# coding: utf-8

"""
    gantry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.activity_message import ActivityMessage
from openapi_client.models.assistant_message import AssistantMessage
from openapi_client.models.developer_message import DeveloperMessage
from openapi_client.models.reasoning_message import ReasoningMessage
from openapi_client.models.system_message import SystemMessage
from openapi_client.models.tool_message import ToolMessage
from openapi_client.models.user_message import UserMessage
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

MESSAGESINNER_ONE_OF_SCHEMAS = ["ActivityMessage", "AssistantMessage", "DeveloperMessage", "ReasoningMessage", "SystemMessage", "ToolMessage", "UserMessage"]

class MessagesInner(BaseModel):
    """
    MessagesInner
    """
    # data type: DeveloperMessage
    oneof_schema_1_validator: Optional[DeveloperMessage] = None
    # data type: SystemMessage
    oneof_schema_2_validator: Optional[SystemMessage] = None
    # data type: AssistantMessage
    oneof_schema_3_validator: Optional[AssistantMessage] = None
    # data type: UserMessage
    oneof_schema_4_validator: Optional[UserMessage] = None
    # data type: ToolMessage
    oneof_schema_5_validator: Optional[ToolMessage] = None
    # data type: ActivityMessage
    oneof_schema_6_validator: Optional[ActivityMessage] = None
    # data type: ReasoningMessage
    oneof_schema_7_validator: Optional[ReasoningMessage] = None
    actual_instance: Optional[Union[ActivityMessage, AssistantMessage, DeveloperMessage, ReasoningMessage, SystemMessage, ToolMessage, UserMessage]] = None
    one_of_schemas: Set[str] = { "ActivityMessage", "AssistantMessage", "DeveloperMessage", "ReasoningMessage", "SystemMessage", "ToolMessage", "UserMessage" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = MessagesInner.model_construct()
        error_messages = []
        match = 0
        # validate data type: DeveloperMessage
        if not isinstance(v, DeveloperMessage):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DeveloperMessage`")
        else:
            match += 1
        # validate data type: SystemMessage
        if not isinstance(v, SystemMessage):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SystemMessage`")
        else:
            match += 1
        # validate data type: AssistantMessage
        if not isinstance(v, AssistantMessage):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AssistantMessage`")
        else:
            match += 1
        # validate data type: UserMessage
        if not isinstance(v, UserMessage):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UserMessage`")
        else:
            match += 1
        # validate data type: ToolMessage
        if not isinstance(v, ToolMessage):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ToolMessage`")
        else:
            match += 1
        # validate data type: ActivityMessage
        if not isinstance(v, ActivityMessage):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ActivityMessage`")
        else:
            match += 1
        # validate data type: ReasoningMessage
        if not isinstance(v, ReasoningMessage):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ReasoningMessage`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in MessagesInner with oneOf schemas: ActivityMessage, AssistantMessage, DeveloperMessage, ReasoningMessage, SystemMessage, ToolMessage, UserMessage. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in MessagesInner with oneOf schemas: ActivityMessage, AssistantMessage, DeveloperMessage, ReasoningMessage, SystemMessage, ToolMessage, UserMessage. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into DeveloperMessage
        try:
            instance.actual_instance = DeveloperMessage.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SystemMessage
        try:
            instance.actual_instance = SystemMessage.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AssistantMessage
        try:
            instance.actual_instance = AssistantMessage.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UserMessage
        try:
            instance.actual_instance = UserMessage.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ToolMessage
        try:
            instance.actual_instance = ToolMessage.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ActivityMessage
        try:
            instance.actual_instance = ActivityMessage.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ReasoningMessage
        try:
            instance.actual_instance = ReasoningMessage.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into MessagesInner with oneOf schemas: ActivityMessage, AssistantMessage, DeveloperMessage, ReasoningMessage, SystemMessage, ToolMessage, UserMessage. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into MessagesInner with oneOf schemas: ActivityMessage, AssistantMessage, DeveloperMessage, ReasoningMessage, SystemMessage, ToolMessage, UserMessage. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ActivityMessage, AssistantMessage, DeveloperMessage, ReasoningMessage, SystemMessage, ToolMessage, UserMessage]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


