# coding: utf-8

"""
    gantry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.keep_separator import KeepSeparator
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RecursiveCharacterTextSplitterOptions(BaseModel):
    """
    RecursiveCharacterTextSplitterOptions
    """ # noqa: E501
    separators: Optional[List[StrictStr]] = None
    keep_separator: Optional[KeepSeparator] = None
    is_separator_regex: Optional[StrictBool] = None
    chunk_size: Optional[StrictInt] = None
    chunk_overlap: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["separators", "keep_separator", "is_separator_regex", "chunk_size", "chunk_overlap"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RecursiveCharacterTextSplitterOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of keep_separator
        if self.keep_separator:
            _dict['keep_separator'] = self.keep_separator.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RecursiveCharacterTextSplitterOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "separators": obj.get("separators"),
            "keep_separator": KeepSeparator.from_dict(obj["keep_separator"]) if obj.get("keep_separator") is not None else None,
            "is_separator_regex": obj.get("is_separator_regex"),
            "chunk_size": obj.get("chunk_size"),
            "chunk_overlap": obj.get("chunk_overlap")
        })
        return _obj


