/*
gantry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)


// KeepSeparator struct for KeepSeparator
type KeepSeparator struct {
	Bool *bool
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *KeepSeparator) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into Bool
	err = json.Unmarshal(data, &dst.Bool);
	if err == nil {
		jsonBool, _ := json.Marshal(dst.Bool)
		if string(jsonBool) == "{}" { // empty struct
			dst.Bool = nil
		} else {
			return nil // data stored in dst.Bool, return on the first match
		}
	} else {
		dst.Bool = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(KeepSeparator)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src KeepSeparator) MarshalJSON() ([]byte, error) {
	if src.Bool != nil {
		return json.Marshal(&src.Bool)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableKeepSeparator struct {
	value *KeepSeparator
	isSet bool
}

func (v NullableKeepSeparator) Get() *KeepSeparator {
	return v.value
}

func (v *NullableKeepSeparator) Set(val *KeepSeparator) {
	v.value = val
	v.isSet = true
}

func (v NullableKeepSeparator) IsSet() bool {
	return v.isSet
}

func (v *NullableKeepSeparator) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeepSeparator(val *KeepSeparator) *NullableKeepSeparator {
	return &NullableKeepSeparator{value: val, isSet: true}
}

func (v NullableKeepSeparator) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeepSeparator) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


