/*
gantry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ReasoningEncryptedValueEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReasoningEncryptedValueEvent{}

// ReasoningEncryptedValueEvent Event containing an encrypted value for a message or tool call.
type ReasoningEncryptedValueEvent struct {
	Type *string `json:"type,omitempty"`
	Timestamp NullableInt32 `json:"timestamp,omitempty"`
	RawEvent NullableAnyOf `json:"rawEvent,omitempty"`
	Subtype string `json:"subtype"`
	EntityId string `json:"entityId"`
	EncryptedValue string `json:"encryptedValue"`
	AdditionalProperties map[string]interface{}
}

type _ReasoningEncryptedValueEvent ReasoningEncryptedValueEvent

// NewReasoningEncryptedValueEvent instantiates a new ReasoningEncryptedValueEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReasoningEncryptedValueEvent(subtype string, entityId string, encryptedValue string) *ReasoningEncryptedValueEvent {
	this := ReasoningEncryptedValueEvent{}
	var type_ string = "REASONING_ENCRYPTED_VALUE"
	this.Type = &type_
	this.Subtype = subtype
	this.EntityId = entityId
	this.EncryptedValue = encryptedValue
	return &this
}

// NewReasoningEncryptedValueEventWithDefaults instantiates a new ReasoningEncryptedValueEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReasoningEncryptedValueEventWithDefaults() *ReasoningEncryptedValueEvent {
	this := ReasoningEncryptedValueEvent{}
	var type_ string = "REASONING_ENCRYPTED_VALUE"
	this.Type = &type_
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ReasoningEncryptedValueEvent) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReasoningEncryptedValueEvent) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ReasoningEncryptedValueEvent) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ReasoningEncryptedValueEvent) SetType(v string) {
	o.Type = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReasoningEncryptedValueEvent) GetTimestamp() int32 {
	if o == nil || IsNil(o.Timestamp.Get()) {
		var ret int32
		return ret
	}
	return *o.Timestamp.Get()
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReasoningEncryptedValueEvent) GetTimestampOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timestamp.Get(), o.Timestamp.IsSet()
}

// HasTimestamp returns a boolean if a field has been set.
func (o *ReasoningEncryptedValueEvent) HasTimestamp() bool {
	if o != nil && o.Timestamp.IsSet() {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given NullableInt32 and assigns it to the Timestamp field.
func (o *ReasoningEncryptedValueEvent) SetTimestamp(v int32) {
	o.Timestamp.Set(&v)
}
// SetTimestampNil sets the value for Timestamp to be an explicit nil
func (o *ReasoningEncryptedValueEvent) SetTimestampNil() {
	o.Timestamp.Set(nil)
}

// UnsetTimestamp ensures that no value is present for Timestamp, not even an explicit nil
func (o *ReasoningEncryptedValueEvent) UnsetTimestamp() {
	o.Timestamp.Unset()
}

// GetRawEvent returns the RawEvent field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReasoningEncryptedValueEvent) GetRawEvent() AnyOf {
	if o == nil || IsNil(o.RawEvent.Get()) {
		var ret AnyOf
		return ret
	}
	return *o.RawEvent.Get()
}

// GetRawEventOk returns a tuple with the RawEvent field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReasoningEncryptedValueEvent) GetRawEventOk() (*AnyOf, bool) {
	if o == nil {
		return nil, false
	}
	return o.RawEvent.Get(), o.RawEvent.IsSet()
}

// HasRawEvent returns a boolean if a field has been set.
func (o *ReasoningEncryptedValueEvent) HasRawEvent() bool {
	if o != nil && o.RawEvent.IsSet() {
		return true
	}

	return false
}

// SetRawEvent gets a reference to the given NullableAnyOf and assigns it to the RawEvent field.
func (o *ReasoningEncryptedValueEvent) SetRawEvent(v AnyOf) {
	o.RawEvent.Set(&v)
}
// SetRawEventNil sets the value for RawEvent to be an explicit nil
func (o *ReasoningEncryptedValueEvent) SetRawEventNil() {
	o.RawEvent.Set(nil)
}

// UnsetRawEvent ensures that no value is present for RawEvent, not even an explicit nil
func (o *ReasoningEncryptedValueEvent) UnsetRawEvent() {
	o.RawEvent.Unset()
}

// GetSubtype returns the Subtype field value
func (o *ReasoningEncryptedValueEvent) GetSubtype() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subtype
}

// GetSubtypeOk returns a tuple with the Subtype field value
// and a boolean to check if the value has been set.
func (o *ReasoningEncryptedValueEvent) GetSubtypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subtype, true
}

// SetSubtype sets field value
func (o *ReasoningEncryptedValueEvent) SetSubtype(v string) {
	o.Subtype = v
}

// GetEntityId returns the EntityId field value
func (o *ReasoningEncryptedValueEvent) GetEntityId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EntityId
}

// GetEntityIdOk returns a tuple with the EntityId field value
// and a boolean to check if the value has been set.
func (o *ReasoningEncryptedValueEvent) GetEntityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntityId, true
}

// SetEntityId sets field value
func (o *ReasoningEncryptedValueEvent) SetEntityId(v string) {
	o.EntityId = v
}

// GetEncryptedValue returns the EncryptedValue field value
func (o *ReasoningEncryptedValueEvent) GetEncryptedValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EncryptedValue
}

// GetEncryptedValueOk returns a tuple with the EncryptedValue field value
// and a boolean to check if the value has been set.
func (o *ReasoningEncryptedValueEvent) GetEncryptedValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EncryptedValue, true
}

// SetEncryptedValue sets field value
func (o *ReasoningEncryptedValueEvent) SetEncryptedValue(v string) {
	o.EncryptedValue = v
}

func (o ReasoningEncryptedValueEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReasoningEncryptedValueEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if o.Timestamp.IsSet() {
		toSerialize["timestamp"] = o.Timestamp.Get()
	}
	if o.RawEvent.IsSet() {
		toSerialize["rawEvent"] = o.RawEvent.Get()
	}
	toSerialize["subtype"] = o.Subtype
	toSerialize["entityId"] = o.EntityId
	toSerialize["encryptedValue"] = o.EncryptedValue

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReasoningEncryptedValueEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"subtype",
		"entityId",
		"encryptedValue",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReasoningEncryptedValueEvent := _ReasoningEncryptedValueEvent{}

	err = json.Unmarshal(data, &varReasoningEncryptedValueEvent)

	if err != nil {
		return err
	}

	*o = ReasoningEncryptedValueEvent(varReasoningEncryptedValueEvent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "timestamp")
		delete(additionalProperties, "rawEvent")
		delete(additionalProperties, "subtype")
		delete(additionalProperties, "entityId")
		delete(additionalProperties, "encryptedValue")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReasoningEncryptedValueEvent struct {
	value *ReasoningEncryptedValueEvent
	isSet bool
}

func (v NullableReasoningEncryptedValueEvent) Get() *ReasoningEncryptedValueEvent {
	return v.value
}

func (v *NullableReasoningEncryptedValueEvent) Set(val *ReasoningEncryptedValueEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableReasoningEncryptedValueEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableReasoningEncryptedValueEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReasoningEncryptedValueEvent(val *ReasoningEncryptedValueEvent) *NullableReasoningEncryptedValueEvent {
	return &NullableReasoningEncryptedValueEvent{value: val, isSet: true}
}

func (v NullableReasoningEncryptedValueEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReasoningEncryptedValueEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


