# coding: utf-8

"""
    gantry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.capture_request import CaptureRequest

class TestCaptureRequest(unittest.TestCase):
    """CaptureRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CaptureRequest:
        """Test CaptureRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CaptureRequest`
        """
        model = CaptureRequest()
        if include_optional:
            return CaptureRequest(
                real_amount = openapi_client.models.scaled_amount.ScaledAmount(
                    value = 56, 
                    scale = 56, )
            )
        else:
            return CaptureRequest(
                real_amount = openapi_client.models.scaled_amount.ScaledAmount(
                    value = 56, 
                    scale = 56, ),
        )
        """

    def testCaptureRequest(self):
        """Test CaptureRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
