/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Event containing a chunk of text message content.
 * @export
 * @interface TextMessageChunkEvent
 */
export interface TextMessageChunkEvent {
    [key: string]: any | any;
    /**
     * 
     * @type {TextMessageChunkEventTypeEnum}
     * @memberof TextMessageChunkEvent
     */
    type?: TextMessageChunkEventTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof TextMessageChunkEvent
     */
    timestamp?: number | null;
    /**
     * 
     * @type {}
     * @memberof TextMessageChunkEvent
     */
    rawEvent?:  | null;
    /**
     * 
     * @type {string}
     * @memberof TextMessageChunkEvent
     */
    messageId?: string | null;
    /**
     * 
     * @type {TextMessageChunkEventRoleEnum}
     * @memberof TextMessageChunkEvent
     */
    role?: TextMessageChunkEventRoleEnum | null;
    /**
     * 
     * @type {string}
     * @memberof TextMessageChunkEvent
     */
    delta?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TextMessageChunkEvent
     */
    name?: string | null;
}


/**
 * @export
 */
export const TextMessageChunkEventTypeEnum = {
    TextMessageChunk: 'TEXT_MESSAGE_CHUNK'
} as const;
export type TextMessageChunkEventTypeEnum = typeof TextMessageChunkEventTypeEnum[keyof typeof TextMessageChunkEventTypeEnum];

/**
 * @export
 */
export const TextMessageChunkEventRoleEnum = {
    Developer: 'developer',
    System: 'system',
    Assistant: 'assistant',
    User: 'user'
} as const;
export type TextMessageChunkEventRoleEnum = typeof TextMessageChunkEventRoleEnum[keyof typeof TextMessageChunkEventRoleEnum];


/**
 * Check if a given object implements the TextMessageChunkEvent interface.
 */
export function instanceOfTextMessageChunkEvent(value: object): value is TextMessageChunkEvent {
    return true;
}

export function TextMessageChunkEventFromJSON(json: any): TextMessageChunkEvent {
    return TextMessageChunkEventFromJSONTyped(json, false);
}

export function TextMessageChunkEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextMessageChunkEvent {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'] == null ? undefined : json['type'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'rawEvent': json['rawEvent'] == null ? undefined : FromJSON(json['rawEvent']),
        'messageId': json['messageId'] == null ? undefined : json['messageId'],
        'role': json['role'] == null ? undefined : json['role'],
        'delta': json['delta'] == null ? undefined : json['delta'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function TextMessageChunkEventToJSON(json: any): TextMessageChunkEvent {
    return TextMessageChunkEventToJSONTyped(json, false);
}

export function TextMessageChunkEventToJSONTyped(value?: TextMessageChunkEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'timestamp': value['timestamp'],
        'rawEvent': ToJSON(value['rawEvent']),
        'messageId': value['messageId'],
        'role': value['role'],
        'delta': value['delta'],
        'name': value['name'],
    };
}

