/*
gantry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the RunAgentInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RunAgentInput{}

// RunAgentInput Input for running an agent.
type RunAgentInput struct {
	ThreadId string `json:"threadId"`
	RunId string `json:"runId"`
	ParentRunId NullableString `json:"parentRunId,omitempty"`
	State interface{} `json:"state"`
	Messages []MessagesInner `json:"messages"`
	Tools []Tool `json:"tools"`
	Context []Context `json:"context"`
	ForwardedProps interface{} `json:"forwardedProps"`
	AdditionalProperties map[string]interface{}
}

type _RunAgentInput RunAgentInput

// NewRunAgentInput instantiates a new RunAgentInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunAgentInput(threadId string, runId string, state interface{}, messages []MessagesInner, tools []Tool, context []Context, forwardedProps interface{}) *RunAgentInput {
	this := RunAgentInput{}
	this.ThreadId = threadId
	this.RunId = runId
	this.State = state
	this.Messages = messages
	this.Tools = tools
	this.Context = context
	this.ForwardedProps = forwardedProps
	return &this
}

// NewRunAgentInputWithDefaults instantiates a new RunAgentInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunAgentInputWithDefaults() *RunAgentInput {
	this := RunAgentInput{}
	return &this
}

// GetThreadId returns the ThreadId field value
func (o *RunAgentInput) GetThreadId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ThreadId
}

// GetThreadIdOk returns a tuple with the ThreadId field value
// and a boolean to check if the value has been set.
func (o *RunAgentInput) GetThreadIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThreadId, true
}

// SetThreadId sets field value
func (o *RunAgentInput) SetThreadId(v string) {
	o.ThreadId = v
}

// GetRunId returns the RunId field value
func (o *RunAgentInput) GetRunId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RunId
}

// GetRunIdOk returns a tuple with the RunId field value
// and a boolean to check if the value has been set.
func (o *RunAgentInput) GetRunIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RunId, true
}

// SetRunId sets field value
func (o *RunAgentInput) SetRunId(v string) {
	o.RunId = v
}

// GetParentRunId returns the ParentRunId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RunAgentInput) GetParentRunId() string {
	if o == nil || IsNil(o.ParentRunId.Get()) {
		var ret string
		return ret
	}
	return *o.ParentRunId.Get()
}

// GetParentRunIdOk returns a tuple with the ParentRunId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RunAgentInput) GetParentRunIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentRunId.Get(), o.ParentRunId.IsSet()
}

// HasParentRunId returns a boolean if a field has been set.
func (o *RunAgentInput) HasParentRunId() bool {
	if o != nil && o.ParentRunId.IsSet() {
		return true
	}

	return false
}

// SetParentRunId gets a reference to the given NullableString and assigns it to the ParentRunId field.
func (o *RunAgentInput) SetParentRunId(v string) {
	o.ParentRunId.Set(&v)
}
// SetParentRunIdNil sets the value for ParentRunId to be an explicit nil
func (o *RunAgentInput) SetParentRunIdNil() {
	o.ParentRunId.Set(nil)
}

// UnsetParentRunId ensures that no value is present for ParentRunId, not even an explicit nil
func (o *RunAgentInput) UnsetParentRunId() {
	o.ParentRunId.Unset()
}

// GetState returns the State field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *RunAgentInput) GetState() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RunAgentInput) GetStateOk() (*interface{}, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *RunAgentInput) SetState(v interface{}) {
	o.State = v
}

// GetMessages returns the Messages field value
func (o *RunAgentInput) GetMessages() []MessagesInner {
	if o == nil {
		var ret []MessagesInner
		return ret
	}

	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value
// and a boolean to check if the value has been set.
func (o *RunAgentInput) GetMessagesOk() ([]MessagesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Messages, true
}

// SetMessages sets field value
func (o *RunAgentInput) SetMessages(v []MessagesInner) {
	o.Messages = v
}

// GetTools returns the Tools field value
func (o *RunAgentInput) GetTools() []Tool {
	if o == nil {
		var ret []Tool
		return ret
	}

	return o.Tools
}

// GetToolsOk returns a tuple with the Tools field value
// and a boolean to check if the value has been set.
func (o *RunAgentInput) GetToolsOk() ([]Tool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tools, true
}

// SetTools sets field value
func (o *RunAgentInput) SetTools(v []Tool) {
	o.Tools = v
}

// GetContext returns the Context field value
func (o *RunAgentInput) GetContext() []Context {
	if o == nil {
		var ret []Context
		return ret
	}

	return o.Context
}

// GetContextOk returns a tuple with the Context field value
// and a boolean to check if the value has been set.
func (o *RunAgentInput) GetContextOk() ([]Context, bool) {
	if o == nil {
		return nil, false
	}
	return o.Context, true
}

// SetContext sets field value
func (o *RunAgentInput) SetContext(v []Context) {
	o.Context = v
}

// GetForwardedProps returns the ForwardedProps field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *RunAgentInput) GetForwardedProps() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.ForwardedProps
}

// GetForwardedPropsOk returns a tuple with the ForwardedProps field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RunAgentInput) GetForwardedPropsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ForwardedProps) {
		return nil, false
	}
	return &o.ForwardedProps, true
}

// SetForwardedProps sets field value
func (o *RunAgentInput) SetForwardedProps(v interface{}) {
	o.ForwardedProps = v
}

func (o RunAgentInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RunAgentInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["threadId"] = o.ThreadId
	toSerialize["runId"] = o.RunId
	if o.ParentRunId.IsSet() {
		toSerialize["parentRunId"] = o.ParentRunId.Get()
	}
	if o.State != nil {
		toSerialize["state"] = o.State
	}
	toSerialize["messages"] = o.Messages
	toSerialize["tools"] = o.Tools
	toSerialize["context"] = o.Context
	if o.ForwardedProps != nil {
		toSerialize["forwardedProps"] = o.ForwardedProps
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RunAgentInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"threadId",
		"runId",
		"state",
		"messages",
		"tools",
		"context",
		"forwardedProps",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRunAgentInput := _RunAgentInput{}

	err = json.Unmarshal(data, &varRunAgentInput)

	if err != nil {
		return err
	}

	*o = RunAgentInput(varRunAgentInput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "threadId")
		delete(additionalProperties, "runId")
		delete(additionalProperties, "parentRunId")
		delete(additionalProperties, "state")
		delete(additionalProperties, "messages")
		delete(additionalProperties, "tools")
		delete(additionalProperties, "context")
		delete(additionalProperties, "forwardedProps")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRunAgentInput struct {
	value *RunAgentInput
	isSet bool
}

func (v NullableRunAgentInput) Get() *RunAgentInput {
	return v.value
}

func (v *NullableRunAgentInput) Set(val *RunAgentInput) {
	v.value = val
	v.isSet = true
}

func (v NullableRunAgentInput) IsSet() bool {
	return v.isSet
}

func (v *NullableRunAgentInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunAgentInput(val *RunAgentInput) *NullableRunAgentInput {
	return &NullableRunAgentInput{value: val, isSet: true}
}

func (v NullableRunAgentInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunAgentInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


