/*
gantry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ReasoningMessageContentEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReasoningMessageContentEvent{}

// ReasoningMessageContentEvent Event containing a piece of reasoning message content.
type ReasoningMessageContentEvent struct {
	Type *string `json:"type,omitempty"`
	Timestamp NullableInt32 `json:"timestamp,omitempty"`
	RawEvent NullableAnyOf `json:"rawEvent,omitempty"`
	MessageId string `json:"messageId"`
	Delta string `json:"delta"`
	AdditionalProperties map[string]interface{}
}

type _ReasoningMessageContentEvent ReasoningMessageContentEvent

// NewReasoningMessageContentEvent instantiates a new ReasoningMessageContentEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReasoningMessageContentEvent(messageId string, delta string) *ReasoningMessageContentEvent {
	this := ReasoningMessageContentEvent{}
	var type_ string = "REASONING_MESSAGE_CONTENT"
	this.Type = &type_
	this.MessageId = messageId
	this.Delta = delta
	return &this
}

// NewReasoningMessageContentEventWithDefaults instantiates a new ReasoningMessageContentEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReasoningMessageContentEventWithDefaults() *ReasoningMessageContentEvent {
	this := ReasoningMessageContentEvent{}
	var type_ string = "REASONING_MESSAGE_CONTENT"
	this.Type = &type_
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ReasoningMessageContentEvent) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReasoningMessageContentEvent) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ReasoningMessageContentEvent) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ReasoningMessageContentEvent) SetType(v string) {
	o.Type = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReasoningMessageContentEvent) GetTimestamp() int32 {
	if o == nil || IsNil(o.Timestamp.Get()) {
		var ret int32
		return ret
	}
	return *o.Timestamp.Get()
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReasoningMessageContentEvent) GetTimestampOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timestamp.Get(), o.Timestamp.IsSet()
}

// HasTimestamp returns a boolean if a field has been set.
func (o *ReasoningMessageContentEvent) HasTimestamp() bool {
	if o != nil && o.Timestamp.IsSet() {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given NullableInt32 and assigns it to the Timestamp field.
func (o *ReasoningMessageContentEvent) SetTimestamp(v int32) {
	o.Timestamp.Set(&v)
}
// SetTimestampNil sets the value for Timestamp to be an explicit nil
func (o *ReasoningMessageContentEvent) SetTimestampNil() {
	o.Timestamp.Set(nil)
}

// UnsetTimestamp ensures that no value is present for Timestamp, not even an explicit nil
func (o *ReasoningMessageContentEvent) UnsetTimestamp() {
	o.Timestamp.Unset()
}

// GetRawEvent returns the RawEvent field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReasoningMessageContentEvent) GetRawEvent() AnyOf {
	if o == nil || IsNil(o.RawEvent.Get()) {
		var ret AnyOf
		return ret
	}
	return *o.RawEvent.Get()
}

// GetRawEventOk returns a tuple with the RawEvent field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReasoningMessageContentEvent) GetRawEventOk() (*AnyOf, bool) {
	if o == nil {
		return nil, false
	}
	return o.RawEvent.Get(), o.RawEvent.IsSet()
}

// HasRawEvent returns a boolean if a field has been set.
func (o *ReasoningMessageContentEvent) HasRawEvent() bool {
	if o != nil && o.RawEvent.IsSet() {
		return true
	}

	return false
}

// SetRawEvent gets a reference to the given NullableAnyOf and assigns it to the RawEvent field.
func (o *ReasoningMessageContentEvent) SetRawEvent(v AnyOf) {
	o.RawEvent.Set(&v)
}
// SetRawEventNil sets the value for RawEvent to be an explicit nil
func (o *ReasoningMessageContentEvent) SetRawEventNil() {
	o.RawEvent.Set(nil)
}

// UnsetRawEvent ensures that no value is present for RawEvent, not even an explicit nil
func (o *ReasoningMessageContentEvent) UnsetRawEvent() {
	o.RawEvent.Unset()
}

// GetMessageId returns the MessageId field value
func (o *ReasoningMessageContentEvent) GetMessageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MessageId
}

// GetMessageIdOk returns a tuple with the MessageId field value
// and a boolean to check if the value has been set.
func (o *ReasoningMessageContentEvent) GetMessageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageId, true
}

// SetMessageId sets field value
func (o *ReasoningMessageContentEvent) SetMessageId(v string) {
	o.MessageId = v
}

// GetDelta returns the Delta field value
func (o *ReasoningMessageContentEvent) GetDelta() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Delta
}

// GetDeltaOk returns a tuple with the Delta field value
// and a boolean to check if the value has been set.
func (o *ReasoningMessageContentEvent) GetDeltaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Delta, true
}

// SetDelta sets field value
func (o *ReasoningMessageContentEvent) SetDelta(v string) {
	o.Delta = v
}

func (o ReasoningMessageContentEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReasoningMessageContentEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if o.Timestamp.IsSet() {
		toSerialize["timestamp"] = o.Timestamp.Get()
	}
	if o.RawEvent.IsSet() {
		toSerialize["rawEvent"] = o.RawEvent.Get()
	}
	toSerialize["messageId"] = o.MessageId
	toSerialize["delta"] = o.Delta

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReasoningMessageContentEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"messageId",
		"delta",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReasoningMessageContentEvent := _ReasoningMessageContentEvent{}

	err = json.Unmarshal(data, &varReasoningMessageContentEvent)

	if err != nil {
		return err
	}

	*o = ReasoningMessageContentEvent(varReasoningMessageContentEvent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "timestamp")
		delete(additionalProperties, "rawEvent")
		delete(additionalProperties, "messageId")
		delete(additionalProperties, "delta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReasoningMessageContentEvent struct {
	value *ReasoningMessageContentEvent
	isSet bool
}

func (v NullableReasoningMessageContentEvent) Get() *ReasoningMessageContentEvent {
	return v.value
}

func (v *NullableReasoningMessageContentEvent) Set(val *ReasoningMessageContentEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableReasoningMessageContentEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableReasoningMessageContentEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReasoningMessageContentEvent(val *ReasoningMessageContentEvent) *NullableReasoningMessageContentEvent {
	return &NullableReasoningMessageContentEvent{value: val, isSet: true}
}

func (v NullableReasoningMessageContentEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReasoningMessageContentEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


