/*
gantry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the FileInfoWithPresignedURLResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileInfoWithPresignedURLResponse{}

// FileInfoWithPresignedURLResponse DTO for file info with URL response.
type FileInfoWithPresignedURLResponse struct {
	Url string `json:"url"`
	Id string `json:"id"`
	Filename string `json:"filename"`
	MimeType string `json:"mime_type"`
	Size int32 `json:"size"`
	CreatedAt time.Time `json:"created_at"`
	ExtraMetadata map[string]interface{} `json:"extra_metadata"`
}

type _FileInfoWithPresignedURLResponse FileInfoWithPresignedURLResponse

// NewFileInfoWithPresignedURLResponse instantiates a new FileInfoWithPresignedURLResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileInfoWithPresignedURLResponse(url string, id string, filename string, mimeType string, size int32, createdAt time.Time, extraMetadata map[string]interface{}) *FileInfoWithPresignedURLResponse {
	this := FileInfoWithPresignedURLResponse{}
	this.Url = url
	this.Id = id
	this.Filename = filename
	this.MimeType = mimeType
	this.Size = size
	this.CreatedAt = createdAt
	this.ExtraMetadata = extraMetadata
	return &this
}

// NewFileInfoWithPresignedURLResponseWithDefaults instantiates a new FileInfoWithPresignedURLResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileInfoWithPresignedURLResponseWithDefaults() *FileInfoWithPresignedURLResponse {
	this := FileInfoWithPresignedURLResponse{}
	return &this
}

// GetUrl returns the Url field value
func (o *FileInfoWithPresignedURLResponse) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *FileInfoWithPresignedURLResponse) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *FileInfoWithPresignedURLResponse) SetUrl(v string) {
	o.Url = v
}

// GetId returns the Id field value
func (o *FileInfoWithPresignedURLResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FileInfoWithPresignedURLResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FileInfoWithPresignedURLResponse) SetId(v string) {
	o.Id = v
}

// GetFilename returns the Filename field value
func (o *FileInfoWithPresignedURLResponse) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *FileInfoWithPresignedURLResponse) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *FileInfoWithPresignedURLResponse) SetFilename(v string) {
	o.Filename = v
}

// GetMimeType returns the MimeType field value
func (o *FileInfoWithPresignedURLResponse) GetMimeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MimeType
}

// GetMimeTypeOk returns a tuple with the MimeType field value
// and a boolean to check if the value has been set.
func (o *FileInfoWithPresignedURLResponse) GetMimeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MimeType, true
}

// SetMimeType sets field value
func (o *FileInfoWithPresignedURLResponse) SetMimeType(v string) {
	o.MimeType = v
}

// GetSize returns the Size field value
func (o *FileInfoWithPresignedURLResponse) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *FileInfoWithPresignedURLResponse) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *FileInfoWithPresignedURLResponse) SetSize(v int32) {
	o.Size = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *FileInfoWithPresignedURLResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *FileInfoWithPresignedURLResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *FileInfoWithPresignedURLResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetExtraMetadata returns the ExtraMetadata field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *FileInfoWithPresignedURLResponse) GetExtraMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.ExtraMetadata
}

// GetExtraMetadataOk returns a tuple with the ExtraMetadata field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FileInfoWithPresignedURLResponse) GetExtraMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ExtraMetadata) {
		return map[string]interface{}{}, false
	}
	return o.ExtraMetadata, true
}

// SetExtraMetadata sets field value
func (o *FileInfoWithPresignedURLResponse) SetExtraMetadata(v map[string]interface{}) {
	o.ExtraMetadata = v
}

func (o FileInfoWithPresignedURLResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileInfoWithPresignedURLResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	toSerialize["id"] = o.Id
	toSerialize["filename"] = o.Filename
	toSerialize["mime_type"] = o.MimeType
	toSerialize["size"] = o.Size
	toSerialize["created_at"] = o.CreatedAt
	if o.ExtraMetadata != nil {
		toSerialize["extra_metadata"] = o.ExtraMetadata
	}
	return toSerialize, nil
}

func (o *FileInfoWithPresignedURLResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
		"id",
		"filename",
		"mime_type",
		"size",
		"created_at",
		"extra_metadata",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFileInfoWithPresignedURLResponse := _FileInfoWithPresignedURLResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFileInfoWithPresignedURLResponse)

	if err != nil {
		return err
	}

	*o = FileInfoWithPresignedURLResponse(varFileInfoWithPresignedURLResponse)

	return err
}

type NullableFileInfoWithPresignedURLResponse struct {
	value *FileInfoWithPresignedURLResponse
	isSet bool
}

func (v NullableFileInfoWithPresignedURLResponse) Get() *FileInfoWithPresignedURLResponse {
	return v.value
}

func (v *NullableFileInfoWithPresignedURLResponse) Set(val *FileInfoWithPresignedURLResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFileInfoWithPresignedURLResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFileInfoWithPresignedURLResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileInfoWithPresignedURLResponse(val *FileInfoWithPresignedURLResponse) *NullableFileInfoWithPresignedURLResponse {
	return &NullableFileInfoWithPresignedURLResponse{value: val, isSet: true}
}

func (v NullableFileInfoWithPresignedURLResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileInfoWithPresignedURLResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


