/*
gantry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FilePresignedURLResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilePresignedURLResponse{}

// FilePresignedURLResponse DTO for file presigned URL response.
type FilePresignedURLResponse struct {
	Url string `json:"url"`
}

type _FilePresignedURLResponse FilePresignedURLResponse

// NewFilePresignedURLResponse instantiates a new FilePresignedURLResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilePresignedURLResponse(url string) *FilePresignedURLResponse {
	this := FilePresignedURLResponse{}
	this.Url = url
	return &this
}

// NewFilePresignedURLResponseWithDefaults instantiates a new FilePresignedURLResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilePresignedURLResponseWithDefaults() *FilePresignedURLResponse {
	this := FilePresignedURLResponse{}
	return &this
}

// GetUrl returns the Url field value
func (o *FilePresignedURLResponse) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *FilePresignedURLResponse) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *FilePresignedURLResponse) SetUrl(v string) {
	o.Url = v
}

func (o FilePresignedURLResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilePresignedURLResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *FilePresignedURLResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFilePresignedURLResponse := _FilePresignedURLResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFilePresignedURLResponse)

	if err != nil {
		return err
	}

	*o = FilePresignedURLResponse(varFilePresignedURLResponse)

	return err
}

type NullableFilePresignedURLResponse struct {
	value *FilePresignedURLResponse
	isSet bool
}

func (v NullableFilePresignedURLResponse) Get() *FilePresignedURLResponse {
	return v.value
}

func (v *NullableFilePresignedURLResponse) Set(val *FilePresignedURLResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFilePresignedURLResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFilePresignedURLResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilePresignedURLResponse(val *FilePresignedURLResponse) *NullableFilePresignedURLResponse {
	return &NullableFilePresignedURLResponse{value: val, isSet: true}
}

func (v NullableFilePresignedURLResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilePresignedURLResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


