/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Inline base64-encoded source.
 * @export
 * @interface InputContentDataSource
 */
export interface InputContentDataSource {
    [key: string]: any | any;
    /**
     * 
     * @type {InputContentDataSourceTypeEnum}
     * @memberof InputContentDataSource
     */
    type?: InputContentDataSourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof InputContentDataSource
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof InputContentDataSource
     */
    mimeType: string;
}


/**
 * @export
 */
export const InputContentDataSourceTypeEnum = {
    Data: 'data'
} as const;
export type InputContentDataSourceTypeEnum = typeof InputContentDataSourceTypeEnum[keyof typeof InputContentDataSourceTypeEnum];


/**
 * Check if a given object implements the InputContentDataSource interface.
 */
export function instanceOfInputContentDataSource(value: object): value is InputContentDataSource {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    return true;
}

export function InputContentDataSourceFromJSON(json: any): InputContentDataSource {
    return InputContentDataSourceFromJSONTyped(json, false);
}

export function InputContentDataSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): InputContentDataSource {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'] == null ? undefined : json['type'],
        'value': json['value'],
        'mimeType': json['mimeType'],
    };
}

export function InputContentDataSourceToJSON(json: any): InputContentDataSource {
    return InputContentDataSourceToJSONTyped(json, false);
}

export function InputContentDataSourceToJSONTyped(value?: InputContentDataSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'value': value['value'],
        'mimeType': value['mimeType'],
    };
}

