/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileInfoResponse } from './FileInfoResponse';
import {
    FileInfoResponseFromJSON,
    FileInfoResponseFromJSONTyped,
    FileInfoResponseToJSON,
    FileInfoResponseToJSONTyped,
} from './FileInfoResponse';

/**
 * DTO for RAG query response.
 * @export
 * @interface RagQueryResponse
 */
export interface RagQueryResponse {
    /**
     * 
     * @type {FileInfoResponse}
     * @memberof RagQueryResponse
     */
    fileInfo: FileInfoResponse | null;
    /**
     * 
     * @type {string}
     * @memberof RagQueryResponse
     */
    text: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof RagQueryResponse
     */
    embedding: Array<number>;
    /**
     * 
     * @type {Date}
     * @memberof RagQueryResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof RagQueryResponse
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * 
     * @type {number}
     * @memberof RagQueryResponse
     */
    vectorDistance?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RagQueryResponse
     */
    bm25Score?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RagQueryResponse
     */
    rerankScore?: number | null;
}

/**
 * Check if a given object implements the RagQueryResponse interface.
 */
export function instanceOfRagQueryResponse(value: object): value is RagQueryResponse {
    if (!('fileInfo' in value) || value['fileInfo'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('embedding' in value) || value['embedding'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function RagQueryResponseFromJSON(json: any): RagQueryResponse {
    return RagQueryResponseFromJSONTyped(json, false);
}

export function RagQueryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RagQueryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'fileInfo': FileInfoResponseFromJSON(json['file_info']),
        'text': json['text'],
        'embedding': json['embedding'],
        'createdAt': (new Date(json['created_at'])),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'vectorDistance': json['vector_distance'] == null ? undefined : json['vector_distance'],
        'bm25Score': json['bm25_score'] == null ? undefined : json['bm25_score'],
        'rerankScore': json['rerank_score'] == null ? undefined : json['rerank_score'],
    };
}

export function RagQueryResponseToJSON(json: any): RagQueryResponse {
    return RagQueryResponseToJSONTyped(json, false);
}

export function RagQueryResponseToJSONTyped(value?: RagQueryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file_info': FileInfoResponseToJSON(value['fileInfo']),
        'text': value['text'],
        'embedding': value['embedding'],
        'created_at': value['createdAt'].toISOString(),
        'metadata': value['metadata'],
        'vector_distance': value['vectorDistance'],
        'bm25_score': value['bm25Score'],
        'rerank_score': value['rerankScore'],
    };
}

