/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Event containing a raw event.
 * @export
 * @interface RawEvent
 */
export interface RawEvent {
    [key: string]: any | any;
    /**
     * 
     * @type {RawEventTypeEnum}
     * @memberof RawEvent
     */
    type?: RawEventTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof RawEvent
     */
    timestamp?: number | null;
    /**
     * 
     * @type {}
     * @memberof RawEvent
     */
    rawEvent?:  | null;
    /**
     * 
     * @type {any}
     * @memberof RawEvent
     */
    event: any | null;
    /**
     * 
     * @type {string}
     * @memberof RawEvent
     */
    source?: string | null;
}


/**
 * @export
 */
export const RawEventTypeEnum = {
    Raw: 'RAW'
} as const;
export type RawEventTypeEnum = typeof RawEventTypeEnum[keyof typeof RawEventTypeEnum];


/**
 * Check if a given object implements the RawEvent interface.
 */
export function instanceOfRawEvent(value: object): value is RawEvent {
    if (!('event' in value) || value['event'] === undefined) return false;
    return true;
}

export function RawEventFromJSON(json: any): RawEvent {
    return RawEventFromJSONTyped(json, false);
}

export function RawEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): RawEvent {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'] == null ? undefined : json['type'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'rawEvent': json['rawEvent'] == null ? undefined : FromJSON(json['rawEvent']),
        'event': json['event'],
        'source': json['source'] == null ? undefined : json['source'],
    };
}

export function RawEventToJSON(json: any): RawEvent {
    return RawEventToJSONTyped(json, false);
}

export function RawEventToJSONTyped(value?: RawEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'timestamp': value['timestamp'],
        'rawEvent': ToJSON(value['rawEvent']),
        'event': value['event'],
        'source': value['source'],
    };
}

