/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A system message.
 * @export
 * @interface SystemMessage
 */
export interface SystemMessage {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof SystemMessage
     */
    id: string;
    /**
     * 
     * @type {SystemMessageRoleEnum}
     * @memberof SystemMessage
     */
    role?: SystemMessageRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof SystemMessage
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof SystemMessage
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SystemMessage
     */
    encryptedValue?: string | null;
}


/**
 * @export
 */
export const SystemMessageRoleEnum = {
    System: 'system'
} as const;
export type SystemMessageRoleEnum = typeof SystemMessageRoleEnum[keyof typeof SystemMessageRoleEnum];


/**
 * Check if a given object implements the SystemMessage interface.
 */
export function instanceOfSystemMessage(value: object): value is SystemMessage {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function SystemMessageFromJSON(json: any): SystemMessage {
    return SystemMessageFromJSONTyped(json, false);
}

export function SystemMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemMessage {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'role': json['role'] == null ? undefined : json['role'],
        'content': json['content'],
        'name': json['name'] == null ? undefined : json['name'],
        'encryptedValue': json['encryptedValue'] == null ? undefined : json['encryptedValue'],
    };
}

export function SystemMessageToJSON(json: any): SystemMessage {
    return SystemMessageToJSONTyped(json, false);
}

export function SystemMessageToJSONTyped(value?: SystemMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'role': value['role'],
        'content': value['content'],
        'name': value['name'],
        'encryptedValue': value['encryptedValue'],
    };
}

