/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KeepSeparator
 */
export interface KeepSeparator {
}

/**
 * Check if a given object implements the KeepSeparator interface.
 */
export function instanceOfKeepSeparator(value: object): value is KeepSeparator {
    return true;
}

export function KeepSeparatorFromJSON(json: any): KeepSeparator {
    return KeepSeparatorFromJSONTyped(json, false);
}

export function KeepSeparatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeepSeparator {
    return json;
}

export function KeepSeparatorToJSON(json: any): KeepSeparator {
    return KeepSeparatorToJSONTyped(json, false);
}

export function KeepSeparatorToJSONTyped(value?: KeepSeparator | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

