/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NLTKTextSplitterOptions
 */
export interface NLTKTextSplitterOptions {
    /**
     * 
     * @type {string}
     * @memberof NLTKTextSplitterOptions
     */
    separator?: string;
    /**
     * 
     * @type {string}
     * @memberof NLTKTextSplitterOptions
     */
    language?: string;
    /**
     * 
     * @type {boolean}
     * @memberof NLTKTextSplitterOptions
     */
    useSpanTokenize?: boolean;
    /**
     * 
     * @type {number}
     * @memberof NLTKTextSplitterOptions
     */
    chunkSize?: number;
    /**
     * 
     * @type {number}
     * @memberof NLTKTextSplitterOptions
     */
    chunkOverlap?: number;
}

/**
 * Check if a given object implements the NLTKTextSplitterOptions interface.
 */
export function instanceOfNLTKTextSplitterOptions(value: object): value is NLTKTextSplitterOptions {
    return true;
}

export function NLTKTextSplitterOptionsFromJSON(json: any): NLTKTextSplitterOptions {
    return NLTKTextSplitterOptionsFromJSONTyped(json, false);
}

export function NLTKTextSplitterOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NLTKTextSplitterOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'separator': json['separator'] == null ? undefined : json['separator'],
        'language': json['language'] == null ? undefined : json['language'],
        'useSpanTokenize': json['use_span_tokenize'] == null ? undefined : json['use_span_tokenize'],
        'chunkSize': json['chunk_size'] == null ? undefined : json['chunk_size'],
        'chunkOverlap': json['chunk_overlap'] == null ? undefined : json['chunk_overlap'],
    };
}

export function NLTKTextSplitterOptionsToJSON(json: any): NLTKTextSplitterOptions {
    return NLTKTextSplitterOptionsToJSONTyped(json, false);
}

export function NLTKTextSplitterOptionsToJSONTyped(value?: NLTKTextSplitterOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'separator': value['separator'],
        'language': value['language'],
        'use_span_tokenize': value['useSpanTokenize'],
        'chunk_size': value['chunkSize'],
        'chunk_overlap': value['chunkOverlap'],
    };
}

