/*
gantry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the SystemMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemMessage{}

// SystemMessage A system message.
type SystemMessage struct {
	Id string `json:"id"`
	Role *string `json:"role,omitempty"`
	Content string `json:"content"`
	Name NullableString `json:"name,omitempty"`
	EncryptedValue NullableString `json:"encryptedValue,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SystemMessage SystemMessage

// NewSystemMessage instantiates a new SystemMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemMessage(id string, content string) *SystemMessage {
	this := SystemMessage{}
	this.Id = id
	var role string = "system"
	this.Role = &role
	this.Content = content
	return &this
}

// NewSystemMessageWithDefaults instantiates a new SystemMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemMessageWithDefaults() *SystemMessage {
	this := SystemMessage{}
	var role string = "system"
	this.Role = &role
	return &this
}

// GetId returns the Id field value
func (o *SystemMessage) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SystemMessage) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SystemMessage) SetId(v string) {
	o.Id = v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *SystemMessage) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemMessage) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *SystemMessage) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *SystemMessage) SetRole(v string) {
	o.Role = &v
}

// GetContent returns the Content field value
func (o *SystemMessage) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *SystemMessage) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *SystemMessage) SetContent(v string) {
	o.Content = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SystemMessage) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SystemMessage) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *SystemMessage) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *SystemMessage) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *SystemMessage) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *SystemMessage) UnsetName() {
	o.Name.Unset()
}

// GetEncryptedValue returns the EncryptedValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SystemMessage) GetEncryptedValue() string {
	if o == nil || IsNil(o.EncryptedValue.Get()) {
		var ret string
		return ret
	}
	return *o.EncryptedValue.Get()
}

// GetEncryptedValueOk returns a tuple with the EncryptedValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SystemMessage) GetEncryptedValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EncryptedValue.Get(), o.EncryptedValue.IsSet()
}

// HasEncryptedValue returns a boolean if a field has been set.
func (o *SystemMessage) HasEncryptedValue() bool {
	if o != nil && o.EncryptedValue.IsSet() {
		return true
	}

	return false
}

// SetEncryptedValue gets a reference to the given NullableString and assigns it to the EncryptedValue field.
func (o *SystemMessage) SetEncryptedValue(v string) {
	o.EncryptedValue.Set(&v)
}
// SetEncryptedValueNil sets the value for EncryptedValue to be an explicit nil
func (o *SystemMessage) SetEncryptedValueNil() {
	o.EncryptedValue.Set(nil)
}

// UnsetEncryptedValue ensures that no value is present for EncryptedValue, not even an explicit nil
func (o *SystemMessage) UnsetEncryptedValue() {
	o.EncryptedValue.Unset()
}

func (o SystemMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	toSerialize["content"] = o.Content
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.EncryptedValue.IsSet() {
		toSerialize["encryptedValue"] = o.EncryptedValue.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SystemMessage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSystemMessage := _SystemMessage{}

	err = json.Unmarshal(data, &varSystemMessage)

	if err != nil {
		return err
	}

	*o = SystemMessage(varSystemMessage)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "role")
		delete(additionalProperties, "content")
		delete(additionalProperties, "name")
		delete(additionalProperties, "encryptedValue")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSystemMessage struct {
	value *SystemMessage
	isSet bool
}

func (v NullableSystemMessage) Get() *SystemMessage {
	return v.value
}

func (v *NullableSystemMessage) Set(val *SystemMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemMessage(val *SystemMessage) *NullableSystemMessage {
	return &NullableSystemMessage{value: val, isSet: true}
}

func (v NullableSystemMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


