/*
gantry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ReasoningEndEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReasoningEndEvent{}

// ReasoningEndEvent Event indicating the end of a reasoning phase.
type ReasoningEndEvent struct {
	Type *string `json:"type,omitempty"`
	Timestamp NullableInt32 `json:"timestamp,omitempty"`
	RawEvent NullableAnyOf `json:"rawEvent,omitempty"`
	MessageId string `json:"messageId"`
	AdditionalProperties map[string]interface{}
}

type _ReasoningEndEvent ReasoningEndEvent

// NewReasoningEndEvent instantiates a new ReasoningEndEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReasoningEndEvent(messageId string) *ReasoningEndEvent {
	this := ReasoningEndEvent{}
	var type_ string = "REASONING_END"
	this.Type = &type_
	this.MessageId = messageId
	return &this
}

// NewReasoningEndEventWithDefaults instantiates a new ReasoningEndEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReasoningEndEventWithDefaults() *ReasoningEndEvent {
	this := ReasoningEndEvent{}
	var type_ string = "REASONING_END"
	this.Type = &type_
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ReasoningEndEvent) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReasoningEndEvent) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ReasoningEndEvent) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ReasoningEndEvent) SetType(v string) {
	o.Type = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReasoningEndEvent) GetTimestamp() int32 {
	if o == nil || IsNil(o.Timestamp.Get()) {
		var ret int32
		return ret
	}
	return *o.Timestamp.Get()
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReasoningEndEvent) GetTimestampOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timestamp.Get(), o.Timestamp.IsSet()
}

// HasTimestamp returns a boolean if a field has been set.
func (o *ReasoningEndEvent) HasTimestamp() bool {
	if o != nil && o.Timestamp.IsSet() {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given NullableInt32 and assigns it to the Timestamp field.
func (o *ReasoningEndEvent) SetTimestamp(v int32) {
	o.Timestamp.Set(&v)
}
// SetTimestampNil sets the value for Timestamp to be an explicit nil
func (o *ReasoningEndEvent) SetTimestampNil() {
	o.Timestamp.Set(nil)
}

// UnsetTimestamp ensures that no value is present for Timestamp, not even an explicit nil
func (o *ReasoningEndEvent) UnsetTimestamp() {
	o.Timestamp.Unset()
}

// GetRawEvent returns the RawEvent field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReasoningEndEvent) GetRawEvent() AnyOf {
	if o == nil || IsNil(o.RawEvent.Get()) {
		var ret AnyOf
		return ret
	}
	return *o.RawEvent.Get()
}

// GetRawEventOk returns a tuple with the RawEvent field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReasoningEndEvent) GetRawEventOk() (*AnyOf, bool) {
	if o == nil {
		return nil, false
	}
	return o.RawEvent.Get(), o.RawEvent.IsSet()
}

// HasRawEvent returns a boolean if a field has been set.
func (o *ReasoningEndEvent) HasRawEvent() bool {
	if o != nil && o.RawEvent.IsSet() {
		return true
	}

	return false
}

// SetRawEvent gets a reference to the given NullableAnyOf and assigns it to the RawEvent field.
func (o *ReasoningEndEvent) SetRawEvent(v AnyOf) {
	o.RawEvent.Set(&v)
}
// SetRawEventNil sets the value for RawEvent to be an explicit nil
func (o *ReasoningEndEvent) SetRawEventNil() {
	o.RawEvent.Set(nil)
}

// UnsetRawEvent ensures that no value is present for RawEvent, not even an explicit nil
func (o *ReasoningEndEvent) UnsetRawEvent() {
	o.RawEvent.Unset()
}

// GetMessageId returns the MessageId field value
func (o *ReasoningEndEvent) GetMessageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MessageId
}

// GetMessageIdOk returns a tuple with the MessageId field value
// and a boolean to check if the value has been set.
func (o *ReasoningEndEvent) GetMessageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageId, true
}

// SetMessageId sets field value
func (o *ReasoningEndEvent) SetMessageId(v string) {
	o.MessageId = v
}

func (o ReasoningEndEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReasoningEndEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if o.Timestamp.IsSet() {
		toSerialize["timestamp"] = o.Timestamp.Get()
	}
	if o.RawEvent.IsSet() {
		toSerialize["rawEvent"] = o.RawEvent.Get()
	}
	toSerialize["messageId"] = o.MessageId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReasoningEndEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"messageId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReasoningEndEvent := _ReasoningEndEvent{}

	err = json.Unmarshal(data, &varReasoningEndEvent)

	if err != nil {
		return err
	}

	*o = ReasoningEndEvent(varReasoningEndEvent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "timestamp")
		delete(additionalProperties, "rawEvent")
		delete(additionalProperties, "messageId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReasoningEndEvent struct {
	value *ReasoningEndEvent
	isSet bool
}

func (v NullableReasoningEndEvent) Get() *ReasoningEndEvent {
	return v.value
}

func (v *NullableReasoningEndEvent) Set(val *ReasoningEndEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableReasoningEndEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableReasoningEndEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReasoningEndEvent(val *ReasoningEndEvent) *NullableReasoningEndEvent {
	return &NullableReasoningEndEvent{value: val, isSet: true}
}

func (v NullableReasoningEndEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReasoningEndEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


