/*
gantry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RecursiveJsonSplitterOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecursiveJsonSplitterOptions{}

// RecursiveJsonSplitterOptions struct for RecursiveJsonSplitterOptions
type RecursiveJsonSplitterOptions struct {
	MaxChunkSize *int32 `json:"max_chunk_size,omitempty"`
	MinChunkSize *int32 `json:"min_chunk_size,omitempty"`
	ConvertLists *bool `json:"convert_lists,omitempty"`
}

// NewRecursiveJsonSplitterOptions instantiates a new RecursiveJsonSplitterOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecursiveJsonSplitterOptions() *RecursiveJsonSplitterOptions {
	this := RecursiveJsonSplitterOptions{}
	return &this
}

// NewRecursiveJsonSplitterOptionsWithDefaults instantiates a new RecursiveJsonSplitterOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecursiveJsonSplitterOptionsWithDefaults() *RecursiveJsonSplitterOptions {
	this := RecursiveJsonSplitterOptions{}
	return &this
}

// GetMaxChunkSize returns the MaxChunkSize field value if set, zero value otherwise.
func (o *RecursiveJsonSplitterOptions) GetMaxChunkSize() int32 {
	if o == nil || IsNil(o.MaxChunkSize) {
		var ret int32
		return ret
	}
	return *o.MaxChunkSize
}

// GetMaxChunkSizeOk returns a tuple with the MaxChunkSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecursiveJsonSplitterOptions) GetMaxChunkSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxChunkSize) {
		return nil, false
	}
	return o.MaxChunkSize, true
}

// HasMaxChunkSize returns a boolean if a field has been set.
func (o *RecursiveJsonSplitterOptions) HasMaxChunkSize() bool {
	if o != nil && !IsNil(o.MaxChunkSize) {
		return true
	}

	return false
}

// SetMaxChunkSize gets a reference to the given int32 and assigns it to the MaxChunkSize field.
func (o *RecursiveJsonSplitterOptions) SetMaxChunkSize(v int32) {
	o.MaxChunkSize = &v
}

// GetMinChunkSize returns the MinChunkSize field value if set, zero value otherwise.
func (o *RecursiveJsonSplitterOptions) GetMinChunkSize() int32 {
	if o == nil || IsNil(o.MinChunkSize) {
		var ret int32
		return ret
	}
	return *o.MinChunkSize
}

// GetMinChunkSizeOk returns a tuple with the MinChunkSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecursiveJsonSplitterOptions) GetMinChunkSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.MinChunkSize) {
		return nil, false
	}
	return o.MinChunkSize, true
}

// HasMinChunkSize returns a boolean if a field has been set.
func (o *RecursiveJsonSplitterOptions) HasMinChunkSize() bool {
	if o != nil && !IsNil(o.MinChunkSize) {
		return true
	}

	return false
}

// SetMinChunkSize gets a reference to the given int32 and assigns it to the MinChunkSize field.
func (o *RecursiveJsonSplitterOptions) SetMinChunkSize(v int32) {
	o.MinChunkSize = &v
}

// GetConvertLists returns the ConvertLists field value if set, zero value otherwise.
func (o *RecursiveJsonSplitterOptions) GetConvertLists() bool {
	if o == nil || IsNil(o.ConvertLists) {
		var ret bool
		return ret
	}
	return *o.ConvertLists
}

// GetConvertListsOk returns a tuple with the ConvertLists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecursiveJsonSplitterOptions) GetConvertListsOk() (*bool, bool) {
	if o == nil || IsNil(o.ConvertLists) {
		return nil, false
	}
	return o.ConvertLists, true
}

// HasConvertLists returns a boolean if a field has been set.
func (o *RecursiveJsonSplitterOptions) HasConvertLists() bool {
	if o != nil && !IsNil(o.ConvertLists) {
		return true
	}

	return false
}

// SetConvertLists gets a reference to the given bool and assigns it to the ConvertLists field.
func (o *RecursiveJsonSplitterOptions) SetConvertLists(v bool) {
	o.ConvertLists = &v
}

func (o RecursiveJsonSplitterOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecursiveJsonSplitterOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MaxChunkSize) {
		toSerialize["max_chunk_size"] = o.MaxChunkSize
	}
	if !IsNil(o.MinChunkSize) {
		toSerialize["min_chunk_size"] = o.MinChunkSize
	}
	if !IsNil(o.ConvertLists) {
		toSerialize["convert_lists"] = o.ConvertLists
	}
	return toSerialize, nil
}

type NullableRecursiveJsonSplitterOptions struct {
	value *RecursiveJsonSplitterOptions
	isSet bool
}

func (v NullableRecursiveJsonSplitterOptions) Get() *RecursiveJsonSplitterOptions {
	return v.value
}

func (v *NullableRecursiveJsonSplitterOptions) Set(val *RecursiveJsonSplitterOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableRecursiveJsonSplitterOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableRecursiveJsonSplitterOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecursiveJsonSplitterOptions(val *RecursiveJsonSplitterOptions) *NullableRecursiveJsonSplitterOptions {
	return &NullableRecursiveJsonSplitterOptions{value: val, isSet: true}
}

func (v NullableRecursiveJsonSplitterOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecursiveJsonSplitterOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


