# coding: utf-8

"""
    gantry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.ai_gateway_api import AiGatewayApi


class TestAiGatewayApi(unittest.TestCase):
    """AiGatewayApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AiGatewayApi()

    def tearDown(self) -> None:
        pass

    def test_ag_ui_gateway_ai_gateway_ag_ui_model_post(self) -> None:
        """Test case for ag_ui_gateway_ai_gateway_ag_ui_model_post

        Ag Ui Gateway
        """
        pass

    def test_get_models_ai_gateway_models_get(self) -> None:
        """Test case for get_models_ai_gateway_models_get

        Get Models
        """
        pass


if __name__ == '__main__':
    unittest.main()
