# coding: utf-8

"""
    gantry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.html_header_text_splitter_options import HTMLHeaderTextSplitterOptions

class TestHTMLHeaderTextSplitterOptions(unittest.TestCase):
    """HTMLHeaderTextSplitterOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HTMLHeaderTextSplitterOptions:
        """Test HTMLHeaderTextSplitterOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HTMLHeaderTextSplitterOptions`
        """
        model = HTMLHeaderTextSplitterOptions()
        if include_optional:
            return HTMLHeaderTextSplitterOptions(
                headers_to_split_on = [
                    [
                        null
                        ]
                    ],
                return_each_element = True
            )
        else:
            return HTMLHeaderTextSplitterOptions(
        )
        """

    def testHTMLHeaderTextSplitterOptions(self):
        """Test HTMLHeaderTextSplitterOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
