# coding: utf-8

"""
    gantry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.content_any_of_inner import ContentAnyOfInner

class TestContentAnyOfInner(unittest.TestCase):
    """ContentAnyOfInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentAnyOfInner:
        """Test ContentAnyOfInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentAnyOfInner`
        """
        model = ContentAnyOfInner()
        if include_optional:
            return ContentAnyOfInner(
                type = 'text',
                text = '',
                source = None,
                metadata = None,
                mime_type = '',
                id = '',
                url = '',
                data = '',
                filename = ''
            )
        else:
            return ContentAnyOfInner(
                text = '',
                source = None,
                mime_type = '',
        )
        """

    def testContentAnyOfInner(self):
        """Test ContentAnyOfInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
