# coding: utf-8

"""
    gantry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.reasoning_message_chunk_event import ReasoningMessageChunkEvent

class TestReasoningMessageChunkEvent(unittest.TestCase):
    """ReasoningMessageChunkEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReasoningMessageChunkEvent:
        """Test ReasoningMessageChunkEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReasoningMessageChunkEvent`
        """
        model = ReasoningMessageChunkEvent()
        if include_optional:
            return ReasoningMessageChunkEvent(
                type = 'REASONING_MESSAGE_CHUNK',
                timestamp = 56,
                raw_event = None,
                message_id = '',
                delta = ''
            )
        else:
            return ReasoningMessageChunkEvent(
        )
        """

    def testReasoningMessageChunkEvent(self):
        """Test ReasoningMessageChunkEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
