# coding: utf-8

"""
    gantry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.run_agent_input import RunAgentInput

class TestRunAgentInput(unittest.TestCase):
    """RunAgentInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RunAgentInput:
        """Test RunAgentInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RunAgentInput`
        """
        model = RunAgentInput()
        if include_optional:
            return RunAgentInput(
                thread_id = '',
                run_id = '',
                parent_run_id = '',
                state = None,
                messages = [
                    null
                    ],
                tools = [
                    { }
                    ],
                context = [
                    { }
                    ],
                forwarded_props = None
            )
        else:
            return RunAgentInput(
                thread_id = '',
                run_id = '',
                state = None,
                messages = [
                    null
                    ],
                tools = [
                    { }
                    ],
                context = [
                    { }
                    ],
                forwarded_props = None,
        )
        """

    def testRunAgentInput(self):
        """Test RunAgentInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
