# coding: utf-8

"""
    gantry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.embedding_task_response import EmbeddingTaskResponse

class TestEmbeddingTaskResponse(unittest.TestCase):
    """EmbeddingTaskResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmbeddingTaskResponse:
        """Test EmbeddingTaskResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmbeddingTaskResponse`
        """
        model = EmbeddingTaskResponse()
        if include_optional:
            return EmbeddingTaskResponse(
                task_id = '',
                file_uid = '',
                text = None,
                metadata = { },
                type = 'file',
                project_uuid = '',
                chunk_splitter = 'simple',
                chunk_splitter_options = None,
                chunk_size = 56,
                chunk_overlap = 56,
                failed_reason = '',
                status = 'pending'
            )
        else:
            return EmbeddingTaskResponse(
                task_id = '',
                file_uid = '',
                text = None,
                metadata = { },
                type = 'file',
                project_uuid = '',
                chunk_splitter = 'simple',
                chunk_size = 56,
                chunk_overlap = 56,
                status = 'pending',
        )
        """

    def testEmbeddingTaskResponse(self):
        """Test EmbeddingTaskResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
