# coding: utf-8

"""
    gantry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.activity_delta_event import ActivityDeltaEvent
from openapi_client.models.activity_snapshot_event import ActivitySnapshotEvent
from openapi_client.models.custom_event import CustomEvent
from openapi_client.models.messages_snapshot_event import MessagesSnapshotEvent
from openapi_client.models.raw_event import RawEvent
from openapi_client.models.reasoning_encrypted_value_event import ReasoningEncryptedValueEvent
from openapi_client.models.reasoning_end_event import ReasoningEndEvent
from openapi_client.models.reasoning_message_chunk_event import ReasoningMessageChunkEvent
from openapi_client.models.reasoning_message_content_event import ReasoningMessageContentEvent
from openapi_client.models.reasoning_message_end_event import ReasoningMessageEndEvent
from openapi_client.models.reasoning_message_start_event import ReasoningMessageStartEvent
from openapi_client.models.reasoning_start_event import ReasoningStartEvent
from openapi_client.models.run_error_event import RunErrorEvent
from openapi_client.models.run_finished_event import RunFinishedEvent
from openapi_client.models.run_started_event import RunStartedEvent
from openapi_client.models.state_delta_event import StateDeltaEvent
from openapi_client.models.state_snapshot_event import StateSnapshotEvent
from openapi_client.models.step_finished_event import StepFinishedEvent
from openapi_client.models.step_started_event import StepStartedEvent
from openapi_client.models.text_message_chunk_event import TextMessageChunkEvent
from openapi_client.models.text_message_content_event import TextMessageContentEvent
from openapi_client.models.text_message_end_event import TextMessageEndEvent
from openapi_client.models.text_message_start_event import TextMessageStartEvent
from openapi_client.models.thinking_end_event import ThinkingEndEvent
from openapi_client.models.thinking_start_event import ThinkingStartEvent
from openapi_client.models.thinking_text_message_content_event import ThinkingTextMessageContentEvent
from openapi_client.models.thinking_text_message_end_event import ThinkingTextMessageEndEvent
from openapi_client.models.thinking_text_message_start_event import ThinkingTextMessageStartEvent
from openapi_client.models.tool_call_args_event import ToolCallArgsEvent
from openapi_client.models.tool_call_chunk_event import ToolCallChunkEvent
from openapi_client.models.tool_call_end_event import ToolCallEndEvent
from openapi_client.models.tool_call_result_event import ToolCallResultEvent
from openapi_client.models.tool_call_start_event import ToolCallStartEvent
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

RESPONSEAGUIGATEWAYAIGATEWAYAGUIMODELPOST_ONE_OF_SCHEMAS = ["ActivityDeltaEvent", "ActivitySnapshotEvent", "CustomEvent", "MessagesSnapshotEvent", "RawEvent", "ReasoningEncryptedValueEvent", "ReasoningEndEvent", "ReasoningMessageChunkEvent", "ReasoningMessageContentEvent", "ReasoningMessageEndEvent", "ReasoningMessageStartEvent", "ReasoningStartEvent", "RunErrorEvent", "RunFinishedEvent", "RunStartedEvent", "StateDeltaEvent", "StateSnapshotEvent", "StepFinishedEvent", "StepStartedEvent", "TextMessageChunkEvent", "TextMessageContentEvent", "TextMessageEndEvent", "TextMessageStartEvent", "ThinkingEndEvent", "ThinkingStartEvent", "ThinkingTextMessageContentEvent", "ThinkingTextMessageEndEvent", "ThinkingTextMessageStartEvent", "ToolCallArgsEvent", "ToolCallChunkEvent", "ToolCallEndEvent", "ToolCallResultEvent", "ToolCallStartEvent"]

class ResponseAgUiGatewayAiGatewayAgUiModelPost(BaseModel):
    """
    ResponseAgUiGatewayAiGatewayAgUiModelPost
    """
    # data type: TextMessageStartEvent
    oneof_schema_1_validator: Optional[TextMessageStartEvent] = None
    # data type: TextMessageContentEvent
    oneof_schema_2_validator: Optional[TextMessageContentEvent] = None
    # data type: TextMessageEndEvent
    oneof_schema_3_validator: Optional[TextMessageEndEvent] = None
    # data type: TextMessageChunkEvent
    oneof_schema_4_validator: Optional[TextMessageChunkEvent] = None
    # data type: ThinkingTextMessageStartEvent
    oneof_schema_5_validator: Optional[ThinkingTextMessageStartEvent] = None
    # data type: ThinkingTextMessageContentEvent
    oneof_schema_6_validator: Optional[ThinkingTextMessageContentEvent] = None
    # data type: ThinkingTextMessageEndEvent
    oneof_schema_7_validator: Optional[ThinkingTextMessageEndEvent] = None
    # data type: ToolCallStartEvent
    oneof_schema_8_validator: Optional[ToolCallStartEvent] = None
    # data type: ToolCallArgsEvent
    oneof_schema_9_validator: Optional[ToolCallArgsEvent] = None
    # data type: ToolCallEndEvent
    oneof_schema_10_validator: Optional[ToolCallEndEvent] = None
    # data type: ToolCallChunkEvent
    oneof_schema_11_validator: Optional[ToolCallChunkEvent] = None
    # data type: ToolCallResultEvent
    oneof_schema_12_validator: Optional[ToolCallResultEvent] = None
    # data type: ThinkingStartEvent
    oneof_schema_13_validator: Optional[ThinkingStartEvent] = None
    # data type: ThinkingEndEvent
    oneof_schema_14_validator: Optional[ThinkingEndEvent] = None
    # data type: StateSnapshotEvent
    oneof_schema_15_validator: Optional[StateSnapshotEvent] = None
    # data type: StateDeltaEvent
    oneof_schema_16_validator: Optional[StateDeltaEvent] = None
    # data type: MessagesSnapshotEvent
    oneof_schema_17_validator: Optional[MessagesSnapshotEvent] = None
    # data type: ActivitySnapshotEvent
    oneof_schema_18_validator: Optional[ActivitySnapshotEvent] = None
    # data type: ActivityDeltaEvent
    oneof_schema_19_validator: Optional[ActivityDeltaEvent] = None
    # data type: RawEvent
    oneof_schema_20_validator: Optional[RawEvent] = None
    # data type: CustomEvent
    oneof_schema_21_validator: Optional[CustomEvent] = None
    # data type: RunStartedEvent
    oneof_schema_22_validator: Optional[RunStartedEvent] = None
    # data type: RunFinishedEvent
    oneof_schema_23_validator: Optional[RunFinishedEvent] = None
    # data type: RunErrorEvent
    oneof_schema_24_validator: Optional[RunErrorEvent] = None
    # data type: StepStartedEvent
    oneof_schema_25_validator: Optional[StepStartedEvent] = None
    # data type: StepFinishedEvent
    oneof_schema_26_validator: Optional[StepFinishedEvent] = None
    # data type: ReasoningStartEvent
    oneof_schema_27_validator: Optional[ReasoningStartEvent] = None
    # data type: ReasoningMessageStartEvent
    oneof_schema_28_validator: Optional[ReasoningMessageStartEvent] = None
    # data type: ReasoningMessageContentEvent
    oneof_schema_29_validator: Optional[ReasoningMessageContentEvent] = None
    # data type: ReasoningMessageEndEvent
    oneof_schema_30_validator: Optional[ReasoningMessageEndEvent] = None
    # data type: ReasoningMessageChunkEvent
    oneof_schema_31_validator: Optional[ReasoningMessageChunkEvent] = None
    # data type: ReasoningEndEvent
    oneof_schema_32_validator: Optional[ReasoningEndEvent] = None
    # data type: ReasoningEncryptedValueEvent
    oneof_schema_33_validator: Optional[ReasoningEncryptedValueEvent] = None
    actual_instance: Optional[Union[ActivityDeltaEvent, ActivitySnapshotEvent, CustomEvent, MessagesSnapshotEvent, RawEvent, ReasoningEncryptedValueEvent, ReasoningEndEvent, ReasoningMessageChunkEvent, ReasoningMessageContentEvent, ReasoningMessageEndEvent, ReasoningMessageStartEvent, ReasoningStartEvent, RunErrorEvent, RunFinishedEvent, RunStartedEvent, StateDeltaEvent, StateSnapshotEvent, StepFinishedEvent, StepStartedEvent, TextMessageChunkEvent, TextMessageContentEvent, TextMessageEndEvent, TextMessageStartEvent, ThinkingEndEvent, ThinkingStartEvent, ThinkingTextMessageContentEvent, ThinkingTextMessageEndEvent, ThinkingTextMessageStartEvent, ToolCallArgsEvent, ToolCallChunkEvent, ToolCallEndEvent, ToolCallResultEvent, ToolCallStartEvent]] = None
    one_of_schemas: Set[str] = { "ActivityDeltaEvent", "ActivitySnapshotEvent", "CustomEvent", "MessagesSnapshotEvent", "RawEvent", "ReasoningEncryptedValueEvent", "ReasoningEndEvent", "ReasoningMessageChunkEvent", "ReasoningMessageContentEvent", "ReasoningMessageEndEvent", "ReasoningMessageStartEvent", "ReasoningStartEvent", "RunErrorEvent", "RunFinishedEvent", "RunStartedEvent", "StateDeltaEvent", "StateSnapshotEvent", "StepFinishedEvent", "StepStartedEvent", "TextMessageChunkEvent", "TextMessageContentEvent", "TextMessageEndEvent", "TextMessageStartEvent", "ThinkingEndEvent", "ThinkingStartEvent", "ThinkingTextMessageContentEvent", "ThinkingTextMessageEndEvent", "ThinkingTextMessageStartEvent", "ToolCallArgsEvent", "ToolCallChunkEvent", "ToolCallEndEvent", "ToolCallResultEvent", "ToolCallStartEvent" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ResponseAgUiGatewayAiGatewayAgUiModelPost.model_construct()
        error_messages = []
        match = 0
        # validate data type: TextMessageStartEvent
        if not isinstance(v, TextMessageStartEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TextMessageStartEvent`")
        else:
            match += 1
        # validate data type: TextMessageContentEvent
        if not isinstance(v, TextMessageContentEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TextMessageContentEvent`")
        else:
            match += 1
        # validate data type: TextMessageEndEvent
        if not isinstance(v, TextMessageEndEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TextMessageEndEvent`")
        else:
            match += 1
        # validate data type: TextMessageChunkEvent
        if not isinstance(v, TextMessageChunkEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TextMessageChunkEvent`")
        else:
            match += 1
        # validate data type: ThinkingTextMessageStartEvent
        if not isinstance(v, ThinkingTextMessageStartEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ThinkingTextMessageStartEvent`")
        else:
            match += 1
        # validate data type: ThinkingTextMessageContentEvent
        if not isinstance(v, ThinkingTextMessageContentEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ThinkingTextMessageContentEvent`")
        else:
            match += 1
        # validate data type: ThinkingTextMessageEndEvent
        if not isinstance(v, ThinkingTextMessageEndEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ThinkingTextMessageEndEvent`")
        else:
            match += 1
        # validate data type: ToolCallStartEvent
        if not isinstance(v, ToolCallStartEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ToolCallStartEvent`")
        else:
            match += 1
        # validate data type: ToolCallArgsEvent
        if not isinstance(v, ToolCallArgsEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ToolCallArgsEvent`")
        else:
            match += 1
        # validate data type: ToolCallEndEvent
        if not isinstance(v, ToolCallEndEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ToolCallEndEvent`")
        else:
            match += 1
        # validate data type: ToolCallChunkEvent
        if not isinstance(v, ToolCallChunkEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ToolCallChunkEvent`")
        else:
            match += 1
        # validate data type: ToolCallResultEvent
        if not isinstance(v, ToolCallResultEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ToolCallResultEvent`")
        else:
            match += 1
        # validate data type: ThinkingStartEvent
        if not isinstance(v, ThinkingStartEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ThinkingStartEvent`")
        else:
            match += 1
        # validate data type: ThinkingEndEvent
        if not isinstance(v, ThinkingEndEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ThinkingEndEvent`")
        else:
            match += 1
        # validate data type: StateSnapshotEvent
        if not isinstance(v, StateSnapshotEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `StateSnapshotEvent`")
        else:
            match += 1
        # validate data type: StateDeltaEvent
        if not isinstance(v, StateDeltaEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `StateDeltaEvent`")
        else:
            match += 1
        # validate data type: MessagesSnapshotEvent
        if not isinstance(v, MessagesSnapshotEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MessagesSnapshotEvent`")
        else:
            match += 1
        # validate data type: ActivitySnapshotEvent
        if not isinstance(v, ActivitySnapshotEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ActivitySnapshotEvent`")
        else:
            match += 1
        # validate data type: ActivityDeltaEvent
        if not isinstance(v, ActivityDeltaEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ActivityDeltaEvent`")
        else:
            match += 1
        # validate data type: RawEvent
        if not isinstance(v, RawEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RawEvent`")
        else:
            match += 1
        # validate data type: CustomEvent
        if not isinstance(v, CustomEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CustomEvent`")
        else:
            match += 1
        # validate data type: RunStartedEvent
        if not isinstance(v, RunStartedEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RunStartedEvent`")
        else:
            match += 1
        # validate data type: RunFinishedEvent
        if not isinstance(v, RunFinishedEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RunFinishedEvent`")
        else:
            match += 1
        # validate data type: RunErrorEvent
        if not isinstance(v, RunErrorEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RunErrorEvent`")
        else:
            match += 1
        # validate data type: StepStartedEvent
        if not isinstance(v, StepStartedEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `StepStartedEvent`")
        else:
            match += 1
        # validate data type: StepFinishedEvent
        if not isinstance(v, StepFinishedEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `StepFinishedEvent`")
        else:
            match += 1
        # validate data type: ReasoningStartEvent
        if not isinstance(v, ReasoningStartEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ReasoningStartEvent`")
        else:
            match += 1
        # validate data type: ReasoningMessageStartEvent
        if not isinstance(v, ReasoningMessageStartEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ReasoningMessageStartEvent`")
        else:
            match += 1
        # validate data type: ReasoningMessageContentEvent
        if not isinstance(v, ReasoningMessageContentEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ReasoningMessageContentEvent`")
        else:
            match += 1
        # validate data type: ReasoningMessageEndEvent
        if not isinstance(v, ReasoningMessageEndEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ReasoningMessageEndEvent`")
        else:
            match += 1
        # validate data type: ReasoningMessageChunkEvent
        if not isinstance(v, ReasoningMessageChunkEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ReasoningMessageChunkEvent`")
        else:
            match += 1
        # validate data type: ReasoningEndEvent
        if not isinstance(v, ReasoningEndEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ReasoningEndEvent`")
        else:
            match += 1
        # validate data type: ReasoningEncryptedValueEvent
        if not isinstance(v, ReasoningEncryptedValueEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ReasoningEncryptedValueEvent`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ResponseAgUiGatewayAiGatewayAgUiModelPost with oneOf schemas: ActivityDeltaEvent, ActivitySnapshotEvent, CustomEvent, MessagesSnapshotEvent, RawEvent, ReasoningEncryptedValueEvent, ReasoningEndEvent, ReasoningMessageChunkEvent, ReasoningMessageContentEvent, ReasoningMessageEndEvent, ReasoningMessageStartEvent, ReasoningStartEvent, RunErrorEvent, RunFinishedEvent, RunStartedEvent, StateDeltaEvent, StateSnapshotEvent, StepFinishedEvent, StepStartedEvent, TextMessageChunkEvent, TextMessageContentEvent, TextMessageEndEvent, TextMessageStartEvent, ThinkingEndEvent, ThinkingStartEvent, ThinkingTextMessageContentEvent, ThinkingTextMessageEndEvent, ThinkingTextMessageStartEvent, ToolCallArgsEvent, ToolCallChunkEvent, ToolCallEndEvent, ToolCallResultEvent, ToolCallStartEvent. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ResponseAgUiGatewayAiGatewayAgUiModelPost with oneOf schemas: ActivityDeltaEvent, ActivitySnapshotEvent, CustomEvent, MessagesSnapshotEvent, RawEvent, ReasoningEncryptedValueEvent, ReasoningEndEvent, ReasoningMessageChunkEvent, ReasoningMessageContentEvent, ReasoningMessageEndEvent, ReasoningMessageStartEvent, ReasoningStartEvent, RunErrorEvent, RunFinishedEvent, RunStartedEvent, StateDeltaEvent, StateSnapshotEvent, StepFinishedEvent, StepStartedEvent, TextMessageChunkEvent, TextMessageContentEvent, TextMessageEndEvent, TextMessageStartEvent, ThinkingEndEvent, ThinkingStartEvent, ThinkingTextMessageContentEvent, ThinkingTextMessageEndEvent, ThinkingTextMessageStartEvent, ToolCallArgsEvent, ToolCallChunkEvent, ToolCallEndEvent, ToolCallResultEvent, ToolCallStartEvent. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into TextMessageStartEvent
        try:
            instance.actual_instance = TextMessageStartEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into TextMessageContentEvent
        try:
            instance.actual_instance = TextMessageContentEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into TextMessageEndEvent
        try:
            instance.actual_instance = TextMessageEndEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into TextMessageChunkEvent
        try:
            instance.actual_instance = TextMessageChunkEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ThinkingTextMessageStartEvent
        try:
            instance.actual_instance = ThinkingTextMessageStartEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ThinkingTextMessageContentEvent
        try:
            instance.actual_instance = ThinkingTextMessageContentEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ThinkingTextMessageEndEvent
        try:
            instance.actual_instance = ThinkingTextMessageEndEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ToolCallStartEvent
        try:
            instance.actual_instance = ToolCallStartEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ToolCallArgsEvent
        try:
            instance.actual_instance = ToolCallArgsEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ToolCallEndEvent
        try:
            instance.actual_instance = ToolCallEndEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ToolCallChunkEvent
        try:
            instance.actual_instance = ToolCallChunkEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ToolCallResultEvent
        try:
            instance.actual_instance = ToolCallResultEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ThinkingStartEvent
        try:
            instance.actual_instance = ThinkingStartEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ThinkingEndEvent
        try:
            instance.actual_instance = ThinkingEndEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into StateSnapshotEvent
        try:
            instance.actual_instance = StateSnapshotEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into StateDeltaEvent
        try:
            instance.actual_instance = StateDeltaEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into MessagesSnapshotEvent
        try:
            instance.actual_instance = MessagesSnapshotEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ActivitySnapshotEvent
        try:
            instance.actual_instance = ActivitySnapshotEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ActivityDeltaEvent
        try:
            instance.actual_instance = ActivityDeltaEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RawEvent
        try:
            instance.actual_instance = RawEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CustomEvent
        try:
            instance.actual_instance = CustomEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RunStartedEvent
        try:
            instance.actual_instance = RunStartedEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RunFinishedEvent
        try:
            instance.actual_instance = RunFinishedEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RunErrorEvent
        try:
            instance.actual_instance = RunErrorEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into StepStartedEvent
        try:
            instance.actual_instance = StepStartedEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into StepFinishedEvent
        try:
            instance.actual_instance = StepFinishedEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ReasoningStartEvent
        try:
            instance.actual_instance = ReasoningStartEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ReasoningMessageStartEvent
        try:
            instance.actual_instance = ReasoningMessageStartEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ReasoningMessageContentEvent
        try:
            instance.actual_instance = ReasoningMessageContentEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ReasoningMessageEndEvent
        try:
            instance.actual_instance = ReasoningMessageEndEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ReasoningMessageChunkEvent
        try:
            instance.actual_instance = ReasoningMessageChunkEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ReasoningEndEvent
        try:
            instance.actual_instance = ReasoningEndEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ReasoningEncryptedValueEvent
        try:
            instance.actual_instance = ReasoningEncryptedValueEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ResponseAgUiGatewayAiGatewayAgUiModelPost with oneOf schemas: ActivityDeltaEvent, ActivitySnapshotEvent, CustomEvent, MessagesSnapshotEvent, RawEvent, ReasoningEncryptedValueEvent, ReasoningEndEvent, ReasoningMessageChunkEvent, ReasoningMessageContentEvent, ReasoningMessageEndEvent, ReasoningMessageStartEvent, ReasoningStartEvent, RunErrorEvent, RunFinishedEvent, RunStartedEvent, StateDeltaEvent, StateSnapshotEvent, StepFinishedEvent, StepStartedEvent, TextMessageChunkEvent, TextMessageContentEvent, TextMessageEndEvent, TextMessageStartEvent, ThinkingEndEvent, ThinkingStartEvent, ThinkingTextMessageContentEvent, ThinkingTextMessageEndEvent, ThinkingTextMessageStartEvent, ToolCallArgsEvent, ToolCallChunkEvent, ToolCallEndEvent, ToolCallResultEvent, ToolCallStartEvent. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ResponseAgUiGatewayAiGatewayAgUiModelPost with oneOf schemas: ActivityDeltaEvent, ActivitySnapshotEvent, CustomEvent, MessagesSnapshotEvent, RawEvent, ReasoningEncryptedValueEvent, ReasoningEndEvent, ReasoningMessageChunkEvent, ReasoningMessageContentEvent, ReasoningMessageEndEvent, ReasoningMessageStartEvent, ReasoningStartEvent, RunErrorEvent, RunFinishedEvent, RunStartedEvent, StateDeltaEvent, StateSnapshotEvent, StepFinishedEvent, StepStartedEvent, TextMessageChunkEvent, TextMessageContentEvent, TextMessageEndEvent, TextMessageStartEvent, ThinkingEndEvent, ThinkingStartEvent, ThinkingTextMessageContentEvent, ThinkingTextMessageEndEvent, ThinkingTextMessageStartEvent, ToolCallArgsEvent, ToolCallChunkEvent, ToolCallEndEvent, ToolCallResultEvent, ToolCallStartEvent. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ActivityDeltaEvent, ActivitySnapshotEvent, CustomEvent, MessagesSnapshotEvent, RawEvent, ReasoningEncryptedValueEvent, ReasoningEndEvent, ReasoningMessageChunkEvent, ReasoningMessageContentEvent, ReasoningMessageEndEvent, ReasoningMessageStartEvent, ReasoningStartEvent, RunErrorEvent, RunFinishedEvent, RunStartedEvent, StateDeltaEvent, StateSnapshotEvent, StepFinishedEvent, StepStartedEvent, TextMessageChunkEvent, TextMessageContentEvent, TextMessageEndEvent, TextMessageStartEvent, ThinkingEndEvent, ThinkingStartEvent, ThinkingTextMessageContentEvent, ThinkingTextMessageEndEvent, ThinkingTextMessageStartEvent, ToolCallArgsEvent, ToolCallChunkEvent, ToolCallEndEvent, ToolCallResultEvent, ToolCallStartEvent]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


