# coding: utf-8

"""
    gantry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.text_message_start_event import TextMessageStartEvent

class TestTextMessageStartEvent(unittest.TestCase):
    """TextMessageStartEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TextMessageStartEvent:
        """Test TextMessageStartEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TextMessageStartEvent`
        """
        model = TextMessageStartEvent()
        if include_optional:
            return TextMessageStartEvent(
                type = 'TEXT_MESSAGE_START',
                timestamp = 56,
                raw_event = None,
                message_id = '',
                role = 'assistant',
                name = ''
            )
        else:
            return TextMessageStartEvent(
                message_id = '',
        )
        """

    def testTextMessageStartEvent(self):
        """Test TextMessageStartEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
