/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ToolCall } from './ToolCall';
import {
    ToolCallFromJSON,
    ToolCallFromJSONTyped,
    ToolCallToJSON,
    ToolCallToJSONTyped,
} from './ToolCall';

/**
 * An assistant message.
 * @export
 * @interface AssistantMessage
 */
export interface AssistantMessage {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof AssistantMessage
     */
    id: string;
    /**
     * 
     * @type {AssistantMessageRoleEnum}
     * @memberof AssistantMessage
     */
    role?: AssistantMessageRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof AssistantMessage
     */
    content?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AssistantMessage
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AssistantMessage
     */
    encryptedValue?: string | null;
    /**
     * 
     * @type {Array<ToolCall>}
     * @memberof AssistantMessage
     */
    toolCalls?: Array<ToolCall> | null;
}


/**
 * @export
 */
export const AssistantMessageRoleEnum = {
    Assistant: 'assistant'
} as const;
export type AssistantMessageRoleEnum = typeof AssistantMessageRoleEnum[keyof typeof AssistantMessageRoleEnum];


/**
 * Check if a given object implements the AssistantMessage interface.
 */
export function instanceOfAssistantMessage(value: object): value is AssistantMessage {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function AssistantMessageFromJSON(json: any): AssistantMessage {
    return AssistantMessageFromJSONTyped(json, false);
}

export function AssistantMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssistantMessage {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'role': json['role'] == null ? undefined : json['role'],
        'content': json['content'] == null ? undefined : json['content'],
        'name': json['name'] == null ? undefined : json['name'],
        'encryptedValue': json['encryptedValue'] == null ? undefined : json['encryptedValue'],
        'toolCalls': json['toolCalls'] == null ? undefined : ((json['toolCalls'] as Array<any>).map(ToolCallFromJSON)),
    };
}

export function AssistantMessageToJSON(json: any): AssistantMessage {
    return AssistantMessageToJSONTyped(json, false);
}

export function AssistantMessageToJSONTyped(value?: AssistantMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'role': value['role'],
        'content': value['content'],
        'name': value['name'],
        'encryptedValue': value['encryptedValue'],
        'toolCalls': value['toolCalls'] == null ? undefined : ((value['toolCalls'] as Array<any>).map(ToolCallToJSON)),
    };
}

