/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A deprecated binary payload reference in a multimodal user message.
 * @export
 * @interface BinaryInputContent
 */
export interface BinaryInputContent {
    [key: string]: any | any;
    /**
     * 
     * @type {BinaryInputContentTypeEnum}
     * @memberof BinaryInputContent
     */
    type?: BinaryInputContentTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof BinaryInputContent
     */
    mimeType: string;
    /**
     * 
     * @type {string}
     * @memberof BinaryInputContent
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BinaryInputContent
     */
    url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BinaryInputContent
     */
    data?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BinaryInputContent
     */
    filename?: string | null;
}


/**
 * @export
 */
export const BinaryInputContentTypeEnum = {
    Binary: 'binary'
} as const;
export type BinaryInputContentTypeEnum = typeof BinaryInputContentTypeEnum[keyof typeof BinaryInputContentTypeEnum];


/**
 * Check if a given object implements the BinaryInputContent interface.
 */
export function instanceOfBinaryInputContent(value: object): value is BinaryInputContent {
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    return true;
}

export function BinaryInputContentFromJSON(json: any): BinaryInputContent {
    return BinaryInputContentFromJSONTyped(json, false);
}

export function BinaryInputContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): BinaryInputContent {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'] == null ? undefined : json['type'],
        'mimeType': json['mimeType'],
        'id': json['id'] == null ? undefined : json['id'],
        'url': json['url'] == null ? undefined : json['url'],
        'data': json['data'] == null ? undefined : json['data'],
        'filename': json['filename'] == null ? undefined : json['filename'],
    };
}

export function BinaryInputContentToJSON(json: any): BinaryInputContent {
    return BinaryInputContentToJSONTyped(json, false);
}

export function BinaryInputContentToJSONTyped(value?: BinaryInputContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'mimeType': value['mimeType'],
        'id': value['id'],
        'url': value['url'],
        'data': value['data'],
        'filename': value['filename'],
    };
}

