/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A developer message.
 * @export
 * @interface DeveloperMessage
 */
export interface DeveloperMessage {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof DeveloperMessage
     */
    id: string;
    /**
     * 
     * @type {DeveloperMessageRoleEnum}
     * @memberof DeveloperMessage
     */
    role?: DeveloperMessageRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof DeveloperMessage
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof DeveloperMessage
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeveloperMessage
     */
    encryptedValue?: string | null;
}


/**
 * @export
 */
export const DeveloperMessageRoleEnum = {
    Developer: 'developer'
} as const;
export type DeveloperMessageRoleEnum = typeof DeveloperMessageRoleEnum[keyof typeof DeveloperMessageRoleEnum];


/**
 * Check if a given object implements the DeveloperMessage interface.
 */
export function instanceOfDeveloperMessage(value: object): value is DeveloperMessage {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function DeveloperMessageFromJSON(json: any): DeveloperMessage {
    return DeveloperMessageFromJSONTyped(json, false);
}

export function DeveloperMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeveloperMessage {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'role': json['role'] == null ? undefined : json['role'],
        'content': json['content'],
        'name': json['name'] == null ? undefined : json['name'],
        'encryptedValue': json['encryptedValue'] == null ? undefined : json['encryptedValue'],
    };
}

export function DeveloperMessageToJSON(json: any): DeveloperMessage {
    return DeveloperMessageToJSONTyped(json, false);
}

export function DeveloperMessageToJSONTyped(value?: DeveloperMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'role': value['role'],
        'content': value['content'],
        'name': value['name'],
        'encryptedValue': value['encryptedValue'],
    };
}

