/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateFileMetadataRequestExtraMetadataValue
 */
export interface UpdateFileMetadataRequestExtraMetadataValue {
}

/**
 * Check if a given object implements the UpdateFileMetadataRequestExtraMetadataValue interface.
 */
export function instanceOfUpdateFileMetadataRequestExtraMetadataValue(value: object): value is UpdateFileMetadataRequestExtraMetadataValue {
    return true;
}

export function UpdateFileMetadataRequestExtraMetadataValueFromJSON(json: any): UpdateFileMetadataRequestExtraMetadataValue {
    return UpdateFileMetadataRequestExtraMetadataValueFromJSONTyped(json, false);
}

export function UpdateFileMetadataRequestExtraMetadataValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateFileMetadataRequestExtraMetadataValue {
    return json;
}

export function UpdateFileMetadataRequestExtraMetadataValueToJSON(json: any): UpdateFileMetadataRequestExtraMetadataValue {
    return UpdateFileMetadataRequestExtraMetadataValueToJSONTyped(json, false);
}

export function UpdateFileMetadataRequestExtraMetadataValueToJSONTyped(value?: UpdateFileMetadataRequestExtraMetadataValue | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

