# coding: utf-8

"""
    gantry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.text_message_end_event import TextMessageEndEvent

class TestTextMessageEndEvent(unittest.TestCase):
    """TextMessageEndEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TextMessageEndEvent:
        """Test TextMessageEndEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TextMessageEndEvent`
        """
        model = TextMessageEndEvent()
        if include_optional:
            return TextMessageEndEvent(
                type = 'TEXT_MESSAGE_END',
                timestamp = 56,
                raw_event = None,
                message_id = ''
            )
        else:
            return TextMessageEndEvent(
                message_id = '',
        )
        """

    def testTextMessageEndEvent(self):
        """Test TextMessageEndEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
