# coding: utf-8

"""
    gantry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.activity_message import ActivityMessage

class TestActivityMessage(unittest.TestCase):
    """ActivityMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActivityMessage:
        """Test ActivityMessage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActivityMessage`
        """
        model = ActivityMessage()
        if include_optional:
            return ActivityMessage(
                id = '',
                role = 'activity',
                activity_type = '',
                content = { }
            )
        else:
            return ActivityMessage(
                id = '',
                activity_type = '',
                content = { },
        )
        """

    def testActivityMessage(self):
        """Test ActivityMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
