/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Event containing a snapshot of an activity message.
 * @export
 * @interface ActivitySnapshotEvent
 */
export interface ActivitySnapshotEvent {
    [key: string]: any | any;
    /**
     * 
     * @type {ActivitySnapshotEventTypeEnum}
     * @memberof ActivitySnapshotEvent
     */
    type?: ActivitySnapshotEventTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ActivitySnapshotEvent
     */
    timestamp?: number | null;
    /**
     * 
     * @type {}
     * @memberof ActivitySnapshotEvent
     */
    rawEvent?:  | null;
    /**
     * 
     * @type {string}
     * @memberof ActivitySnapshotEvent
     */
    messageId: string;
    /**
     * 
     * @type {string}
     * @memberof ActivitySnapshotEvent
     */
    activityType: string;
    /**
     * 
     * @type {any}
     * @memberof ActivitySnapshotEvent
     */
    content: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof ActivitySnapshotEvent
     */
    replace?: boolean;
}


/**
 * @export
 */
export const ActivitySnapshotEventTypeEnum = {
    ActivitySnapshot: 'ACTIVITY_SNAPSHOT'
} as const;
export type ActivitySnapshotEventTypeEnum = typeof ActivitySnapshotEventTypeEnum[keyof typeof ActivitySnapshotEventTypeEnum];


/**
 * Check if a given object implements the ActivitySnapshotEvent interface.
 */
export function instanceOfActivitySnapshotEvent(value: object): value is ActivitySnapshotEvent {
    if (!('messageId' in value) || value['messageId'] === undefined) return false;
    if (!('activityType' in value) || value['activityType'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function ActivitySnapshotEventFromJSON(json: any): ActivitySnapshotEvent {
    return ActivitySnapshotEventFromJSONTyped(json, false);
}

export function ActivitySnapshotEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivitySnapshotEvent {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'] == null ? undefined : json['type'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'rawEvent': json['rawEvent'] == null ? undefined : FromJSON(json['rawEvent']),
        'messageId': json['messageId'],
        'activityType': json['activityType'],
        'content': json['content'],
        'replace': json['replace'] == null ? undefined : json['replace'],
    };
}

export function ActivitySnapshotEventToJSON(json: any): ActivitySnapshotEvent {
    return ActivitySnapshotEventToJSONTyped(json, false);
}

export function ActivitySnapshotEventToJSONTyped(value?: ActivitySnapshotEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'timestamp': value['timestamp'],
        'rawEvent': ToJSON(value['rawEvent']),
        'messageId': value['messageId'],
        'activityType': value['activityType'],
        'content': value['content'],
        'replace': value['replace'],
    };
}

