/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Event containing a piece of text message content.
 * @export
 * @interface TextMessageContentEvent
 */
export interface TextMessageContentEvent {
    [key: string]: any | any;
    /**
     * 
     * @type {TextMessageContentEventTypeEnum}
     * @memberof TextMessageContentEvent
     */
    type?: TextMessageContentEventTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof TextMessageContentEvent
     */
    timestamp?: number | null;
    /**
     * 
     * @type {}
     * @memberof TextMessageContentEvent
     */
    rawEvent?:  | null;
    /**
     * 
     * @type {string}
     * @memberof TextMessageContentEvent
     */
    messageId: string;
    /**
     * 
     * @type {string}
     * @memberof TextMessageContentEvent
     */
    delta: string;
}


/**
 * @export
 */
export const TextMessageContentEventTypeEnum = {
    TextMessageContent: 'TEXT_MESSAGE_CONTENT'
} as const;
export type TextMessageContentEventTypeEnum = typeof TextMessageContentEventTypeEnum[keyof typeof TextMessageContentEventTypeEnum];


/**
 * Check if a given object implements the TextMessageContentEvent interface.
 */
export function instanceOfTextMessageContentEvent(value: object): value is TextMessageContentEvent {
    if (!('messageId' in value) || value['messageId'] === undefined) return false;
    if (!('delta' in value) || value['delta'] === undefined) return false;
    return true;
}

export function TextMessageContentEventFromJSON(json: any): TextMessageContentEvent {
    return TextMessageContentEventFromJSONTyped(json, false);
}

export function TextMessageContentEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextMessageContentEvent {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'] == null ? undefined : json['type'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'rawEvent': json['rawEvent'] == null ? undefined : FromJSON(json['rawEvent']),
        'messageId': json['messageId'],
        'delta': json['delta'],
    };
}

export function TextMessageContentEventToJSON(json: any): TextMessageContentEvent {
    return TextMessageContentEventToJSONTyped(json, false);
}

export function TextMessageContentEventToJSONTyped(value?: TextMessageContentEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'timestamp': value['timestamp'],
        'rawEvent': ToJSON(value['rawEvent']),
        'messageId': value['messageId'],
        'delta': value['delta'],
    };
}

