/*
gantry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ReasoningMessageChunkEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReasoningMessageChunkEvent{}

// ReasoningMessageChunkEvent Event containing a chunk of reasoning message content.
type ReasoningMessageChunkEvent struct {
	Type *string `json:"type,omitempty"`
	Timestamp NullableInt32 `json:"timestamp,omitempty"`
	RawEvent NullableAnyOf `json:"rawEvent,omitempty"`
	MessageId NullableString `json:"messageId,omitempty"`
	Delta NullableString `json:"delta,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ReasoningMessageChunkEvent ReasoningMessageChunkEvent

// NewReasoningMessageChunkEvent instantiates a new ReasoningMessageChunkEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReasoningMessageChunkEvent() *ReasoningMessageChunkEvent {
	this := ReasoningMessageChunkEvent{}
	var type_ string = "REASONING_MESSAGE_CHUNK"
	this.Type = &type_
	return &this
}

// NewReasoningMessageChunkEventWithDefaults instantiates a new ReasoningMessageChunkEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReasoningMessageChunkEventWithDefaults() *ReasoningMessageChunkEvent {
	this := ReasoningMessageChunkEvent{}
	var type_ string = "REASONING_MESSAGE_CHUNK"
	this.Type = &type_
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ReasoningMessageChunkEvent) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReasoningMessageChunkEvent) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ReasoningMessageChunkEvent) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ReasoningMessageChunkEvent) SetType(v string) {
	o.Type = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReasoningMessageChunkEvent) GetTimestamp() int32 {
	if o == nil || IsNil(o.Timestamp.Get()) {
		var ret int32
		return ret
	}
	return *o.Timestamp.Get()
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReasoningMessageChunkEvent) GetTimestampOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timestamp.Get(), o.Timestamp.IsSet()
}

// HasTimestamp returns a boolean if a field has been set.
func (o *ReasoningMessageChunkEvent) HasTimestamp() bool {
	if o != nil && o.Timestamp.IsSet() {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given NullableInt32 and assigns it to the Timestamp field.
func (o *ReasoningMessageChunkEvent) SetTimestamp(v int32) {
	o.Timestamp.Set(&v)
}
// SetTimestampNil sets the value for Timestamp to be an explicit nil
func (o *ReasoningMessageChunkEvent) SetTimestampNil() {
	o.Timestamp.Set(nil)
}

// UnsetTimestamp ensures that no value is present for Timestamp, not even an explicit nil
func (o *ReasoningMessageChunkEvent) UnsetTimestamp() {
	o.Timestamp.Unset()
}

// GetRawEvent returns the RawEvent field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReasoningMessageChunkEvent) GetRawEvent() AnyOf {
	if o == nil || IsNil(o.RawEvent.Get()) {
		var ret AnyOf
		return ret
	}
	return *o.RawEvent.Get()
}

// GetRawEventOk returns a tuple with the RawEvent field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReasoningMessageChunkEvent) GetRawEventOk() (*AnyOf, bool) {
	if o == nil {
		return nil, false
	}
	return o.RawEvent.Get(), o.RawEvent.IsSet()
}

// HasRawEvent returns a boolean if a field has been set.
func (o *ReasoningMessageChunkEvent) HasRawEvent() bool {
	if o != nil && o.RawEvent.IsSet() {
		return true
	}

	return false
}

// SetRawEvent gets a reference to the given NullableAnyOf and assigns it to the RawEvent field.
func (o *ReasoningMessageChunkEvent) SetRawEvent(v AnyOf) {
	o.RawEvent.Set(&v)
}
// SetRawEventNil sets the value for RawEvent to be an explicit nil
func (o *ReasoningMessageChunkEvent) SetRawEventNil() {
	o.RawEvent.Set(nil)
}

// UnsetRawEvent ensures that no value is present for RawEvent, not even an explicit nil
func (o *ReasoningMessageChunkEvent) UnsetRawEvent() {
	o.RawEvent.Unset()
}

// GetMessageId returns the MessageId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReasoningMessageChunkEvent) GetMessageId() string {
	if o == nil || IsNil(o.MessageId.Get()) {
		var ret string
		return ret
	}
	return *o.MessageId.Get()
}

// GetMessageIdOk returns a tuple with the MessageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReasoningMessageChunkEvent) GetMessageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MessageId.Get(), o.MessageId.IsSet()
}

// HasMessageId returns a boolean if a field has been set.
func (o *ReasoningMessageChunkEvent) HasMessageId() bool {
	if o != nil && o.MessageId.IsSet() {
		return true
	}

	return false
}

// SetMessageId gets a reference to the given NullableString and assigns it to the MessageId field.
func (o *ReasoningMessageChunkEvent) SetMessageId(v string) {
	o.MessageId.Set(&v)
}
// SetMessageIdNil sets the value for MessageId to be an explicit nil
func (o *ReasoningMessageChunkEvent) SetMessageIdNil() {
	o.MessageId.Set(nil)
}

// UnsetMessageId ensures that no value is present for MessageId, not even an explicit nil
func (o *ReasoningMessageChunkEvent) UnsetMessageId() {
	o.MessageId.Unset()
}

// GetDelta returns the Delta field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReasoningMessageChunkEvent) GetDelta() string {
	if o == nil || IsNil(o.Delta.Get()) {
		var ret string
		return ret
	}
	return *o.Delta.Get()
}

// GetDeltaOk returns a tuple with the Delta field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReasoningMessageChunkEvent) GetDeltaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Delta.Get(), o.Delta.IsSet()
}

// HasDelta returns a boolean if a field has been set.
func (o *ReasoningMessageChunkEvent) HasDelta() bool {
	if o != nil && o.Delta.IsSet() {
		return true
	}

	return false
}

// SetDelta gets a reference to the given NullableString and assigns it to the Delta field.
func (o *ReasoningMessageChunkEvent) SetDelta(v string) {
	o.Delta.Set(&v)
}
// SetDeltaNil sets the value for Delta to be an explicit nil
func (o *ReasoningMessageChunkEvent) SetDeltaNil() {
	o.Delta.Set(nil)
}

// UnsetDelta ensures that no value is present for Delta, not even an explicit nil
func (o *ReasoningMessageChunkEvent) UnsetDelta() {
	o.Delta.Unset()
}

func (o ReasoningMessageChunkEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReasoningMessageChunkEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if o.Timestamp.IsSet() {
		toSerialize["timestamp"] = o.Timestamp.Get()
	}
	if o.RawEvent.IsSet() {
		toSerialize["rawEvent"] = o.RawEvent.Get()
	}
	if o.MessageId.IsSet() {
		toSerialize["messageId"] = o.MessageId.Get()
	}
	if o.Delta.IsSet() {
		toSerialize["delta"] = o.Delta.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReasoningMessageChunkEvent) UnmarshalJSON(data []byte) (err error) {
	varReasoningMessageChunkEvent := _ReasoningMessageChunkEvent{}

	err = json.Unmarshal(data, &varReasoningMessageChunkEvent)

	if err != nil {
		return err
	}

	*o = ReasoningMessageChunkEvent(varReasoningMessageChunkEvent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "timestamp")
		delete(additionalProperties, "rawEvent")
		delete(additionalProperties, "messageId")
		delete(additionalProperties, "delta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReasoningMessageChunkEvent struct {
	value *ReasoningMessageChunkEvent
	isSet bool
}

func (v NullableReasoningMessageChunkEvent) Get() *ReasoningMessageChunkEvent {
	return v.value
}

func (v *NullableReasoningMessageChunkEvent) Set(val *ReasoningMessageChunkEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableReasoningMessageChunkEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableReasoningMessageChunkEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReasoningMessageChunkEvent(val *ReasoningMessageChunkEvent) *NullableReasoningMessageChunkEvent {
	return &NullableReasoningMessageChunkEvent{value: val, isSet: true}
}

func (v NullableReasoningMessageChunkEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReasoningMessageChunkEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


