/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Event containing a piece of reasoning message content.
 * @export
 * @interface ReasoningMessageContentEvent
 */
export interface ReasoningMessageContentEvent {
    [key: string]: any | any;
    /**
     * 
     * @type {ReasoningMessageContentEventTypeEnum}
     * @memberof ReasoningMessageContentEvent
     */
    type?: ReasoningMessageContentEventTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ReasoningMessageContentEvent
     */
    timestamp?: number | null;
    /**
     * 
     * @type {}
     * @memberof ReasoningMessageContentEvent
     */
    rawEvent?:  | null;
    /**
     * 
     * @type {string}
     * @memberof ReasoningMessageContentEvent
     */
    messageId: string;
    /**
     * 
     * @type {string}
     * @memberof ReasoningMessageContentEvent
     */
    delta: string;
}


/**
 * @export
 */
export const ReasoningMessageContentEventTypeEnum = {
    ReasoningMessageContent: 'REASONING_MESSAGE_CONTENT'
} as const;
export type ReasoningMessageContentEventTypeEnum = typeof ReasoningMessageContentEventTypeEnum[keyof typeof ReasoningMessageContentEventTypeEnum];


/**
 * Check if a given object implements the ReasoningMessageContentEvent interface.
 */
export function instanceOfReasoningMessageContentEvent(value: object): value is ReasoningMessageContentEvent {
    if (!('messageId' in value) || value['messageId'] === undefined) return false;
    if (!('delta' in value) || value['delta'] === undefined) return false;
    return true;
}

export function ReasoningMessageContentEventFromJSON(json: any): ReasoningMessageContentEvent {
    return ReasoningMessageContentEventFromJSONTyped(json, false);
}

export function ReasoningMessageContentEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReasoningMessageContentEvent {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'] == null ? undefined : json['type'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'rawEvent': json['rawEvent'] == null ? undefined : FromJSON(json['rawEvent']),
        'messageId': json['messageId'],
        'delta': json['delta'],
    };
}

export function ReasoningMessageContentEventToJSON(json: any): ReasoningMessageContentEvent {
    return ReasoningMessageContentEventToJSONTyped(json, false);
}

export function ReasoningMessageContentEventToJSONTyped(value?: ReasoningMessageContentEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'timestamp': value['timestamp'],
        'rawEvent': ToJSON(value['rawEvent']),
        'messageId': value['messageId'],
        'delta': value['delta'],
    };
}

