/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Event containing a delta of the state.
 * @export
 * @interface StateDeltaEvent
 */
export interface StateDeltaEvent {
    [key: string]: any | any;
    /**
     * 
     * @type {StateDeltaEventTypeEnum}
     * @memberof StateDeltaEvent
     */
    type?: StateDeltaEventTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof StateDeltaEvent
     */
    timestamp?: number | null;
    /**
     * 
     * @type {}
     * @memberof StateDeltaEvent
     */
    rawEvent?:  | null;
    /**
     * 
     * @type {Array<any>}
     * @memberof StateDeltaEvent
     */
    delta: Array<any>;
}


/**
 * @export
 */
export const StateDeltaEventTypeEnum = {
    StateDelta: 'STATE_DELTA'
} as const;
export type StateDeltaEventTypeEnum = typeof StateDeltaEventTypeEnum[keyof typeof StateDeltaEventTypeEnum];


/**
 * Check if a given object implements the StateDeltaEvent interface.
 */
export function instanceOfStateDeltaEvent(value: object): value is StateDeltaEvent {
    if (!('delta' in value) || value['delta'] === undefined) return false;
    return true;
}

export function StateDeltaEventFromJSON(json: any): StateDeltaEvent {
    return StateDeltaEventFromJSONTyped(json, false);
}

export function StateDeltaEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): StateDeltaEvent {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'] == null ? undefined : json['type'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'rawEvent': json['rawEvent'] == null ? undefined : FromJSON(json['rawEvent']),
        'delta': json['delta'],
    };
}

export function StateDeltaEventToJSON(json: any): StateDeltaEvent {
    return StateDeltaEventToJSONTyped(json, false);
}

export function StateDeltaEventToJSONTyped(value?: StateDeltaEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'timestamp': value['timestamp'],
        'rawEvent': ToJSON(value['rawEvent']),
        'delta': value['delta'],
    };
}

