/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Event containing tool call arguments.
 * @export
 * @interface ToolCallArgsEvent
 */
export interface ToolCallArgsEvent {
    [key: string]: any | any;
    /**
     * 
     * @type {ToolCallArgsEventTypeEnum}
     * @memberof ToolCallArgsEvent
     */
    type?: ToolCallArgsEventTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ToolCallArgsEvent
     */
    timestamp?: number | null;
    /**
     * 
     * @type {}
     * @memberof ToolCallArgsEvent
     */
    rawEvent?:  | null;
    /**
     * 
     * @type {string}
     * @memberof ToolCallArgsEvent
     */
    toolCallId: string;
    /**
     * 
     * @type {string}
     * @memberof ToolCallArgsEvent
     */
    delta: string;
}


/**
 * @export
 */
export const ToolCallArgsEventTypeEnum = {
    ToolCallArgs: 'TOOL_CALL_ARGS'
} as const;
export type ToolCallArgsEventTypeEnum = typeof ToolCallArgsEventTypeEnum[keyof typeof ToolCallArgsEventTypeEnum];


/**
 * Check if a given object implements the ToolCallArgsEvent interface.
 */
export function instanceOfToolCallArgsEvent(value: object): value is ToolCallArgsEvent {
    if (!('toolCallId' in value) || value['toolCallId'] === undefined) return false;
    if (!('delta' in value) || value['delta'] === undefined) return false;
    return true;
}

export function ToolCallArgsEventFromJSON(json: any): ToolCallArgsEvent {
    return ToolCallArgsEventFromJSONTyped(json, false);
}

export function ToolCallArgsEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolCallArgsEvent {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'] == null ? undefined : json['type'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'rawEvent': json['rawEvent'] == null ? undefined : FromJSON(json['rawEvent']),
        'toolCallId': json['toolCallId'],
        'delta': json['delta'],
    };
}

export function ToolCallArgsEventToJSON(json: any): ToolCallArgsEvent {
    return ToolCallArgsEventToJSONTyped(json, false);
}

export function ToolCallArgsEventToJSONTyped(value?: ToolCallArgsEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'timestamp': value['timestamp'],
        'rawEvent': ToJSON(value['rawEvent']),
        'toolCallId': value['toolCallId'],
        'delta': value['delta'],
    };
}

