# coding: utf-8

"""
    gantry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.text_input_content import TextInputContent

class TestTextInputContent(unittest.TestCase):
    """TextInputContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TextInputContent:
        """Test TextInputContent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TextInputContent`
        """
        model = TextInputContent()
        if include_optional:
            return TextInputContent(
                type = 'text',
                text = ''
            )
        else:
            return TextInputContent(
                text = '',
        )
        """

    def testTextInputContent(self):
        """Test TextInputContent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
