# coding: utf-8

"""
    gantry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.recursive_character_text_splitter_options import RecursiveCharacterTextSplitterOptions

class TestRecursiveCharacterTextSplitterOptions(unittest.TestCase):
    """RecursiveCharacterTextSplitterOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecursiveCharacterTextSplitterOptions:
        """Test RecursiveCharacterTextSplitterOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecursiveCharacterTextSplitterOptions`
        """
        model = RecursiveCharacterTextSplitterOptions()
        if include_optional:
            return RecursiveCharacterTextSplitterOptions(
                separators = [
                    ''
                    ],
                keep_separator = None,
                is_separator_regex = True,
                chunk_size = 56,
                chunk_overlap = 56
            )
        else:
            return RecursiveCharacterTextSplitterOptions(
        )
        """

    def testRecursiveCharacterTextSplitterOptions(self):
        """Test RecursiveCharacterTextSplitterOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
