/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An activity progress message emitted between chat messages.
 * @export
 * @interface ActivityMessage
 */
export interface ActivityMessage {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof ActivityMessage
     */
    id: string;
    /**
     * 
     * @type {ActivityMessageRoleEnum}
     * @memberof ActivityMessage
     */
    role?: ActivityMessageRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof ActivityMessage
     */
    activityType: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ActivityMessage
     */
    content: { [key: string]: any; };
}


/**
 * @export
 */
export const ActivityMessageRoleEnum = {
    Activity: 'activity'
} as const;
export type ActivityMessageRoleEnum = typeof ActivityMessageRoleEnum[keyof typeof ActivityMessageRoleEnum];


/**
 * Check if a given object implements the ActivityMessage interface.
 */
export function instanceOfActivityMessage(value: object): value is ActivityMessage {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('activityType' in value) || value['activityType'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function ActivityMessageFromJSON(json: any): ActivityMessage {
    return ActivityMessageFromJSONTyped(json, false);
}

export function ActivityMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityMessage {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'role': json['role'] == null ? undefined : json['role'],
        'activityType': json['activityType'],
        'content': json['content'],
    };
}

export function ActivityMessageToJSON(json: any): ActivityMessage {
    return ActivityMessageToJSONTyped(json, false);
}

export function ActivityMessageToJSONTyped(value?: ActivityMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'role': value['role'],
        'activityType': value['activityType'],
        'content': value['content'],
    };
}

