/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessagesInner } from './MessagesInner';
import {
    MessagesInnerFromJSON,
    MessagesInnerFromJSONTyped,
    MessagesInnerToJSON,
    MessagesInnerToJSONTyped,
} from './MessagesInner';

/**
 * Event containing a snapshot of the messages.
 * @export
 * @interface MessagesSnapshotEvent
 */
export interface MessagesSnapshotEvent {
    [key: string]: any | any;
    /**
     * 
     * @type {MessagesSnapshotEventTypeEnum}
     * @memberof MessagesSnapshotEvent
     */
    type?: MessagesSnapshotEventTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof MessagesSnapshotEvent
     */
    timestamp?: number | null;
    /**
     * 
     * @type {}
     * @memberof MessagesSnapshotEvent
     */
    rawEvent?:  | null;
    /**
     * 
     * @type {Array<MessagesInner>}
     * @memberof MessagesSnapshotEvent
     */
    messages: Array<MessagesInner>;
}


/**
 * @export
 */
export const MessagesSnapshotEventTypeEnum = {
    MessagesSnapshot: 'MESSAGES_SNAPSHOT'
} as const;
export type MessagesSnapshotEventTypeEnum = typeof MessagesSnapshotEventTypeEnum[keyof typeof MessagesSnapshotEventTypeEnum];


/**
 * Check if a given object implements the MessagesSnapshotEvent interface.
 */
export function instanceOfMessagesSnapshotEvent(value: object): value is MessagesSnapshotEvent {
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function MessagesSnapshotEventFromJSON(json: any): MessagesSnapshotEvent {
    return MessagesSnapshotEventFromJSONTyped(json, false);
}

export function MessagesSnapshotEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessagesSnapshotEvent {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'] == null ? undefined : json['type'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'rawEvent': json['rawEvent'] == null ? undefined : FromJSON(json['rawEvent']),
        'messages': ((json['messages'] as Array<any>).map(MessagesInnerFromJSON)),
    };
}

export function MessagesSnapshotEventToJSON(json: any): MessagesSnapshotEvent {
    return MessagesSnapshotEventToJSONTyped(json, false);
}

export function MessagesSnapshotEventToJSONTyped(value?: MessagesSnapshotEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'timestamp': value['timestamp'],
        'rawEvent': ToJSON(value['rawEvent']),
        'messages': ((value['messages'] as Array<any>).map(MessagesInnerToJSON)),
    };
}

