/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpacyTextSplitterOptions
 */
export interface SpacyTextSplitterOptions {
    /**
     * 
     * @type {string}
     * @memberof SpacyTextSplitterOptions
     */
    separator?: string;
    /**
     * 
     * @type {string}
     * @memberof SpacyTextSplitterOptions
     */
    pipeline?: string;
    /**
     * 
     * @type {number}
     * @memberof SpacyTextSplitterOptions
     */
    maxLength?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SpacyTextSplitterOptions
     */
    stripWhitespace?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SpacyTextSplitterOptions
     */
    chunkSize?: number;
    /**
     * 
     * @type {number}
     * @memberof SpacyTextSplitterOptions
     */
    chunkOverlap?: number;
}

/**
 * Check if a given object implements the SpacyTextSplitterOptions interface.
 */
export function instanceOfSpacyTextSplitterOptions(value: object): value is SpacyTextSplitterOptions {
    return true;
}

export function SpacyTextSplitterOptionsFromJSON(json: any): SpacyTextSplitterOptions {
    return SpacyTextSplitterOptionsFromJSONTyped(json, false);
}

export function SpacyTextSplitterOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpacyTextSplitterOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'separator': json['separator'] == null ? undefined : json['separator'],
        'pipeline': json['pipeline'] == null ? undefined : json['pipeline'],
        'maxLength': json['max_length'] == null ? undefined : json['max_length'],
        'stripWhitespace': json['strip_whitespace'] == null ? undefined : json['strip_whitespace'],
        'chunkSize': json['chunk_size'] == null ? undefined : json['chunk_size'],
        'chunkOverlap': json['chunk_overlap'] == null ? undefined : json['chunk_overlap'],
    };
}

export function SpacyTextSplitterOptionsToJSON(json: any): SpacyTextSplitterOptions {
    return SpacyTextSplitterOptionsToJSONTyped(json, false);
}

export function SpacyTextSplitterOptionsToJSONTyped(value?: SpacyTextSplitterOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'separator': value['separator'],
        'pipeline': value['pipeline'],
        'max_length': value['maxLength'],
        'strip_whitespace': value['stripWhitespace'],
        'chunk_size': value['chunkSize'],
        'chunk_overlap': value['chunkOverlap'],
    };
}

