# coding: utf-8

"""
    gantry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from openapi_client.models.file_metadata_filters_value import FileMetadataFiltersValue
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class QueryFilterByFileMetadata(BaseModel):
    """
    DTO for querying RAG embeddings with file metadata filters.
    """ # noqa: E501
    file_metadata_filters: Dict[str, FileMetadataFiltersValue]
    __properties: ClassVar[List[str]] = ["file_metadata_filters"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QueryFilterByFileMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in file_metadata_filters (dict)
        _field_dict = {}
        if self.file_metadata_filters:
            for _key_file_metadata_filters in self.file_metadata_filters:
                if self.file_metadata_filters[_key_file_metadata_filters]:
                    _field_dict[_key_file_metadata_filters] = self.file_metadata_filters[_key_file_metadata_filters].to_dict()
            _dict['file_metadata_filters'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QueryFilterByFileMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "file_metadata_filters": dict(
                (_k, FileMetadataFiltersValue.from_dict(_v))
                for _k, _v in obj["file_metadata_filters"].items()
            )
            if obj.get("file_metadata_filters") is not None
            else None
        })
        return _obj


