/*
gantry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ReasoningMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReasoningMessage{}

// ReasoningMessage A reasoning message containing the agent's internal reasoning process.
type ReasoningMessage struct {
	Id string `json:"id"`
	Role *string `json:"role,omitempty"`
	Content string `json:"content"`
	EncryptedValue NullableString `json:"encryptedValue,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ReasoningMessage ReasoningMessage

// NewReasoningMessage instantiates a new ReasoningMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReasoningMessage(id string, content string) *ReasoningMessage {
	this := ReasoningMessage{}
	this.Id = id
	var role string = "reasoning"
	this.Role = &role
	this.Content = content
	return &this
}

// NewReasoningMessageWithDefaults instantiates a new ReasoningMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReasoningMessageWithDefaults() *ReasoningMessage {
	this := ReasoningMessage{}
	var role string = "reasoning"
	this.Role = &role
	return &this
}

// GetId returns the Id field value
func (o *ReasoningMessage) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ReasoningMessage) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ReasoningMessage) SetId(v string) {
	o.Id = v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *ReasoningMessage) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReasoningMessage) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *ReasoningMessage) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *ReasoningMessage) SetRole(v string) {
	o.Role = &v
}

// GetContent returns the Content field value
func (o *ReasoningMessage) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *ReasoningMessage) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *ReasoningMessage) SetContent(v string) {
	o.Content = v
}

// GetEncryptedValue returns the EncryptedValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReasoningMessage) GetEncryptedValue() string {
	if o == nil || IsNil(o.EncryptedValue.Get()) {
		var ret string
		return ret
	}
	return *o.EncryptedValue.Get()
}

// GetEncryptedValueOk returns a tuple with the EncryptedValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReasoningMessage) GetEncryptedValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EncryptedValue.Get(), o.EncryptedValue.IsSet()
}

// HasEncryptedValue returns a boolean if a field has been set.
func (o *ReasoningMessage) HasEncryptedValue() bool {
	if o != nil && o.EncryptedValue.IsSet() {
		return true
	}

	return false
}

// SetEncryptedValue gets a reference to the given NullableString and assigns it to the EncryptedValue field.
func (o *ReasoningMessage) SetEncryptedValue(v string) {
	o.EncryptedValue.Set(&v)
}
// SetEncryptedValueNil sets the value for EncryptedValue to be an explicit nil
func (o *ReasoningMessage) SetEncryptedValueNil() {
	o.EncryptedValue.Set(nil)
}

// UnsetEncryptedValue ensures that no value is present for EncryptedValue, not even an explicit nil
func (o *ReasoningMessage) UnsetEncryptedValue() {
	o.EncryptedValue.Unset()
}

func (o ReasoningMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReasoningMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	toSerialize["content"] = o.Content
	if o.EncryptedValue.IsSet() {
		toSerialize["encryptedValue"] = o.EncryptedValue.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReasoningMessage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReasoningMessage := _ReasoningMessage{}

	err = json.Unmarshal(data, &varReasoningMessage)

	if err != nil {
		return err
	}

	*o = ReasoningMessage(varReasoningMessage)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "role")
		delete(additionalProperties, "content")
		delete(additionalProperties, "encryptedValue")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReasoningMessage struct {
	value *ReasoningMessage
	isSet bool
}

func (v NullableReasoningMessage) Get() *ReasoningMessage {
	return v.value
}

func (v *NullableReasoningMessage) Set(val *ReasoningMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableReasoningMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableReasoningMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReasoningMessage(val *ReasoningMessage) *NullableReasoningMessage {
	return &NullableReasoningMessage{value: val, isSet: true}
}

func (v NullableReasoningMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReasoningMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


