/*
gantry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TokenTextSplitterOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenTextSplitterOptions{}

// TokenTextSplitterOptions struct for TokenTextSplitterOptions
type TokenTextSplitterOptions struct {
	EncodingName *string `json:"encoding_name,omitempty"`
	ModelName NullableString `json:"model_name,omitempty"`
	AllowedSpecial NullableAllowedSpecial `json:"allowed_special,omitempty"`
	DisallowedSpecial *DisallowedSpecial `json:"disallowed_special,omitempty"`
	ChunkSize *int32 `json:"chunk_size,omitempty"`
	ChunkOverlap *int32 `json:"chunk_overlap,omitempty"`
}

// NewTokenTextSplitterOptions instantiates a new TokenTextSplitterOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenTextSplitterOptions() *TokenTextSplitterOptions {
	this := TokenTextSplitterOptions{}
	return &this
}

// NewTokenTextSplitterOptionsWithDefaults instantiates a new TokenTextSplitterOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenTextSplitterOptionsWithDefaults() *TokenTextSplitterOptions {
	this := TokenTextSplitterOptions{}
	return &this
}

// GetEncodingName returns the EncodingName field value if set, zero value otherwise.
func (o *TokenTextSplitterOptions) GetEncodingName() string {
	if o == nil || IsNil(o.EncodingName) {
		var ret string
		return ret
	}
	return *o.EncodingName
}

// GetEncodingNameOk returns a tuple with the EncodingName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenTextSplitterOptions) GetEncodingNameOk() (*string, bool) {
	if o == nil || IsNil(o.EncodingName) {
		return nil, false
	}
	return o.EncodingName, true
}

// HasEncodingName returns a boolean if a field has been set.
func (o *TokenTextSplitterOptions) HasEncodingName() bool {
	if o != nil && !IsNil(o.EncodingName) {
		return true
	}

	return false
}

// SetEncodingName gets a reference to the given string and assigns it to the EncodingName field.
func (o *TokenTextSplitterOptions) SetEncodingName(v string) {
	o.EncodingName = &v
}

// GetModelName returns the ModelName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TokenTextSplitterOptions) GetModelName() string {
	if o == nil || IsNil(o.ModelName.Get()) {
		var ret string
		return ret
	}
	return *o.ModelName.Get()
}

// GetModelNameOk returns a tuple with the ModelName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TokenTextSplitterOptions) GetModelNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ModelName.Get(), o.ModelName.IsSet()
}

// HasModelName returns a boolean if a field has been set.
func (o *TokenTextSplitterOptions) HasModelName() bool {
	if o != nil && o.ModelName.IsSet() {
		return true
	}

	return false
}

// SetModelName gets a reference to the given NullableString and assigns it to the ModelName field.
func (o *TokenTextSplitterOptions) SetModelName(v string) {
	o.ModelName.Set(&v)
}
// SetModelNameNil sets the value for ModelName to be an explicit nil
func (o *TokenTextSplitterOptions) SetModelNameNil() {
	o.ModelName.Set(nil)
}

// UnsetModelName ensures that no value is present for ModelName, not even an explicit nil
func (o *TokenTextSplitterOptions) UnsetModelName() {
	o.ModelName.Unset()
}

// GetAllowedSpecial returns the AllowedSpecial field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TokenTextSplitterOptions) GetAllowedSpecial() AllowedSpecial {
	if o == nil || IsNil(o.AllowedSpecial.Get()) {
		var ret AllowedSpecial
		return ret
	}
	return *o.AllowedSpecial.Get()
}

// GetAllowedSpecialOk returns a tuple with the AllowedSpecial field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TokenTextSplitterOptions) GetAllowedSpecialOk() (*AllowedSpecial, bool) {
	if o == nil {
		return nil, false
	}
	return o.AllowedSpecial.Get(), o.AllowedSpecial.IsSet()
}

// HasAllowedSpecial returns a boolean if a field has been set.
func (o *TokenTextSplitterOptions) HasAllowedSpecial() bool {
	if o != nil && o.AllowedSpecial.IsSet() {
		return true
	}

	return false
}

// SetAllowedSpecial gets a reference to the given NullableAllowedSpecial and assigns it to the AllowedSpecial field.
func (o *TokenTextSplitterOptions) SetAllowedSpecial(v AllowedSpecial) {
	o.AllowedSpecial.Set(&v)
}
// SetAllowedSpecialNil sets the value for AllowedSpecial to be an explicit nil
func (o *TokenTextSplitterOptions) SetAllowedSpecialNil() {
	o.AllowedSpecial.Set(nil)
}

// UnsetAllowedSpecial ensures that no value is present for AllowedSpecial, not even an explicit nil
func (o *TokenTextSplitterOptions) UnsetAllowedSpecial() {
	o.AllowedSpecial.Unset()
}

// GetDisallowedSpecial returns the DisallowedSpecial field value if set, zero value otherwise.
func (o *TokenTextSplitterOptions) GetDisallowedSpecial() DisallowedSpecial {
	if o == nil || IsNil(o.DisallowedSpecial) {
		var ret DisallowedSpecial
		return ret
	}
	return *o.DisallowedSpecial
}

// GetDisallowedSpecialOk returns a tuple with the DisallowedSpecial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenTextSplitterOptions) GetDisallowedSpecialOk() (*DisallowedSpecial, bool) {
	if o == nil || IsNil(o.DisallowedSpecial) {
		return nil, false
	}
	return o.DisallowedSpecial, true
}

// HasDisallowedSpecial returns a boolean if a field has been set.
func (o *TokenTextSplitterOptions) HasDisallowedSpecial() bool {
	if o != nil && !IsNil(o.DisallowedSpecial) {
		return true
	}

	return false
}

// SetDisallowedSpecial gets a reference to the given DisallowedSpecial and assigns it to the DisallowedSpecial field.
func (o *TokenTextSplitterOptions) SetDisallowedSpecial(v DisallowedSpecial) {
	o.DisallowedSpecial = &v
}

// GetChunkSize returns the ChunkSize field value if set, zero value otherwise.
func (o *TokenTextSplitterOptions) GetChunkSize() int32 {
	if o == nil || IsNil(o.ChunkSize) {
		var ret int32
		return ret
	}
	return *o.ChunkSize
}

// GetChunkSizeOk returns a tuple with the ChunkSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenTextSplitterOptions) GetChunkSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.ChunkSize) {
		return nil, false
	}
	return o.ChunkSize, true
}

// HasChunkSize returns a boolean if a field has been set.
func (o *TokenTextSplitterOptions) HasChunkSize() bool {
	if o != nil && !IsNil(o.ChunkSize) {
		return true
	}

	return false
}

// SetChunkSize gets a reference to the given int32 and assigns it to the ChunkSize field.
func (o *TokenTextSplitterOptions) SetChunkSize(v int32) {
	o.ChunkSize = &v
}

// GetChunkOverlap returns the ChunkOverlap field value if set, zero value otherwise.
func (o *TokenTextSplitterOptions) GetChunkOverlap() int32 {
	if o == nil || IsNil(o.ChunkOverlap) {
		var ret int32
		return ret
	}
	return *o.ChunkOverlap
}

// GetChunkOverlapOk returns a tuple with the ChunkOverlap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenTextSplitterOptions) GetChunkOverlapOk() (*int32, bool) {
	if o == nil || IsNil(o.ChunkOverlap) {
		return nil, false
	}
	return o.ChunkOverlap, true
}

// HasChunkOverlap returns a boolean if a field has been set.
func (o *TokenTextSplitterOptions) HasChunkOverlap() bool {
	if o != nil && !IsNil(o.ChunkOverlap) {
		return true
	}

	return false
}

// SetChunkOverlap gets a reference to the given int32 and assigns it to the ChunkOverlap field.
func (o *TokenTextSplitterOptions) SetChunkOverlap(v int32) {
	o.ChunkOverlap = &v
}

func (o TokenTextSplitterOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenTextSplitterOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EncodingName) {
		toSerialize["encoding_name"] = o.EncodingName
	}
	if o.ModelName.IsSet() {
		toSerialize["model_name"] = o.ModelName.Get()
	}
	if o.AllowedSpecial.IsSet() {
		toSerialize["allowed_special"] = o.AllowedSpecial.Get()
	}
	if !IsNil(o.DisallowedSpecial) {
		toSerialize["disallowed_special"] = o.DisallowedSpecial
	}
	if !IsNil(o.ChunkSize) {
		toSerialize["chunk_size"] = o.ChunkSize
	}
	if !IsNil(o.ChunkOverlap) {
		toSerialize["chunk_overlap"] = o.ChunkOverlap
	}
	return toSerialize, nil
}

type NullableTokenTextSplitterOptions struct {
	value *TokenTextSplitterOptions
	isSet bool
}

func (v NullableTokenTextSplitterOptions) Get() *TokenTextSplitterOptions {
	return v.value
}

func (v *NullableTokenTextSplitterOptions) Set(val *TokenTextSplitterOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenTextSplitterOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenTextSplitterOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenTextSplitterOptions(val *TokenTextSplitterOptions) *NullableTokenTextSplitterOptions {
	return &NullableTokenTextSplitterOptions{value: val, isSet: true}
}

func (v NullableTokenTextSplitterOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenTextSplitterOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


