/*
gantry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the AudioInputContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AudioInputContent{}

// AudioInputContent An audio input content fragment.
type AudioInputContent struct {
	Type *string `json:"type,omitempty"`
	Source Source `json:"source"`
	Metadata NullableAnyOf `json:"metadata,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AudioInputContent AudioInputContent

// NewAudioInputContent instantiates a new AudioInputContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAudioInputContent(source Source) *AudioInputContent {
	this := AudioInputContent{}
	var type_ string = "audio"
	this.Type = &type_
	this.Source = source
	return &this
}

// NewAudioInputContentWithDefaults instantiates a new AudioInputContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAudioInputContentWithDefaults() *AudioInputContent {
	this := AudioInputContent{}
	var type_ string = "audio"
	this.Type = &type_
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *AudioInputContent) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AudioInputContent) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *AudioInputContent) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *AudioInputContent) SetType(v string) {
	o.Type = &v
}

// GetSource returns the Source field value
func (o *AudioInputContent) GetSource() Source {
	if o == nil {
		var ret Source
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *AudioInputContent) GetSourceOk() (*Source, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *AudioInputContent) SetSource(v Source) {
	o.Source = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AudioInputContent) GetMetadata() AnyOf {
	if o == nil || IsNil(o.Metadata.Get()) {
		var ret AnyOf
		return ret
	}
	return *o.Metadata.Get()
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AudioInputContent) GetMetadataOk() (*AnyOf, bool) {
	if o == nil {
		return nil, false
	}
	return o.Metadata.Get(), o.Metadata.IsSet()
}

// HasMetadata returns a boolean if a field has been set.
func (o *AudioInputContent) HasMetadata() bool {
	if o != nil && o.Metadata.IsSet() {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given NullableAnyOf and assigns it to the Metadata field.
func (o *AudioInputContent) SetMetadata(v AnyOf) {
	o.Metadata.Set(&v)
}
// SetMetadataNil sets the value for Metadata to be an explicit nil
func (o *AudioInputContent) SetMetadataNil() {
	o.Metadata.Set(nil)
}

// UnsetMetadata ensures that no value is present for Metadata, not even an explicit nil
func (o *AudioInputContent) UnsetMetadata() {
	o.Metadata.Unset()
}

func (o AudioInputContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AudioInputContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	toSerialize["source"] = o.Source
	if o.Metadata.IsSet() {
		toSerialize["metadata"] = o.Metadata.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AudioInputContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAudioInputContent := _AudioInputContent{}

	err = json.Unmarshal(data, &varAudioInputContent)

	if err != nil {
		return err
	}

	*o = AudioInputContent(varAudioInputContent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "source")
		delete(additionalProperties, "metadata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAudioInputContent struct {
	value *AudioInputContent
	isSet bool
}

func (v NullableAudioInputContent) Get() *AudioInputContent {
	return v.value
}

func (v *NullableAudioInputContent) Set(val *AudioInputContent) {
	v.value = val
	v.isSet = true
}

func (v NullableAudioInputContent) IsSet() bool {
	return v.isSet
}

func (v *NullableAudioInputContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAudioInputContent(val *AudioInputContent) *NullableAudioInputContent {
	return &NullableAudioInputContent{value: val, isSet: true}
}

func (v NullableAudioInputContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAudioInputContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


