/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Event indicating the end of a reasoning message.
 * @export
 * @interface ReasoningMessageEndEvent
 */
export interface ReasoningMessageEndEvent {
    [key: string]: any | any;
    /**
     * 
     * @type {ReasoningMessageEndEventTypeEnum}
     * @memberof ReasoningMessageEndEvent
     */
    type?: ReasoningMessageEndEventTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ReasoningMessageEndEvent
     */
    timestamp?: number | null;
    /**
     * 
     * @type {}
     * @memberof ReasoningMessageEndEvent
     */
    rawEvent?:  | null;
    /**
     * 
     * @type {string}
     * @memberof ReasoningMessageEndEvent
     */
    messageId: string;
}


/**
 * @export
 */
export const ReasoningMessageEndEventTypeEnum = {
    ReasoningMessageEnd: 'REASONING_MESSAGE_END'
} as const;
export type ReasoningMessageEndEventTypeEnum = typeof ReasoningMessageEndEventTypeEnum[keyof typeof ReasoningMessageEndEventTypeEnum];


/**
 * Check if a given object implements the ReasoningMessageEndEvent interface.
 */
export function instanceOfReasoningMessageEndEvent(value: object): value is ReasoningMessageEndEvent {
    if (!('messageId' in value) || value['messageId'] === undefined) return false;
    return true;
}

export function ReasoningMessageEndEventFromJSON(json: any): ReasoningMessageEndEvent {
    return ReasoningMessageEndEventFromJSONTyped(json, false);
}

export function ReasoningMessageEndEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReasoningMessageEndEvent {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'] == null ? undefined : json['type'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'rawEvent': json['rawEvent'] == null ? undefined : FromJSON(json['rawEvent']),
        'messageId': json['messageId'],
    };
}

export function ReasoningMessageEndEventToJSON(json: any): ReasoningMessageEndEvent {
    return ReasoningMessageEndEventToJSONTyped(json, false);
}

export function ReasoningMessageEndEventToJSONTyped(value?: ReasoningMessageEndEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'timestamp': value['timestamp'],
        'rawEvent': ToJSON(value['rawEvent']),
        'messageId': value['messageId'],
    };
}

