/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Event indicating the end of a text message.
 * @export
 * @interface TextMessageEndEvent
 */
export interface TextMessageEndEvent {
    [key: string]: any | any;
    /**
     * 
     * @type {TextMessageEndEventTypeEnum}
     * @memberof TextMessageEndEvent
     */
    type?: TextMessageEndEventTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof TextMessageEndEvent
     */
    timestamp?: number | null;
    /**
     * 
     * @type {}
     * @memberof TextMessageEndEvent
     */
    rawEvent?:  | null;
    /**
     * 
     * @type {string}
     * @memberof TextMessageEndEvent
     */
    messageId: string;
}


/**
 * @export
 */
export const TextMessageEndEventTypeEnum = {
    TextMessageEnd: 'TEXT_MESSAGE_END'
} as const;
export type TextMessageEndEventTypeEnum = typeof TextMessageEndEventTypeEnum[keyof typeof TextMessageEndEventTypeEnum];


/**
 * Check if a given object implements the TextMessageEndEvent interface.
 */
export function instanceOfTextMessageEndEvent(value: object): value is TextMessageEndEvent {
    if (!('messageId' in value) || value['messageId'] === undefined) return false;
    return true;
}

export function TextMessageEndEventFromJSON(json: any): TextMessageEndEvent {
    return TextMessageEndEventFromJSONTyped(json, false);
}

export function TextMessageEndEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextMessageEndEvent {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'] == null ? undefined : json['type'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'rawEvent': json['rawEvent'] == null ? undefined : FromJSON(json['rawEvent']),
        'messageId': json['messageId'],
    };
}

export function TextMessageEndEventToJSON(json: any): TextMessageEndEvent {
    return TextMessageEndEventToJSONTyped(json, false);
}

export function TextMessageEndEventToJSONTyped(value?: TextMessageEndEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'timestamp': value['timestamp'],
        'rawEvent': ToJSON(value['rawEvent']),
        'messageId': value['messageId'],
    };
}

