/*
gantry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the HTMLHeaderTextSplitterOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HTMLHeaderTextSplitterOptions{}

// HTMLHeaderTextSplitterOptions struct for HTMLHeaderTextSplitterOptions
type HTMLHeaderTextSplitterOptions struct {
	HeadersToSplitOn [][]interface{} `json:"headers_to_split_on,omitempty"`
	ReturnEachElement *bool `json:"return_each_element,omitempty"`
}

// NewHTMLHeaderTextSplitterOptions instantiates a new HTMLHeaderTextSplitterOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHTMLHeaderTextSplitterOptions() *HTMLHeaderTextSplitterOptions {
	this := HTMLHeaderTextSplitterOptions{}
	return &this
}

// NewHTMLHeaderTextSplitterOptionsWithDefaults instantiates a new HTMLHeaderTextSplitterOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHTMLHeaderTextSplitterOptionsWithDefaults() *HTMLHeaderTextSplitterOptions {
	this := HTMLHeaderTextSplitterOptions{}
	return &this
}

// GetHeadersToSplitOn returns the HeadersToSplitOn field value if set, zero value otherwise.
func (o *HTMLHeaderTextSplitterOptions) GetHeadersToSplitOn() [][]interface{} {
	if o == nil || IsNil(o.HeadersToSplitOn) {
		var ret [][]interface{}
		return ret
	}
	return o.HeadersToSplitOn
}

// GetHeadersToSplitOnOk returns a tuple with the HeadersToSplitOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HTMLHeaderTextSplitterOptions) GetHeadersToSplitOnOk() ([][]interface{}, bool) {
	if o == nil || IsNil(o.HeadersToSplitOn) {
		return nil, false
	}
	return o.HeadersToSplitOn, true
}

// HasHeadersToSplitOn returns a boolean if a field has been set.
func (o *HTMLHeaderTextSplitterOptions) HasHeadersToSplitOn() bool {
	if o != nil && !IsNil(o.HeadersToSplitOn) {
		return true
	}

	return false
}

// SetHeadersToSplitOn gets a reference to the given [][]interface{} and assigns it to the HeadersToSplitOn field.
func (o *HTMLHeaderTextSplitterOptions) SetHeadersToSplitOn(v [][]interface{}) {
	o.HeadersToSplitOn = v
}

// GetReturnEachElement returns the ReturnEachElement field value if set, zero value otherwise.
func (o *HTMLHeaderTextSplitterOptions) GetReturnEachElement() bool {
	if o == nil || IsNil(o.ReturnEachElement) {
		var ret bool
		return ret
	}
	return *o.ReturnEachElement
}

// GetReturnEachElementOk returns a tuple with the ReturnEachElement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HTMLHeaderTextSplitterOptions) GetReturnEachElementOk() (*bool, bool) {
	if o == nil || IsNil(o.ReturnEachElement) {
		return nil, false
	}
	return o.ReturnEachElement, true
}

// HasReturnEachElement returns a boolean if a field has been set.
func (o *HTMLHeaderTextSplitterOptions) HasReturnEachElement() bool {
	if o != nil && !IsNil(o.ReturnEachElement) {
		return true
	}

	return false
}

// SetReturnEachElement gets a reference to the given bool and assigns it to the ReturnEachElement field.
func (o *HTMLHeaderTextSplitterOptions) SetReturnEachElement(v bool) {
	o.ReturnEachElement = &v
}

func (o HTMLHeaderTextSplitterOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HTMLHeaderTextSplitterOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HeadersToSplitOn) {
		toSerialize["headers_to_split_on"] = o.HeadersToSplitOn
	}
	if !IsNil(o.ReturnEachElement) {
		toSerialize["return_each_element"] = o.ReturnEachElement
	}
	return toSerialize, nil
}

type NullableHTMLHeaderTextSplitterOptions struct {
	value *HTMLHeaderTextSplitterOptions
	isSet bool
}

func (v NullableHTMLHeaderTextSplitterOptions) Get() *HTMLHeaderTextSplitterOptions {
	return v.value
}

func (v *NullableHTMLHeaderTextSplitterOptions) Set(val *HTMLHeaderTextSplitterOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableHTMLHeaderTextSplitterOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableHTMLHeaderTextSplitterOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHTMLHeaderTextSplitterOptions(val *HTMLHeaderTextSplitterOptions) *NullableHTMLHeaderTextSplitterOptions {
	return &NullableHTMLHeaderTextSplitterOptions{value: val, isSet: true}
}

func (v NullableHTMLHeaderTextSplitterOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHTMLHeaderTextSplitterOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


