/*
gantry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ToolMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ToolMessage{}

// ToolMessage A tool result message.
type ToolMessage struct {
	Id string `json:"id"`
	Role *string `json:"role,omitempty"`
	Content string `json:"content"`
	ToolCallId string `json:"toolCallId"`
	Error NullableString `json:"error,omitempty"`
	EncryptedValue NullableString `json:"encryptedValue,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ToolMessage ToolMessage

// NewToolMessage instantiates a new ToolMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewToolMessage(id string, content string, toolCallId string) *ToolMessage {
	this := ToolMessage{}
	this.Id = id
	var role string = "tool"
	this.Role = &role
	this.Content = content
	this.ToolCallId = toolCallId
	return &this
}

// NewToolMessageWithDefaults instantiates a new ToolMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewToolMessageWithDefaults() *ToolMessage {
	this := ToolMessage{}
	var role string = "tool"
	this.Role = &role
	return &this
}

// GetId returns the Id field value
func (o *ToolMessage) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ToolMessage) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ToolMessage) SetId(v string) {
	o.Id = v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *ToolMessage) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ToolMessage) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *ToolMessage) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *ToolMessage) SetRole(v string) {
	o.Role = &v
}

// GetContent returns the Content field value
func (o *ToolMessage) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *ToolMessage) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *ToolMessage) SetContent(v string) {
	o.Content = v
}

// GetToolCallId returns the ToolCallId field value
func (o *ToolMessage) GetToolCallId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ToolCallId
}

// GetToolCallIdOk returns a tuple with the ToolCallId field value
// and a boolean to check if the value has been set.
func (o *ToolMessage) GetToolCallIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToolCallId, true
}

// SetToolCallId sets field value
func (o *ToolMessage) SetToolCallId(v string) {
	o.ToolCallId = v
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ToolMessage) GetError() string {
	if o == nil || IsNil(o.Error.Get()) {
		var ret string
		return ret
	}
	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ToolMessage) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// HasError returns a boolean if a field has been set.
func (o *ToolMessage) HasError() bool {
	if o != nil && o.Error.IsSet() {
		return true
	}

	return false
}

// SetError gets a reference to the given NullableString and assigns it to the Error field.
func (o *ToolMessage) SetError(v string) {
	o.Error.Set(&v)
}
// SetErrorNil sets the value for Error to be an explicit nil
func (o *ToolMessage) SetErrorNil() {
	o.Error.Set(nil)
}

// UnsetError ensures that no value is present for Error, not even an explicit nil
func (o *ToolMessage) UnsetError() {
	o.Error.Unset()
}

// GetEncryptedValue returns the EncryptedValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ToolMessage) GetEncryptedValue() string {
	if o == nil || IsNil(o.EncryptedValue.Get()) {
		var ret string
		return ret
	}
	return *o.EncryptedValue.Get()
}

// GetEncryptedValueOk returns a tuple with the EncryptedValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ToolMessage) GetEncryptedValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EncryptedValue.Get(), o.EncryptedValue.IsSet()
}

// HasEncryptedValue returns a boolean if a field has been set.
func (o *ToolMessage) HasEncryptedValue() bool {
	if o != nil && o.EncryptedValue.IsSet() {
		return true
	}

	return false
}

// SetEncryptedValue gets a reference to the given NullableString and assigns it to the EncryptedValue field.
func (o *ToolMessage) SetEncryptedValue(v string) {
	o.EncryptedValue.Set(&v)
}
// SetEncryptedValueNil sets the value for EncryptedValue to be an explicit nil
func (o *ToolMessage) SetEncryptedValueNil() {
	o.EncryptedValue.Set(nil)
}

// UnsetEncryptedValue ensures that no value is present for EncryptedValue, not even an explicit nil
func (o *ToolMessage) UnsetEncryptedValue() {
	o.EncryptedValue.Unset()
}

func (o ToolMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ToolMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	toSerialize["content"] = o.Content
	toSerialize["toolCallId"] = o.ToolCallId
	if o.Error.IsSet() {
		toSerialize["error"] = o.Error.Get()
	}
	if o.EncryptedValue.IsSet() {
		toSerialize["encryptedValue"] = o.EncryptedValue.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ToolMessage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"content",
		"toolCallId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varToolMessage := _ToolMessage{}

	err = json.Unmarshal(data, &varToolMessage)

	if err != nil {
		return err
	}

	*o = ToolMessage(varToolMessage)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "role")
		delete(additionalProperties, "content")
		delete(additionalProperties, "toolCallId")
		delete(additionalProperties, "error")
		delete(additionalProperties, "encryptedValue")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableToolMessage struct {
	value *ToolMessage
	isSet bool
}

func (v NullableToolMessage) Get() *ToolMessage {
	return v.value
}

func (v *NullableToolMessage) Set(val *ToolMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableToolMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableToolMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToolMessage(val *ToolMessage) *NullableToolMessage {
	return &NullableToolMessage{value: val, isSet: true}
}

func (v NullableToolMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToolMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


