/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FunctionCall } from './FunctionCall';
import {
    FunctionCallFromJSON,
    FunctionCallFromJSONTyped,
    FunctionCallToJSON,
    FunctionCallToJSONTyped,
} from './FunctionCall';

/**
 * A tool call, modelled after OpenAI tool calls.
 * @export
 * @interface ToolCall
 */
export interface ToolCall {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof ToolCall
     */
    id: string;
    /**
     * 
     * @type {ToolCallTypeEnum}
     * @memberof ToolCall
     */
    type?: ToolCallTypeEnum;
    /**
     * 
     * @type {FunctionCall}
     * @memberof ToolCall
     */
    _function: FunctionCall;
    /**
     * 
     * @type {string}
     * @memberof ToolCall
     */
    encryptedValue?: string | null;
}


/**
 * @export
 */
export const ToolCallTypeEnum = {
    Function: 'function'
} as const;
export type ToolCallTypeEnum = typeof ToolCallTypeEnum[keyof typeof ToolCallTypeEnum];


/**
 * Check if a given object implements the ToolCall interface.
 */
export function instanceOfToolCall(value: object): value is ToolCall {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('_function' in value) || value['_function'] === undefined) return false;
    return true;
}

export function ToolCallFromJSON(json: any): ToolCall {
    return ToolCallFromJSONTyped(json, false);
}

export function ToolCallFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolCall {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        '_function': FunctionCallFromJSON(json['function']),
        'encryptedValue': json['encryptedValue'] == null ? undefined : json['encryptedValue'],
    };
}

export function ToolCallToJSON(json: any): ToolCall {
    return ToolCallToJSONTyped(json, false);
}

export function ToolCallToJSONTyped(value?: ToolCall | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'type': value['type'],
        'function': FunctionCallToJSON(value['_function']),
        'encryptedValue': value['encryptedValue'],
    };
}

