/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CaptureRequest,
    CaptureRequestFromJSON,
    CaptureRequestToJSON,
} from '../models/CaptureRequest';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type PostRequest,
    PostRequestFromJSON,
    PostRequestToJSON,
} from '../models/PostRequest';

export interface CaptureBillingTransactionUidCapturePostRequest {
    transactionUid: string;
    captureRequest: CaptureRequest;
}

export interface PostBillingPostRequest {
    postRequest: PostRequest;
    idempotencyKey?: string | null;
}

/**
 * 
 */
export class InternalApi extends runtime.BaseAPI {

    /**
     * Creates request options for captureBillingTransactionUidCapturePost without sending the request
     */
    async captureBillingTransactionUidCapturePostRequestOpts(requestParameters: CaptureBillingTransactionUidCapturePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['transactionUid'] == null) {
            throw new runtime.RequiredError(
                'transactionUid',
                'Required parameter "transactionUid" was null or undefined when calling captureBillingTransactionUidCapturePost().'
            );
        }

        if (requestParameters['captureRequest'] == null) {
            throw new runtime.RequiredError(
                'captureRequest',
                'Required parameter "captureRequest" was null or undefined when calling captureBillingTransactionUidCapturePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/billing/{transaction_uid}/capture`;
        urlPath = urlPath.replace('{transaction_uid}', encodeURIComponent(String(requestParameters['transactionUid'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CaptureRequestToJSON(requestParameters['captureRequest']),
        };
    }

    /**
     * Capture
     */
    async captureBillingTransactionUidCapturePostRaw(requestParameters: CaptureBillingTransactionUidCapturePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        const requestOptions = await this.captureBillingTransactionUidCapturePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Capture
     */
    async captureBillingTransactionUidCapturePost(requestParameters: CaptureBillingTransactionUidCapturePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.captureBillingTransactionUidCapturePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postBillingPost without sending the request
     */
    async postBillingPostRequestOpts(requestParameters: PostBillingPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postRequest'] == null) {
            throw new runtime.RequiredError(
                'postRequest',
                'Required parameter "postRequest" was null or undefined when calling postBillingPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['idempotency-key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/billing/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostRequestToJSON(requestParameters['postRequest']),
        };
    }

    /**
     * Post
     */
    async postBillingPostRaw(requestParameters: PostBillingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.postBillingPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Post
     */
    async postBillingPost(requestParameters: PostBillingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.postBillingPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
