# coding: utf-8

"""
    gantry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.file_info_with_presigned_url_response import FileInfoWithPresignedURLResponse

class TestFileInfoWithPresignedURLResponse(unittest.TestCase):
    """FileInfoWithPresignedURLResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileInfoWithPresignedURLResponse:
        """Test FileInfoWithPresignedURLResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileInfoWithPresignedURLResponse`
        """
        model = FileInfoWithPresignedURLResponse()
        if include_optional:
            return FileInfoWithPresignedURLResponse(
                url = '',
                id = '',
                filename = '',
                mime_type = '',
                size = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                extra_metadata = { }
            )
        else:
            return FileInfoWithPresignedURLResponse(
                url = '',
                id = '',
                filename = '',
                mime_type = '',
                size = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                extra_metadata = { },
        )
        """

    def testFileInfoWithPresignedURLResponse(self):
        """Test FileInfoWithPresignedURLResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
