# coding: utf-8

"""
    gantry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.file_storage_api import FileStorageApi


class TestFileStorageApi(unittest.TestCase):
    """FileStorageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FileStorageApi()

    def tearDown(self) -> None:
        pass

    def test_delete_file_file_storage_file_id_delete(self) -> None:
        """Test case for delete_file_file_storage_file_id_delete

        Delete a file by file ID.
        """
        pass

    def test_download_file_file_storage_file_id_download_get(self) -> None:
        """Test case for download_file_file_storage_file_id_download_get

        Download a file by file ID.
        """
        pass

    def test_get_file_info_and_presigned_url_file_storage_file_id_get(self) -> None:
        """Test case for get_file_info_and_presigned_url_file_storage_file_id_get

        Get file info and presigned URL by file ID.
        """
        pass

    def test_get_file_info_file_storage_file_id_info_get(self) -> None:
        """Test case for get_file_info_file_storage_file_id_info_get

        Get file info by file ID.
        """
        pass

    def test_get_file_presigned_url_file_storage_file_id_presigned_url_get(self) -> None:
        """Test case for get_file_presigned_url_file_storage_file_id_presigned_url_get

        Get presigned URL for file download.
        """
        pass

    def test_list_files_file_storage_get(self) -> None:
        """Test case for list_files_file_storage_get

        List files in the file storage service.
        """
        pass

    def test_update_file_metadata_file_storage_file_id_metadata_put(self) -> None:
        """Test case for update_file_metadata_file_storage_file_id_metadata_put

        Update file metadata by file ID.
        """
        pass

    def test_upload_file_file_storage_post(self) -> None:
        """Test case for upload_file_file_storage_post

        Upload a file to the file storage service.
        """
        pass


if __name__ == '__main__':
    unittest.main()
