# coding: utf-8

"""
    gantry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.raw_event import RawEvent

class TestRawEvent(unittest.TestCase):
    """RawEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RawEvent:
        """Test RawEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RawEvent`
        """
        model = RawEvent()
        if include_optional:
            return RawEvent(
                type = 'RAW',
                timestamp = 56,
                raw_event = None,
                event = None,
                source = ''
            )
        else:
            return RawEvent(
                event = None,
        )
        """

    def testRawEvent(self):
        """Test RawEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
