# coding: utf-8

"""
    gantry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.system_message import SystemMessage

class TestSystemMessage(unittest.TestCase):
    """SystemMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SystemMessage:
        """Test SystemMessage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SystemMessage`
        """
        model = SystemMessage()
        if include_optional:
            return SystemMessage(
                id = '',
                role = 'system',
                content = '',
                name = '',
                encrypted_value = ''
            )
        else:
            return SystemMessage(
                id = '',
                content = '',
        )
        """

    def testSystemMessage(self):
        """Test SystemMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
