/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChunkSplitterType } from './ChunkSplitterType';
import {
    ChunkSplitterTypeFromJSON,
    ChunkSplitterTypeFromJSONTyped,
    ChunkSplitterTypeToJSON,
    ChunkSplitterTypeToJSONTyped,
} from './ChunkSplitterType';
import type { ChunkSplitterOptions } from './ChunkSplitterOptions';
import {
    ChunkSplitterOptionsFromJSON,
    ChunkSplitterOptionsFromJSONTyped,
    ChunkSplitterOptionsToJSON,
    ChunkSplitterOptionsToJSONTyped,
} from './ChunkSplitterOptions';
import type { Text1 } from './Text1';
import {
    Text1FromJSON,
    Text1FromJSONTyped,
    Text1ToJSON,
    Text1ToJSONTyped,
} from './Text1';

/**
 * DTO for RAG embedding task status response.
 * @export
 * @interface EmbeddingTaskResponse
 */
export interface EmbeddingTaskResponse {
    /**
     * 
     * @type {string}
     * @memberof EmbeddingTaskResponse
     */
    taskId: string;
    /**
     * 
     * @type {string}
     * @memberof EmbeddingTaskResponse
     */
    fileUid: string | null;
    /**
     * 
     * @type {Text1}
     * @memberof EmbeddingTaskResponse
     */
    text: Text1 | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof EmbeddingTaskResponse
     */
    metadata: { [key: string]: any; } | null;
    /**
     * 
     * @type {EmbeddingTaskResponseTypeEnum}
     * @memberof EmbeddingTaskResponse
     */
    type: EmbeddingTaskResponseTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof EmbeddingTaskResponse
     */
    projectUuid: string;
    /**
     * 
     * @type {ChunkSplitterType}
     * @memberof EmbeddingTaskResponse
     */
    chunkSplitter: ChunkSplitterType;
    /**
     * 
     * @type {ChunkSplitterOptions}
     * @memberof EmbeddingTaskResponse
     */
    chunkSplitterOptions?: ChunkSplitterOptions;
    /**
     * 
     * @type {number}
     * @memberof EmbeddingTaskResponse
     */
    chunkSize: number;
    /**
     * 
     * @type {number}
     * @memberof EmbeddingTaskResponse
     */
    chunkOverlap: number;
    /**
     * 
     * @type {string}
     * @memberof EmbeddingTaskResponse
     */
    failedReason?: string | null;
    /**
     * 
     * @type {EmbeddingTaskResponseStatusEnum}
     * @memberof EmbeddingTaskResponse
     */
    status: EmbeddingTaskResponseStatusEnum;
}


/**
 * @export
 */
export const EmbeddingTaskResponseTypeEnum = {
    File: 'file',
    Text: 'text'
} as const;
export type EmbeddingTaskResponseTypeEnum = typeof EmbeddingTaskResponseTypeEnum[keyof typeof EmbeddingTaskResponseTypeEnum];

/**
 * @export
 */
export const EmbeddingTaskResponseStatusEnum = {
    Pending: 'pending',
    Completed: 'completed',
    FailedAndRetrying: 'failed_and_retrying',
    FailedAndDropped: 'failed_and_dropped'
} as const;
export type EmbeddingTaskResponseStatusEnum = typeof EmbeddingTaskResponseStatusEnum[keyof typeof EmbeddingTaskResponseStatusEnum];


/**
 * Check if a given object implements the EmbeddingTaskResponse interface.
 */
export function instanceOfEmbeddingTaskResponse(value: object): value is EmbeddingTaskResponse {
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    if (!('fileUid' in value) || value['fileUid'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('projectUuid' in value) || value['projectUuid'] === undefined) return false;
    if (!('chunkSplitter' in value) || value['chunkSplitter'] === undefined) return false;
    if (!('chunkSize' in value) || value['chunkSize'] === undefined) return false;
    if (!('chunkOverlap' in value) || value['chunkOverlap'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function EmbeddingTaskResponseFromJSON(json: any): EmbeddingTaskResponse {
    return EmbeddingTaskResponseFromJSONTyped(json, false);
}

export function EmbeddingTaskResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddingTaskResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['task_id'],
        'fileUid': json['file_uid'],
        'text': Text1FromJSON(json['text']),
        'metadata': json['metadata'],
        'type': json['type'],
        'projectUuid': json['project_uuid'],
        'chunkSplitter': ChunkSplitterTypeFromJSON(json['chunk_splitter']),
        'chunkSplitterOptions': json['chunk_splitter_options'] == null ? undefined : ChunkSplitterOptionsFromJSON(json['chunk_splitter_options']),
        'chunkSize': json['chunk_size'],
        'chunkOverlap': json['chunk_overlap'],
        'failedReason': json['failed_reason'] == null ? undefined : json['failed_reason'],
        'status': json['status'],
    };
}

export function EmbeddingTaskResponseToJSON(json: any): EmbeddingTaskResponse {
    return EmbeddingTaskResponseToJSONTyped(json, false);
}

export function EmbeddingTaskResponseToJSONTyped(value?: EmbeddingTaskResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task_id': value['taskId'],
        'file_uid': value['fileUid'],
        'text': Text1ToJSON(value['text']),
        'metadata': value['metadata'],
        'type': value['type'],
        'project_uuid': value['projectUuid'],
        'chunk_splitter': ChunkSplitterTypeToJSON(value['chunkSplitter']),
        'chunk_splitter_options': ChunkSplitterOptionsToJSON(value['chunkSplitterOptions']),
        'chunk_size': value['chunkSize'],
        'chunk_overlap': value['chunkOverlap'],
        'failed_reason': value['failedReason'],
        'status': value['status'],
    };
}

