/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Event containing an encrypted value for a message or tool call.
 * @export
 * @interface ReasoningEncryptedValueEvent
 */
export interface ReasoningEncryptedValueEvent {
    [key: string]: any | any;
    /**
     * 
     * @type {ReasoningEncryptedValueEventTypeEnum}
     * @memberof ReasoningEncryptedValueEvent
     */
    type?: ReasoningEncryptedValueEventTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ReasoningEncryptedValueEvent
     */
    timestamp?: number | null;
    /**
     * 
     * @type {}
     * @memberof ReasoningEncryptedValueEvent
     */
    rawEvent?:  | null;
    /**
     * 
     * @type {ReasoningEncryptedValueEventSubtypeEnum}
     * @memberof ReasoningEncryptedValueEvent
     */
    subtype: ReasoningEncryptedValueEventSubtypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ReasoningEncryptedValueEvent
     */
    entityId: string;
    /**
     * 
     * @type {string}
     * @memberof ReasoningEncryptedValueEvent
     */
    encryptedValue: string;
}


/**
 * @export
 */
export const ReasoningEncryptedValueEventTypeEnum = {
    ReasoningEncryptedValue: 'REASONING_ENCRYPTED_VALUE'
} as const;
export type ReasoningEncryptedValueEventTypeEnum = typeof ReasoningEncryptedValueEventTypeEnum[keyof typeof ReasoningEncryptedValueEventTypeEnum];

/**
 * @export
 */
export const ReasoningEncryptedValueEventSubtypeEnum = {
    ToolCall: 'tool-call',
    Message: 'message'
} as const;
export type ReasoningEncryptedValueEventSubtypeEnum = typeof ReasoningEncryptedValueEventSubtypeEnum[keyof typeof ReasoningEncryptedValueEventSubtypeEnum];


/**
 * Check if a given object implements the ReasoningEncryptedValueEvent interface.
 */
export function instanceOfReasoningEncryptedValueEvent(value: object): value is ReasoningEncryptedValueEvent {
    if (!('subtype' in value) || value['subtype'] === undefined) return false;
    if (!('entityId' in value) || value['entityId'] === undefined) return false;
    if (!('encryptedValue' in value) || value['encryptedValue'] === undefined) return false;
    return true;
}

export function ReasoningEncryptedValueEventFromJSON(json: any): ReasoningEncryptedValueEvent {
    return ReasoningEncryptedValueEventFromJSONTyped(json, false);
}

export function ReasoningEncryptedValueEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReasoningEncryptedValueEvent {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'] == null ? undefined : json['type'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'rawEvent': json['rawEvent'] == null ? undefined : FromJSON(json['rawEvent']),
        'subtype': json['subtype'],
        'entityId': json['entityId'],
        'encryptedValue': json['encryptedValue'],
    };
}

export function ReasoningEncryptedValueEventToJSON(json: any): ReasoningEncryptedValueEvent {
    return ReasoningEncryptedValueEventToJSONTyped(json, false);
}

export function ReasoningEncryptedValueEventToJSONTyped(value?: ReasoningEncryptedValueEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'timestamp': value['timestamp'],
        'rawEvent': ToJSON(value['rawEvent']),
        'subtype': value['subtype'],
        'entityId': value['entityId'],
        'encryptedValue': value['encryptedValue'],
    };
}

