/*
gantry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the RawEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RawEvent{}

// RawEvent Event containing a raw event.
type RawEvent struct {
	Type *string `json:"type,omitempty"`
	Timestamp NullableInt32 `json:"timestamp,omitempty"`
	RawEvent NullableAnyOf `json:"rawEvent,omitempty"`
	Event interface{} `json:"event"`
	Source NullableString `json:"source,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RawEvent RawEvent

// NewRawEvent instantiates a new RawEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRawEvent(event interface{}) *RawEvent {
	this := RawEvent{}
	var type_ string = "RAW"
	this.Type = &type_
	this.Event = event
	return &this
}

// NewRawEventWithDefaults instantiates a new RawEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRawEventWithDefaults() *RawEvent {
	this := RawEvent{}
	var type_ string = "RAW"
	this.Type = &type_
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *RawEvent) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawEvent) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *RawEvent) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *RawEvent) SetType(v string) {
	o.Type = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RawEvent) GetTimestamp() int32 {
	if o == nil || IsNil(o.Timestamp.Get()) {
		var ret int32
		return ret
	}
	return *o.Timestamp.Get()
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RawEvent) GetTimestampOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timestamp.Get(), o.Timestamp.IsSet()
}

// HasTimestamp returns a boolean if a field has been set.
func (o *RawEvent) HasTimestamp() bool {
	if o != nil && o.Timestamp.IsSet() {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given NullableInt32 and assigns it to the Timestamp field.
func (o *RawEvent) SetTimestamp(v int32) {
	o.Timestamp.Set(&v)
}
// SetTimestampNil sets the value for Timestamp to be an explicit nil
func (o *RawEvent) SetTimestampNil() {
	o.Timestamp.Set(nil)
}

// UnsetTimestamp ensures that no value is present for Timestamp, not even an explicit nil
func (o *RawEvent) UnsetTimestamp() {
	o.Timestamp.Unset()
}

// GetRawEvent returns the RawEvent field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RawEvent) GetRawEvent() AnyOf {
	if o == nil || IsNil(o.RawEvent.Get()) {
		var ret AnyOf
		return ret
	}
	return *o.RawEvent.Get()
}

// GetRawEventOk returns a tuple with the RawEvent field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RawEvent) GetRawEventOk() (*AnyOf, bool) {
	if o == nil {
		return nil, false
	}
	return o.RawEvent.Get(), o.RawEvent.IsSet()
}

// HasRawEvent returns a boolean if a field has been set.
func (o *RawEvent) HasRawEvent() bool {
	if o != nil && o.RawEvent.IsSet() {
		return true
	}

	return false
}

// SetRawEvent gets a reference to the given NullableAnyOf and assigns it to the RawEvent field.
func (o *RawEvent) SetRawEvent(v AnyOf) {
	o.RawEvent.Set(&v)
}
// SetRawEventNil sets the value for RawEvent to be an explicit nil
func (o *RawEvent) SetRawEventNil() {
	o.RawEvent.Set(nil)
}

// UnsetRawEvent ensures that no value is present for RawEvent, not even an explicit nil
func (o *RawEvent) UnsetRawEvent() {
	o.RawEvent.Unset()
}

// GetEvent returns the Event field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *RawEvent) GetEvent() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RawEvent) GetEventOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Event) {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *RawEvent) SetEvent(v interface{}) {
	o.Event = v
}

// GetSource returns the Source field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RawEvent) GetSource() string {
	if o == nil || IsNil(o.Source.Get()) {
		var ret string
		return ret
	}
	return *o.Source.Get()
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RawEvent) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Source.Get(), o.Source.IsSet()
}

// HasSource returns a boolean if a field has been set.
func (o *RawEvent) HasSource() bool {
	if o != nil && o.Source.IsSet() {
		return true
	}

	return false
}

// SetSource gets a reference to the given NullableString and assigns it to the Source field.
func (o *RawEvent) SetSource(v string) {
	o.Source.Set(&v)
}
// SetSourceNil sets the value for Source to be an explicit nil
func (o *RawEvent) SetSourceNil() {
	o.Source.Set(nil)
}

// UnsetSource ensures that no value is present for Source, not even an explicit nil
func (o *RawEvent) UnsetSource() {
	o.Source.Unset()
}

func (o RawEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RawEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if o.Timestamp.IsSet() {
		toSerialize["timestamp"] = o.Timestamp.Get()
	}
	if o.RawEvent.IsSet() {
		toSerialize["rawEvent"] = o.RawEvent.Get()
	}
	if o.Event != nil {
		toSerialize["event"] = o.Event
	}
	if o.Source.IsSet() {
		toSerialize["source"] = o.Source.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RawEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRawEvent := _RawEvent{}

	err = json.Unmarshal(data, &varRawEvent)

	if err != nil {
		return err
	}

	*o = RawEvent(varRawEvent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "timestamp")
		delete(additionalProperties, "rawEvent")
		delete(additionalProperties, "event")
		delete(additionalProperties, "source")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRawEvent struct {
	value *RawEvent
	isSet bool
}

func (v NullableRawEvent) Get() *RawEvent {
	return v.value
}

func (v *NullableRawEvent) Set(val *RawEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableRawEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableRawEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRawEvent(val *RawEvent) *NullableRawEvent {
	return &NullableRawEvent{value: val, isSet: true}
}

func (v NullableRawEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRawEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


