/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * DTO for file upload response.
 * @export
 * @interface FileUploadResponse
 */
export interface FileUploadResponse {
    /**
     * 
     * @type {string}
     * @memberof FileUploadResponse
     */
    fileId: string;
}

/**
 * Check if a given object implements the FileUploadResponse interface.
 */
export function instanceOfFileUploadResponse(value: object): value is FileUploadResponse {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function FileUploadResponseFromJSON(json: any): FileUploadResponse {
    return FileUploadResponseFromJSONTyped(json, false);
}

export function FileUploadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileUploadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'fileId': json['file_id'],
    };
}

export function FileUploadResponseToJSON(json: any): FileUploadResponse {
    return FileUploadResponseToJSONTyped(json, false);
}

export function FileUploadResponseToJSONTyped(value?: FileUploadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file_id': value['fileId'],
    };
}

