/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * DTO for file info with URL response.
 * @export
 * @interface FileInfoWithPresignedURLResponse
 */
export interface FileInfoWithPresignedURLResponse {
    /**
     * 
     * @type {string}
     * @memberof FileInfoWithPresignedURLResponse
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof FileInfoWithPresignedURLResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FileInfoWithPresignedURLResponse
     */
    filename: string;
    /**
     * 
     * @type {string}
     * @memberof FileInfoWithPresignedURLResponse
     */
    mimeType: string;
    /**
     * 
     * @type {number}
     * @memberof FileInfoWithPresignedURLResponse
     */
    size: number;
    /**
     * 
     * @type {Date}
     * @memberof FileInfoWithPresignedURLResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof FileInfoWithPresignedURLResponse
     */
    extraMetadata: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the FileInfoWithPresignedURLResponse interface.
 */
export function instanceOfFileInfoWithPresignedURLResponse(value: object): value is FileInfoWithPresignedURLResponse {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('extraMetadata' in value) || value['extraMetadata'] === undefined) return false;
    return true;
}

export function FileInfoWithPresignedURLResponseFromJSON(json: any): FileInfoWithPresignedURLResponse {
    return FileInfoWithPresignedURLResponseFromJSONTyped(json, false);
}

export function FileInfoWithPresignedURLResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileInfoWithPresignedURLResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'id': json['id'],
        'filename': json['filename'],
        'mimeType': json['mime_type'],
        'size': json['size'],
        'createdAt': (new Date(json['created_at'])),
        'extraMetadata': json['extra_metadata'],
    };
}

export function FileInfoWithPresignedURLResponseToJSON(json: any): FileInfoWithPresignedURLResponse {
    return FileInfoWithPresignedURLResponseToJSONTyped(json, false);
}

export function FileInfoWithPresignedURLResponseToJSONTyped(value?: FileInfoWithPresignedURLResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'id': value['id'],
        'filename': value['filename'],
        'mime_type': value['mimeType'],
        'size': value['size'],
        'created_at': value['createdAt'].toISOString(),
        'extra_metadata': value['extraMetadata'],
    };
}

