/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Event containing a chunk of reasoning message content.
 * @export
 * @interface ReasoningMessageChunkEvent
 */
export interface ReasoningMessageChunkEvent {
    [key: string]: any | any;
    /**
     * 
     * @type {ReasoningMessageChunkEventTypeEnum}
     * @memberof ReasoningMessageChunkEvent
     */
    type?: ReasoningMessageChunkEventTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ReasoningMessageChunkEvent
     */
    timestamp?: number | null;
    /**
     * 
     * @type {}
     * @memberof ReasoningMessageChunkEvent
     */
    rawEvent?:  | null;
    /**
     * 
     * @type {string}
     * @memberof ReasoningMessageChunkEvent
     */
    messageId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReasoningMessageChunkEvent
     */
    delta?: string | null;
}


/**
 * @export
 */
export const ReasoningMessageChunkEventTypeEnum = {
    ReasoningMessageChunk: 'REASONING_MESSAGE_CHUNK'
} as const;
export type ReasoningMessageChunkEventTypeEnum = typeof ReasoningMessageChunkEventTypeEnum[keyof typeof ReasoningMessageChunkEventTypeEnum];


/**
 * Check if a given object implements the ReasoningMessageChunkEvent interface.
 */
export function instanceOfReasoningMessageChunkEvent(value: object): value is ReasoningMessageChunkEvent {
    return true;
}

export function ReasoningMessageChunkEventFromJSON(json: any): ReasoningMessageChunkEvent {
    return ReasoningMessageChunkEventFromJSONTyped(json, false);
}

export function ReasoningMessageChunkEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReasoningMessageChunkEvent {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'] == null ? undefined : json['type'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'rawEvent': json['rawEvent'] == null ? undefined : FromJSON(json['rawEvent']),
        'messageId': json['messageId'] == null ? undefined : json['messageId'],
        'delta': json['delta'] == null ? undefined : json['delta'],
    };
}

export function ReasoningMessageChunkEventToJSON(json: any): ReasoningMessageChunkEvent {
    return ReasoningMessageChunkEventToJSONTyped(json, false);
}

export function ReasoningMessageChunkEventToJSONTyped(value?: ReasoningMessageChunkEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'timestamp': value['timestamp'],
        'rawEvent': ToJSON(value['rawEvent']),
        'messageId': value['messageId'],
        'delta': value['delta'],
    };
}

