/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { InputContentDataSource } from './InputContentDataSource';
import {
    instanceOfInputContentDataSource,
    InputContentDataSourceFromJSON,
    InputContentDataSourceFromJSONTyped,
    InputContentDataSourceToJSON,
} from './InputContentDataSource';
import type { InputContentUrlSource } from './InputContentUrlSource';
import {
    instanceOfInputContentUrlSource,
    InputContentUrlSourceFromJSON,
    InputContentUrlSourceFromJSONTyped,
    InputContentUrlSourceToJSON,
} from './InputContentUrlSource';

/**
 * @type Source
 * 
 * @export
 */
export type Source = { type: 'data' } & InputContentDataSource | { type: 'url' } & InputContentUrlSource;

export function SourceFromJSON(json: any): Source {
    return SourceFromJSONTyped(json, false);
}

export function SourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Source {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'data':
            return Object.assign({}, InputContentDataSourceFromJSONTyped(json, true), { type: 'data' } as const);
        case 'url':
            return Object.assign({}, InputContentUrlSourceFromJSONTyped(json, true), { type: 'url' } as const);
        default:
            return json;
    }
}

export function SourceToJSON(json: any): any {
    return SourceToJSONTyped(json, false);
}

export function SourceToJSONTyped(value?: Source | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'data':
            return Object.assign({}, InputContentDataSourceToJSON(value), { type: 'data' } as const);
        case 'url':
            return Object.assign({}, InputContentUrlSourceToJSON(value), { type: 'url' } as const);
        default:
            return value;
    }
}

