/* tslint:disable */
/* eslint-disable */
/**
 * gantry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Source } from './Source';
import {
    SourceFromJSON,
    SourceFromJSONTyped,
    SourceToJSON,
    SourceToJSONTyped,
} from './Source';

/**
 * A document input content fragment.
 * @export
 * @interface DocumentInputContent
 */
export interface DocumentInputContent {
    [key: string]: any | any;
    /**
     * 
     * @type {DocumentInputContentTypeEnum}
     * @memberof DocumentInputContent
     */
    type?: DocumentInputContentTypeEnum;
    /**
     * 
     * @type {Source}
     * @memberof DocumentInputContent
     */
    source: Source;
    /**
     * 
     * @type {}
     * @memberof DocumentInputContent
     */
    metadata?:  | null;
}


/**
 * @export
 */
export const DocumentInputContentTypeEnum = {
    Document: 'document'
} as const;
export type DocumentInputContentTypeEnum = typeof DocumentInputContentTypeEnum[keyof typeof DocumentInputContentTypeEnum];


/**
 * Check if a given object implements the DocumentInputContent interface.
 */
export function instanceOfDocumentInputContent(value: object): value is DocumentInputContent {
    if (!('source' in value) || value['source'] === undefined) return false;
    return true;
}

export function DocumentInputContentFromJSON(json: any): DocumentInputContent {
    return DocumentInputContentFromJSONTyped(json, false);
}

export function DocumentInputContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentInputContent {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'] == null ? undefined : json['type'],
        'source': SourceFromJSON(json['source']),
        'metadata': json['metadata'] == null ? undefined : FromJSON(json['metadata']),
    };
}

export function DocumentInputContentToJSON(json: any): DocumentInputContent {
    return DocumentInputContentToJSONTyped(json, false);
}

export function DocumentInputContentToJSONTyped(value?: DocumentInputContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'source': SourceToJSON(value['source']),
        'metadata': ToJSON(value['metadata']),
    };
}

