# coding: utf-8

"""
    gantry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.filters import Filters
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class QueryRagQueryByTextRequest(BaseModel):
    """
    DTO for querying RAG embeddings by text.
    """ # noqa: E501
    query_text: StrictStr
    top_k: Optional[Annotated[int, Field(le=100, strict=True, gt=0)]] = 5
    filters: Optional[Filters] = None
    hybrid_search: Optional[StrictBool] = Field(default=False, description="Whether to perform a hybrid search that combines vector similarity and BM25 text search. If true, the service will first use BM25 + semantic search to filter candidates and then rerank them using vector similarity.")
    hybrid_search_bm25_top_k: Optional[Annotated[int, Field(le=1000, strict=True, gt=0)]] = Field(default=5, description="When hybrid_search is true, this parameter controls the number of top candidates to retrieve using BM25 before reranking with vector similarity. A higher value may improve recall but increase latency.")
    hybrid_search_semantic_top_k: Optional[Annotated[int, Field(le=1000, strict=True, gt=0)]] = Field(default=5, description="When hybrid_search is true, this parameter controls the number of top candidates to retrieve using semantic search before reranking with vector similarity. A higher value may improve recall but increase latency.")
    hybrid_search_bm25_lang: Optional[StrictStr] = Field(default='simple', description="When hybrid_search is true, this parameter specifies the language to use for BM25 search. This can affect tokenization and stopword removal, which in turn can impact search results. The default 'simple' option applies basic tokenization and is suitable for many languages, but you may want to specify a particular language for better results with certain languages.")
    __properties: ClassVar[List[str]] = ["query_text", "top_k", "filters", "hybrid_search", "hybrid_search_bm25_top_k", "hybrid_search_semantic_top_k", "hybrid_search_bm25_lang"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QueryRagQueryByTextRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of filters
        if self.filters:
            _dict['filters'] = self.filters.to_dict()
        # set to None if filters (nullable) is None
        # and model_fields_set contains the field
        if self.filters is None and "filters" in self.model_fields_set:
            _dict['filters'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QueryRagQueryByTextRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "query_text": obj.get("query_text"),
            "top_k": obj.get("top_k") if obj.get("top_k") is not None else 5,
            "filters": Filters.from_dict(obj["filters"]) if obj.get("filters") is not None else None,
            "hybrid_search": obj.get("hybrid_search") if obj.get("hybrid_search") is not None else False,
            "hybrid_search_bm25_top_k": obj.get("hybrid_search_bm25_top_k") if obj.get("hybrid_search_bm25_top_k") is not None else 5,
            "hybrid_search_semantic_top_k": obj.get("hybrid_search_semantic_top_k") if obj.get("hybrid_search_semantic_top_k") is not None else 5,
            "hybrid_search_bm25_lang": obj.get("hybrid_search_bm25_lang") if obj.get("hybrid_search_bm25_lang") is not None else 'simple'
        })
        return _obj


