/*
gantry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QueryRagQueryByTextRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryRagQueryByTextRequest{}

// QueryRagQueryByTextRequest DTO for querying RAG embeddings by text.
type QueryRagQueryByTextRequest struct {
	QueryText string `json:"query_text"`
	TopK *int32 `json:"top_k,omitempty"`
	Filters NullableFilters `json:"filters,omitempty"`
	// Whether to perform a hybrid search that combines vector similarity and BM25 text search. If true, the service will first use BM25 + semantic search to filter candidates and then rerank them using vector similarity.
	HybridSearch *bool `json:"hybrid_search,omitempty"`
	// When hybrid_search is true, this parameter controls the number of top candidates to retrieve using BM25 before reranking with vector similarity. A higher value may improve recall but increase latency.
	HybridSearchBm25TopK *int32 `json:"hybrid_search_bm25_top_k,omitempty"`
	// When hybrid_search is true, this parameter controls the number of top candidates to retrieve using semantic search before reranking with vector similarity. A higher value may improve recall but increase latency.
	HybridSearchSemanticTopK *int32 `json:"hybrid_search_semantic_top_k,omitempty"`
	// When hybrid_search is true, this parameter specifies the language to use for BM25 search. This can affect tokenization and stopword removal, which in turn can impact search results. The default 'simple' option applies basic tokenization and is suitable for many languages, but you may want to specify a particular language for better results with certain languages.
	HybridSearchBm25Lang *string `json:"hybrid_search_bm25_lang,omitempty"`
}

type _QueryRagQueryByTextRequest QueryRagQueryByTextRequest

// NewQueryRagQueryByTextRequest instantiates a new QueryRagQueryByTextRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryRagQueryByTextRequest(queryText string) *QueryRagQueryByTextRequest {
	this := QueryRagQueryByTextRequest{}
	this.QueryText = queryText
	var topK int32 = 5
	this.TopK = &topK
	var hybridSearch bool = false
	this.HybridSearch = &hybridSearch
	var hybridSearchBm25TopK int32 = 5
	this.HybridSearchBm25TopK = &hybridSearchBm25TopK
	var hybridSearchSemanticTopK int32 = 5
	this.HybridSearchSemanticTopK = &hybridSearchSemanticTopK
	var hybridSearchBm25Lang string = "simple"
	this.HybridSearchBm25Lang = &hybridSearchBm25Lang
	return &this
}

// NewQueryRagQueryByTextRequestWithDefaults instantiates a new QueryRagQueryByTextRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryRagQueryByTextRequestWithDefaults() *QueryRagQueryByTextRequest {
	this := QueryRagQueryByTextRequest{}
	var topK int32 = 5
	this.TopK = &topK
	var hybridSearch bool = false
	this.HybridSearch = &hybridSearch
	var hybridSearchBm25TopK int32 = 5
	this.HybridSearchBm25TopK = &hybridSearchBm25TopK
	var hybridSearchSemanticTopK int32 = 5
	this.HybridSearchSemanticTopK = &hybridSearchSemanticTopK
	var hybridSearchBm25Lang string = "simple"
	this.HybridSearchBm25Lang = &hybridSearchBm25Lang
	return &this
}

// GetQueryText returns the QueryText field value
func (o *QueryRagQueryByTextRequest) GetQueryText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QueryText
}

// GetQueryTextOk returns a tuple with the QueryText field value
// and a boolean to check if the value has been set.
func (o *QueryRagQueryByTextRequest) GetQueryTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QueryText, true
}

// SetQueryText sets field value
func (o *QueryRagQueryByTextRequest) SetQueryText(v string) {
	o.QueryText = v
}

// GetTopK returns the TopK field value if set, zero value otherwise.
func (o *QueryRagQueryByTextRequest) GetTopK() int32 {
	if o == nil || IsNil(o.TopK) {
		var ret int32
		return ret
	}
	return *o.TopK
}

// GetTopKOk returns a tuple with the TopK field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryRagQueryByTextRequest) GetTopKOk() (*int32, bool) {
	if o == nil || IsNil(o.TopK) {
		return nil, false
	}
	return o.TopK, true
}

// HasTopK returns a boolean if a field has been set.
func (o *QueryRagQueryByTextRequest) HasTopK() bool {
	if o != nil && !IsNil(o.TopK) {
		return true
	}

	return false
}

// SetTopK gets a reference to the given int32 and assigns it to the TopK field.
func (o *QueryRagQueryByTextRequest) SetTopK(v int32) {
	o.TopK = &v
}

// GetFilters returns the Filters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryRagQueryByTextRequest) GetFilters() Filters {
	if o == nil || IsNil(o.Filters.Get()) {
		var ret Filters
		return ret
	}
	return *o.Filters.Get()
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryRagQueryByTextRequest) GetFiltersOk() (*Filters, bool) {
	if o == nil {
		return nil, false
	}
	return o.Filters.Get(), o.Filters.IsSet()
}

// HasFilters returns a boolean if a field has been set.
func (o *QueryRagQueryByTextRequest) HasFilters() bool {
	if o != nil && o.Filters.IsSet() {
		return true
	}

	return false
}

// SetFilters gets a reference to the given NullableFilters and assigns it to the Filters field.
func (o *QueryRagQueryByTextRequest) SetFilters(v Filters) {
	o.Filters.Set(&v)
}
// SetFiltersNil sets the value for Filters to be an explicit nil
func (o *QueryRagQueryByTextRequest) SetFiltersNil() {
	o.Filters.Set(nil)
}

// UnsetFilters ensures that no value is present for Filters, not even an explicit nil
func (o *QueryRagQueryByTextRequest) UnsetFilters() {
	o.Filters.Unset()
}

// GetHybridSearch returns the HybridSearch field value if set, zero value otherwise.
func (o *QueryRagQueryByTextRequest) GetHybridSearch() bool {
	if o == nil || IsNil(o.HybridSearch) {
		var ret bool
		return ret
	}
	return *o.HybridSearch
}

// GetHybridSearchOk returns a tuple with the HybridSearch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryRagQueryByTextRequest) GetHybridSearchOk() (*bool, bool) {
	if o == nil || IsNil(o.HybridSearch) {
		return nil, false
	}
	return o.HybridSearch, true
}

// HasHybridSearch returns a boolean if a field has been set.
func (o *QueryRagQueryByTextRequest) HasHybridSearch() bool {
	if o != nil && !IsNil(o.HybridSearch) {
		return true
	}

	return false
}

// SetHybridSearch gets a reference to the given bool and assigns it to the HybridSearch field.
func (o *QueryRagQueryByTextRequest) SetHybridSearch(v bool) {
	o.HybridSearch = &v
}

// GetHybridSearchBm25TopK returns the HybridSearchBm25TopK field value if set, zero value otherwise.
func (o *QueryRagQueryByTextRequest) GetHybridSearchBm25TopK() int32 {
	if o == nil || IsNil(o.HybridSearchBm25TopK) {
		var ret int32
		return ret
	}
	return *o.HybridSearchBm25TopK
}

// GetHybridSearchBm25TopKOk returns a tuple with the HybridSearchBm25TopK field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryRagQueryByTextRequest) GetHybridSearchBm25TopKOk() (*int32, bool) {
	if o == nil || IsNil(o.HybridSearchBm25TopK) {
		return nil, false
	}
	return o.HybridSearchBm25TopK, true
}

// HasHybridSearchBm25TopK returns a boolean if a field has been set.
func (o *QueryRagQueryByTextRequest) HasHybridSearchBm25TopK() bool {
	if o != nil && !IsNil(o.HybridSearchBm25TopK) {
		return true
	}

	return false
}

// SetHybridSearchBm25TopK gets a reference to the given int32 and assigns it to the HybridSearchBm25TopK field.
func (o *QueryRagQueryByTextRequest) SetHybridSearchBm25TopK(v int32) {
	o.HybridSearchBm25TopK = &v
}

// GetHybridSearchSemanticTopK returns the HybridSearchSemanticTopK field value if set, zero value otherwise.
func (o *QueryRagQueryByTextRequest) GetHybridSearchSemanticTopK() int32 {
	if o == nil || IsNil(o.HybridSearchSemanticTopK) {
		var ret int32
		return ret
	}
	return *o.HybridSearchSemanticTopK
}

// GetHybridSearchSemanticTopKOk returns a tuple with the HybridSearchSemanticTopK field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryRagQueryByTextRequest) GetHybridSearchSemanticTopKOk() (*int32, bool) {
	if o == nil || IsNil(o.HybridSearchSemanticTopK) {
		return nil, false
	}
	return o.HybridSearchSemanticTopK, true
}

// HasHybridSearchSemanticTopK returns a boolean if a field has been set.
func (o *QueryRagQueryByTextRequest) HasHybridSearchSemanticTopK() bool {
	if o != nil && !IsNil(o.HybridSearchSemanticTopK) {
		return true
	}

	return false
}

// SetHybridSearchSemanticTopK gets a reference to the given int32 and assigns it to the HybridSearchSemanticTopK field.
func (o *QueryRagQueryByTextRequest) SetHybridSearchSemanticTopK(v int32) {
	o.HybridSearchSemanticTopK = &v
}

// GetHybridSearchBm25Lang returns the HybridSearchBm25Lang field value if set, zero value otherwise.
func (o *QueryRagQueryByTextRequest) GetHybridSearchBm25Lang() string {
	if o == nil || IsNil(o.HybridSearchBm25Lang) {
		var ret string
		return ret
	}
	return *o.HybridSearchBm25Lang
}

// GetHybridSearchBm25LangOk returns a tuple with the HybridSearchBm25Lang field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryRagQueryByTextRequest) GetHybridSearchBm25LangOk() (*string, bool) {
	if o == nil || IsNil(o.HybridSearchBm25Lang) {
		return nil, false
	}
	return o.HybridSearchBm25Lang, true
}

// HasHybridSearchBm25Lang returns a boolean if a field has been set.
func (o *QueryRagQueryByTextRequest) HasHybridSearchBm25Lang() bool {
	if o != nil && !IsNil(o.HybridSearchBm25Lang) {
		return true
	}

	return false
}

// SetHybridSearchBm25Lang gets a reference to the given string and assigns it to the HybridSearchBm25Lang field.
func (o *QueryRagQueryByTextRequest) SetHybridSearchBm25Lang(v string) {
	o.HybridSearchBm25Lang = &v
}

func (o QueryRagQueryByTextRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryRagQueryByTextRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["query_text"] = o.QueryText
	if !IsNil(o.TopK) {
		toSerialize["top_k"] = o.TopK
	}
	if o.Filters.IsSet() {
		toSerialize["filters"] = o.Filters.Get()
	}
	if !IsNil(o.HybridSearch) {
		toSerialize["hybrid_search"] = o.HybridSearch
	}
	if !IsNil(o.HybridSearchBm25TopK) {
		toSerialize["hybrid_search_bm25_top_k"] = o.HybridSearchBm25TopK
	}
	if !IsNil(o.HybridSearchSemanticTopK) {
		toSerialize["hybrid_search_semantic_top_k"] = o.HybridSearchSemanticTopK
	}
	if !IsNil(o.HybridSearchBm25Lang) {
		toSerialize["hybrid_search_bm25_lang"] = o.HybridSearchBm25Lang
	}
	return toSerialize, nil
}

func (o *QueryRagQueryByTextRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"query_text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueryRagQueryByTextRequest := _QueryRagQueryByTextRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQueryRagQueryByTextRequest)

	if err != nil {
		return err
	}

	*o = QueryRagQueryByTextRequest(varQueryRagQueryByTextRequest)

	return err
}

type NullableQueryRagQueryByTextRequest struct {
	value *QueryRagQueryByTextRequest
	isSet bool
}

func (v NullableQueryRagQueryByTextRequest) Get() *QueryRagQueryByTextRequest {
	return v.value
}

func (v *NullableQueryRagQueryByTextRequest) Set(val *QueryRagQueryByTextRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryRagQueryByTextRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryRagQueryByTextRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryRagQueryByTextRequest(val *QueryRagQueryByTextRequest) *NullableQueryRagQueryByTextRequest {
	return &NullableQueryRagQueryByTextRequest{value: val, isSet: true}
}

func (v NullableQueryRagQueryByTextRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryRagQueryByTextRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


