/*
gantry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ChunkSplitterType the model 'ChunkSplitterType'
type ChunkSplitterType string

// List of ChunkSplitterType
const (
	SIMPLE ChunkSplitterType = "simple"
	CHARACTER ChunkSplitterType = "character"
	RECURSIVE ChunkSplitterType = "recursive"
	TOKEN ChunkSplitterType = "token"
	MARKDOWN ChunkSplitterType = "markdown"
	MARKDOWN_HEADER ChunkSplitterType = "markdown_header"
	HTML ChunkSplitterType = "html"
	HTML_HEADER ChunkSplitterType = "html_header"
	HTML_SEMANTIC_PRESERVING ChunkSplitterType = "html_semantic_preserving"
	HTML_SECTION ChunkSplitterType = "html_section"
	RECURSIVE_JSON ChunkSplitterType = "recursive_json"
	EXPERIMENTAL_MARKDOWN_SYNTAX ChunkSplitterType = "experimental_markdown_syntax"
	CODE_LANGUAGE_C ChunkSplitterType = "code_language_c"
	CODE_LANGUAGE_COBOL ChunkSplitterType = "code_language_cobol"
	CODE_LANGUAGE_CPP ChunkSplitterType = "code_language_cpp"
	CODE_LANGUAGE_CSHARP ChunkSplitterType = "code_language_csharp"
	CODE_LANGUAGE_GO ChunkSplitterType = "code_language_go"
	CODE_LANGUAGE_HASKELL ChunkSplitterType = "code_language_haskell"
	CODE_LANGUAGE_HTML ChunkSplitterType = "code_language_html"
	CODE_LANGUAGE_JAVA ChunkSplitterType = "code_language_java"
	CODE_LANGUAGE_JSX ChunkSplitterType = "code_language_jsx"
	CODE_LANGUAGE_KOTLIN ChunkSplitterType = "code_language_kotlin"
	CODE_LANGUAGE_LATEX ChunkSplitterType = "code_language_latex"
	CODE_LANGUAGE_LUA ChunkSplitterType = "code_language_lua"
	CODE_LANGUAGE_MARKDOWN ChunkSplitterType = "code_language_markdown"
	CODE_LANGUAGE_PERL ChunkSplitterType = "code_language_perl"
	CODE_LANGUAGE_PHP ChunkSplitterType = "code_language_php"
	CODE_LANGUAGE_PROTO ChunkSplitterType = "code_language_proto"
	CODE_LANGUAGE_PYTHON ChunkSplitterType = "code_language_python"
	CODE_LANGUAGE_RST ChunkSplitterType = "code_language_rst"
	CODE_LANGUAGE_RUBY ChunkSplitterType = "code_language_ruby"
	CODE_LANGUAGE_RUST ChunkSplitterType = "code_language_rust"
	CODE_LANGUAGE_SCALA ChunkSplitterType = "code_language_scala"
	CODE_LANGUAGE_SOL ChunkSplitterType = "code_language_sol"
	CODE_LANGUAGE_SWIFT ChunkSplitterType = "code_language_swift"
	CODE_LANGUAGE_TS ChunkSplitterType = "code_language_ts"
	CODE_LANGUAGE_JS ChunkSplitterType = "code_language_js"
	LATEX ChunkSplitterType = "latex"
	NLTK ChunkSplitterType = "nltk"
	SPACY ChunkSplitterType = "spacy"
	KONLPY ChunkSplitterType = "konlpy"
	SENTENCE_TRANSFORMERS_TOKEN ChunkSplitterType = "sentence_transformers_token"
	PARAGRAPH ChunkSplitterType = "paragraph"
	LINE ChunkSplitterType = "line"
)

// All allowed values of ChunkSplitterType enum
var AllowedChunkSplitterTypeEnumValues = []ChunkSplitterType{
	"simple",
	"character",
	"recursive",
	"token",
	"markdown",
	"markdown_header",
	"html",
	"html_header",
	"html_semantic_preserving",
	"html_section",
	"recursive_json",
	"experimental_markdown_syntax",
	"code_language_c",
	"code_language_cobol",
	"code_language_cpp",
	"code_language_csharp",
	"code_language_go",
	"code_language_haskell",
	"code_language_html",
	"code_language_java",
	"code_language_jsx",
	"code_language_kotlin",
	"code_language_latex",
	"code_language_lua",
	"code_language_markdown",
	"code_language_perl",
	"code_language_php",
	"code_language_proto",
	"code_language_python",
	"code_language_rst",
	"code_language_ruby",
	"code_language_rust",
	"code_language_scala",
	"code_language_sol",
	"code_language_swift",
	"code_language_ts",
	"code_language_js",
	"latex",
	"nltk",
	"spacy",
	"konlpy",
	"sentence_transformers_token",
	"paragraph",
	"line",
}

func (v *ChunkSplitterType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ChunkSplitterType(value)
	for _, existing := range AllowedChunkSplitterTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ChunkSplitterType", value)
}

// NewChunkSplitterTypeFromValue returns a pointer to a valid ChunkSplitterType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewChunkSplitterTypeFromValue(v string) (*ChunkSplitterType, error) {
	ev := ChunkSplitterType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ChunkSplitterType: valid values are %v", v, AllowedChunkSplitterTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ChunkSplitterType) IsValid() bool {
	for _, existing := range AllowedChunkSplitterTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ChunkSplitterType value
func (v ChunkSplitterType) Ptr() *ChunkSplitterType {
	return &v
}

type NullableChunkSplitterType struct {
	value *ChunkSplitterType
	isSet bool
}

func (v NullableChunkSplitterType) Get() *ChunkSplitterType {
	return v.value
}

func (v *NullableChunkSplitterType) Set(val *ChunkSplitterType) {
	v.value = val
	v.isSet = true
}

func (v NullableChunkSplitterType) IsSet() bool {
	return v.isSet
}

func (v *NullableChunkSplitterType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChunkSplitterType(val *ChunkSplitterType) *NullableChunkSplitterType {
	return &NullableChunkSplitterType{value: val, isSet: true}
}

func (v NullableChunkSplitterType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChunkSplitterType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

