/*
gantry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// AiGatewayAPIService AiGatewayAPI service
type AiGatewayAPIService service

type ApiAgUiGatewayAiGatewayAgUiModelPostRequest struct {
	ctx context.Context
	ApiService *AiGatewayAPIService
	model string
	projectId *string
	runAgentInputWithModelSettings *RunAgentInputWithModelSettings
}

func (r ApiAgUiGatewayAiGatewayAgUiModelPostRequest) ProjectId(projectId string) ApiAgUiGatewayAiGatewayAgUiModelPostRequest {
	r.projectId = &projectId
	return r
}

func (r ApiAgUiGatewayAiGatewayAgUiModelPostRequest) RunAgentInputWithModelSettings(runAgentInputWithModelSettings RunAgentInputWithModelSettings) ApiAgUiGatewayAiGatewayAgUiModelPostRequest {
	r.runAgentInputWithModelSettings = &runAgentInputWithModelSettings
	return r
}

func (r ApiAgUiGatewayAiGatewayAgUiModelPostRequest) Execute() (*ResponseAgUiGatewayAiGatewayAgUiModelPost, *http.Response, error) {
	return r.ApiService.AgUiGatewayAiGatewayAgUiModelPostExecute(r)
}

/*
AgUiGatewayAiGatewayAgUiModelPost Ag Ui Gateway

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param model
 @return ApiAgUiGatewayAiGatewayAgUiModelPostRequest
*/
func (a *AiGatewayAPIService) AgUiGatewayAiGatewayAgUiModelPost(ctx context.Context, model string) ApiAgUiGatewayAiGatewayAgUiModelPostRequest {
	return ApiAgUiGatewayAiGatewayAgUiModelPostRequest{
		ApiService: a,
		ctx: ctx,
		model: model,
	}
}

// Execute executes the request
//  @return ResponseAgUiGatewayAiGatewayAgUiModelPost
func (a *AiGatewayAPIService) AgUiGatewayAiGatewayAgUiModelPostExecute(r ApiAgUiGatewayAiGatewayAgUiModelPostRequest) (*ResponseAgUiGatewayAiGatewayAgUiModelPost, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ResponseAgUiGatewayAiGatewayAgUiModelPost
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AiGatewayAPIService.AgUiGatewayAiGatewayAgUiModelPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/ai-gateway/ag-ui/{model}"
	localVarPath = strings.Replace(localVarPath, "{"+"model"+"}", url.PathEscape(parameterValueToString(r.model, "model")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.projectId == nil {
		return localVarReturnValue, nil, reportError("projectId is required and must be specified")
	}
	if r.runAgentInputWithModelSettings == nil {
		return localVarReturnValue, nil, reportError("runAgentInputWithModelSettings is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "project_id", r.projectId, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.runAgentInputWithModelSettings
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetModelsAiGatewayModelsGetRequest struct {
	ctx context.Context
	ApiService *AiGatewayAPIService
}

func (r ApiGetModelsAiGatewayModelsGetRequest) Execute() ([]string, *http.Response, error) {
	return r.ApiService.GetModelsAiGatewayModelsGetExecute(r)
}

/*
GetModelsAiGatewayModelsGet Get Models

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetModelsAiGatewayModelsGetRequest
*/
func (a *AiGatewayAPIService) GetModelsAiGatewayModelsGet(ctx context.Context) ApiGetModelsAiGatewayModelsGetRequest {
	return ApiGetModelsAiGatewayModelsGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []string
func (a *AiGatewayAPIService) GetModelsAiGatewayModelsGetExecute(r ApiGetModelsAiGatewayModelsGetRequest) ([]string, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []string
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AiGatewayAPIService.GetModelsAiGatewayModelsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/ai-gateway/models"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
