/*
gantry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmbeddingTaskResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmbeddingTaskResponse{}

// EmbeddingTaskResponse DTO for RAG embedding task status response.
type EmbeddingTaskResponse struct {
	TaskId string `json:"task_id"`
	FileUid NullableString `json:"file_uid"`
	Text NullableText1 `json:"text"`
	Metadata map[string]interface{} `json:"metadata"`
	Type string `json:"type"`
	ProjectUuid string `json:"project_uuid"`
	ChunkSplitter ChunkSplitterType `json:"chunk_splitter"`
	ChunkSplitterOptions *ChunkSplitterOptions `json:"chunk_splitter_options,omitempty"`
	ChunkSize int32 `json:"chunk_size"`
	ChunkOverlap int32 `json:"chunk_overlap"`
	FailedReason NullableString `json:"failed_reason,omitempty"`
	Status string `json:"status"`
}

type _EmbeddingTaskResponse EmbeddingTaskResponse

// NewEmbeddingTaskResponse instantiates a new EmbeddingTaskResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmbeddingTaskResponse(taskId string, fileUid NullableString, text NullableText1, metadata map[string]interface{}, type_ string, projectUuid string, chunkSplitter ChunkSplitterType, chunkSize int32, chunkOverlap int32, status string) *EmbeddingTaskResponse {
	this := EmbeddingTaskResponse{}
	this.TaskId = taskId
	this.FileUid = fileUid
	this.Text = text
	this.Metadata = metadata
	this.Type = type_
	this.ProjectUuid = projectUuid
	this.ChunkSplitter = chunkSplitter
	this.ChunkSize = chunkSize
	this.ChunkOverlap = chunkOverlap
	this.Status = status
	return &this
}

// NewEmbeddingTaskResponseWithDefaults instantiates a new EmbeddingTaskResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmbeddingTaskResponseWithDefaults() *EmbeddingTaskResponse {
	this := EmbeddingTaskResponse{}
	return &this
}

// GetTaskId returns the TaskId field value
func (o *EmbeddingTaskResponse) GetTaskId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value
// and a boolean to check if the value has been set.
func (o *EmbeddingTaskResponse) GetTaskIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskId, true
}

// SetTaskId sets field value
func (o *EmbeddingTaskResponse) SetTaskId(v string) {
	o.TaskId = v
}

// GetFileUid returns the FileUid field value
// If the value is explicit nil, the zero value for string will be returned
func (o *EmbeddingTaskResponse) GetFileUid() string {
	if o == nil || o.FileUid.Get() == nil {
		var ret string
		return ret
	}

	return *o.FileUid.Get()
}

// GetFileUidOk returns a tuple with the FileUid field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmbeddingTaskResponse) GetFileUidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FileUid.Get(), o.FileUid.IsSet()
}

// SetFileUid sets field value
func (o *EmbeddingTaskResponse) SetFileUid(v string) {
	o.FileUid.Set(&v)
}

// GetText returns the Text field value
// If the value is explicit nil, the zero value for Text1 will be returned
func (o *EmbeddingTaskResponse) GetText() Text1 {
	if o == nil || o.Text.Get() == nil {
		var ret Text1
		return ret
	}

	return *o.Text.Get()
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmbeddingTaskResponse) GetTextOk() (*Text1, bool) {
	if o == nil {
		return nil, false
	}
	return o.Text.Get(), o.Text.IsSet()
}

// SetText sets field value
func (o *EmbeddingTaskResponse) SetText(v Text1) {
	o.Text.Set(&v)
}

// GetMetadata returns the Metadata field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *EmbeddingTaskResponse) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmbeddingTaskResponse) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// SetMetadata sets field value
func (o *EmbeddingTaskResponse) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetType returns the Type field value
func (o *EmbeddingTaskResponse) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EmbeddingTaskResponse) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EmbeddingTaskResponse) SetType(v string) {
	o.Type = v
}

// GetProjectUuid returns the ProjectUuid field value
func (o *EmbeddingTaskResponse) GetProjectUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectUuid
}

// GetProjectUuidOk returns a tuple with the ProjectUuid field value
// and a boolean to check if the value has been set.
func (o *EmbeddingTaskResponse) GetProjectUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectUuid, true
}

// SetProjectUuid sets field value
func (o *EmbeddingTaskResponse) SetProjectUuid(v string) {
	o.ProjectUuid = v
}

// GetChunkSplitter returns the ChunkSplitter field value
func (o *EmbeddingTaskResponse) GetChunkSplitter() ChunkSplitterType {
	if o == nil {
		var ret ChunkSplitterType
		return ret
	}

	return o.ChunkSplitter
}

// GetChunkSplitterOk returns a tuple with the ChunkSplitter field value
// and a boolean to check if the value has been set.
func (o *EmbeddingTaskResponse) GetChunkSplitterOk() (*ChunkSplitterType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChunkSplitter, true
}

// SetChunkSplitter sets field value
func (o *EmbeddingTaskResponse) SetChunkSplitter(v ChunkSplitterType) {
	o.ChunkSplitter = v
}

// GetChunkSplitterOptions returns the ChunkSplitterOptions field value if set, zero value otherwise.
func (o *EmbeddingTaskResponse) GetChunkSplitterOptions() ChunkSplitterOptions {
	if o == nil || IsNil(o.ChunkSplitterOptions) {
		var ret ChunkSplitterOptions
		return ret
	}
	return *o.ChunkSplitterOptions
}

// GetChunkSplitterOptionsOk returns a tuple with the ChunkSplitterOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbeddingTaskResponse) GetChunkSplitterOptionsOk() (*ChunkSplitterOptions, bool) {
	if o == nil || IsNil(o.ChunkSplitterOptions) {
		return nil, false
	}
	return o.ChunkSplitterOptions, true
}

// HasChunkSplitterOptions returns a boolean if a field has been set.
func (o *EmbeddingTaskResponse) HasChunkSplitterOptions() bool {
	if o != nil && !IsNil(o.ChunkSplitterOptions) {
		return true
	}

	return false
}

// SetChunkSplitterOptions gets a reference to the given ChunkSplitterOptions and assigns it to the ChunkSplitterOptions field.
func (o *EmbeddingTaskResponse) SetChunkSplitterOptions(v ChunkSplitterOptions) {
	o.ChunkSplitterOptions = &v
}

// GetChunkSize returns the ChunkSize field value
func (o *EmbeddingTaskResponse) GetChunkSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChunkSize
}

// GetChunkSizeOk returns a tuple with the ChunkSize field value
// and a boolean to check if the value has been set.
func (o *EmbeddingTaskResponse) GetChunkSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChunkSize, true
}

// SetChunkSize sets field value
func (o *EmbeddingTaskResponse) SetChunkSize(v int32) {
	o.ChunkSize = v
}

// GetChunkOverlap returns the ChunkOverlap field value
func (o *EmbeddingTaskResponse) GetChunkOverlap() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChunkOverlap
}

// GetChunkOverlapOk returns a tuple with the ChunkOverlap field value
// and a boolean to check if the value has been set.
func (o *EmbeddingTaskResponse) GetChunkOverlapOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChunkOverlap, true
}

// SetChunkOverlap sets field value
func (o *EmbeddingTaskResponse) SetChunkOverlap(v int32) {
	o.ChunkOverlap = v
}

// GetFailedReason returns the FailedReason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmbeddingTaskResponse) GetFailedReason() string {
	if o == nil || IsNil(o.FailedReason.Get()) {
		var ret string
		return ret
	}
	return *o.FailedReason.Get()
}

// GetFailedReasonOk returns a tuple with the FailedReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmbeddingTaskResponse) GetFailedReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FailedReason.Get(), o.FailedReason.IsSet()
}

// HasFailedReason returns a boolean if a field has been set.
func (o *EmbeddingTaskResponse) HasFailedReason() bool {
	if o != nil && o.FailedReason.IsSet() {
		return true
	}

	return false
}

// SetFailedReason gets a reference to the given NullableString and assigns it to the FailedReason field.
func (o *EmbeddingTaskResponse) SetFailedReason(v string) {
	o.FailedReason.Set(&v)
}
// SetFailedReasonNil sets the value for FailedReason to be an explicit nil
func (o *EmbeddingTaskResponse) SetFailedReasonNil() {
	o.FailedReason.Set(nil)
}

// UnsetFailedReason ensures that no value is present for FailedReason, not even an explicit nil
func (o *EmbeddingTaskResponse) UnsetFailedReason() {
	o.FailedReason.Unset()
}

// GetStatus returns the Status field value
func (o *EmbeddingTaskResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *EmbeddingTaskResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *EmbeddingTaskResponse) SetStatus(v string) {
	o.Status = v
}

func (o EmbeddingTaskResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmbeddingTaskResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["task_id"] = o.TaskId
	toSerialize["file_uid"] = o.FileUid.Get()
	toSerialize["text"] = o.Text.Get()
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["type"] = o.Type
	toSerialize["project_uuid"] = o.ProjectUuid
	toSerialize["chunk_splitter"] = o.ChunkSplitter
	if !IsNil(o.ChunkSplitterOptions) {
		toSerialize["chunk_splitter_options"] = o.ChunkSplitterOptions
	}
	toSerialize["chunk_size"] = o.ChunkSize
	toSerialize["chunk_overlap"] = o.ChunkOverlap
	if o.FailedReason.IsSet() {
		toSerialize["failed_reason"] = o.FailedReason.Get()
	}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *EmbeddingTaskResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"task_id",
		"file_uid",
		"text",
		"metadata",
		"type",
		"project_uuid",
		"chunk_splitter",
		"chunk_size",
		"chunk_overlap",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmbeddingTaskResponse := _EmbeddingTaskResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmbeddingTaskResponse)

	if err != nil {
		return err
	}

	*o = EmbeddingTaskResponse(varEmbeddingTaskResponse)

	return err
}

type NullableEmbeddingTaskResponse struct {
	value *EmbeddingTaskResponse
	isSet bool
}

func (v NullableEmbeddingTaskResponse) Get() *EmbeddingTaskResponse {
	return v.value
}

func (v *NullableEmbeddingTaskResponse) Set(val *EmbeddingTaskResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEmbeddingTaskResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEmbeddingTaskResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmbeddingTaskResponse(val *EmbeddingTaskResponse) *NullableEmbeddingTaskResponse {
	return &NullableEmbeddingTaskResponse{value: val, isSet: true}
}

func (v NullableEmbeddingTaskResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmbeddingTaskResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


