/*
gantry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the MessagesSnapshotEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessagesSnapshotEvent{}

// MessagesSnapshotEvent Event containing a snapshot of the messages.
type MessagesSnapshotEvent struct {
	Type *string `json:"type,omitempty"`
	Timestamp NullableInt32 `json:"timestamp,omitempty"`
	RawEvent NullableAnyOf `json:"rawEvent,omitempty"`
	Messages []MessagesInner `json:"messages"`
	AdditionalProperties map[string]interface{}
}

type _MessagesSnapshotEvent MessagesSnapshotEvent

// NewMessagesSnapshotEvent instantiates a new MessagesSnapshotEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessagesSnapshotEvent(messages []MessagesInner) *MessagesSnapshotEvent {
	this := MessagesSnapshotEvent{}
	var type_ string = "MESSAGES_SNAPSHOT"
	this.Type = &type_
	this.Messages = messages
	return &this
}

// NewMessagesSnapshotEventWithDefaults instantiates a new MessagesSnapshotEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessagesSnapshotEventWithDefaults() *MessagesSnapshotEvent {
	this := MessagesSnapshotEvent{}
	var type_ string = "MESSAGES_SNAPSHOT"
	this.Type = &type_
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *MessagesSnapshotEvent) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessagesSnapshotEvent) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *MessagesSnapshotEvent) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *MessagesSnapshotEvent) SetType(v string) {
	o.Type = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MessagesSnapshotEvent) GetTimestamp() int32 {
	if o == nil || IsNil(o.Timestamp.Get()) {
		var ret int32
		return ret
	}
	return *o.Timestamp.Get()
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MessagesSnapshotEvent) GetTimestampOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timestamp.Get(), o.Timestamp.IsSet()
}

// HasTimestamp returns a boolean if a field has been set.
func (o *MessagesSnapshotEvent) HasTimestamp() bool {
	if o != nil && o.Timestamp.IsSet() {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given NullableInt32 and assigns it to the Timestamp field.
func (o *MessagesSnapshotEvent) SetTimestamp(v int32) {
	o.Timestamp.Set(&v)
}
// SetTimestampNil sets the value for Timestamp to be an explicit nil
func (o *MessagesSnapshotEvent) SetTimestampNil() {
	o.Timestamp.Set(nil)
}

// UnsetTimestamp ensures that no value is present for Timestamp, not even an explicit nil
func (o *MessagesSnapshotEvent) UnsetTimestamp() {
	o.Timestamp.Unset()
}

// GetRawEvent returns the RawEvent field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MessagesSnapshotEvent) GetRawEvent() AnyOf {
	if o == nil || IsNil(o.RawEvent.Get()) {
		var ret AnyOf
		return ret
	}
	return *o.RawEvent.Get()
}

// GetRawEventOk returns a tuple with the RawEvent field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MessagesSnapshotEvent) GetRawEventOk() (*AnyOf, bool) {
	if o == nil {
		return nil, false
	}
	return o.RawEvent.Get(), o.RawEvent.IsSet()
}

// HasRawEvent returns a boolean if a field has been set.
func (o *MessagesSnapshotEvent) HasRawEvent() bool {
	if o != nil && o.RawEvent.IsSet() {
		return true
	}

	return false
}

// SetRawEvent gets a reference to the given NullableAnyOf and assigns it to the RawEvent field.
func (o *MessagesSnapshotEvent) SetRawEvent(v AnyOf) {
	o.RawEvent.Set(&v)
}
// SetRawEventNil sets the value for RawEvent to be an explicit nil
func (o *MessagesSnapshotEvent) SetRawEventNil() {
	o.RawEvent.Set(nil)
}

// UnsetRawEvent ensures that no value is present for RawEvent, not even an explicit nil
func (o *MessagesSnapshotEvent) UnsetRawEvent() {
	o.RawEvent.Unset()
}

// GetMessages returns the Messages field value
func (o *MessagesSnapshotEvent) GetMessages() []MessagesInner {
	if o == nil {
		var ret []MessagesInner
		return ret
	}

	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value
// and a boolean to check if the value has been set.
func (o *MessagesSnapshotEvent) GetMessagesOk() ([]MessagesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Messages, true
}

// SetMessages sets field value
func (o *MessagesSnapshotEvent) SetMessages(v []MessagesInner) {
	o.Messages = v
}

func (o MessagesSnapshotEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessagesSnapshotEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if o.Timestamp.IsSet() {
		toSerialize["timestamp"] = o.Timestamp.Get()
	}
	if o.RawEvent.IsSet() {
		toSerialize["rawEvent"] = o.RawEvent.Get()
	}
	toSerialize["messages"] = o.Messages

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MessagesSnapshotEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"messages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMessagesSnapshotEvent := _MessagesSnapshotEvent{}

	err = json.Unmarshal(data, &varMessagesSnapshotEvent)

	if err != nil {
		return err
	}

	*o = MessagesSnapshotEvent(varMessagesSnapshotEvent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "timestamp")
		delete(additionalProperties, "rawEvent")
		delete(additionalProperties, "messages")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMessagesSnapshotEvent struct {
	value *MessagesSnapshotEvent
	isSet bool
}

func (v NullableMessagesSnapshotEvent) Get() *MessagesSnapshotEvent {
	return v.value
}

func (v *NullableMessagesSnapshotEvent) Set(val *MessagesSnapshotEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableMessagesSnapshotEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableMessagesSnapshotEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessagesSnapshotEvent(val *MessagesSnapshotEvent) *NullableMessagesSnapshotEvent {
	return &NullableMessagesSnapshotEvent{value: val, isSet: true}
}

func (v NullableMessagesSnapshotEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessagesSnapshotEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


